within Pharmacolibrary.UsersGuide;

class ReleaseNotes
  extends Modelica.Icons.ReleaseNotes;
  annotation(
    Documentation(info = "<html><head></head><body><h5>Version 26.09</h5><ul><li><b>Drugs.ATC and Drugs.Common removed.</b> Each generated model Drugs.ATC.{L1}.{code} was folded into its model in the ATC packages (Drugs.{L1}_….{L3}_….{code}_{Drug}.{Drug}), which now extends the Pharmacokinetic template directly; models that modified the ATC model keep their own values. Simulation results are unchanged.</li><li>A model extending Drugs.ATC.… is converted on load (Resources/Scripts/Conversion/ConvertFromPharmacolibrary_25.09.mos). Drugs.Common.DrugData (molecular data) has no replacement: models set the molar mass as a parameter.</li><li>Examples that extended Drugs.ATC models extend the template with the same values.</li><li>Paracetamol_healthy: molar mass is a parameter (it read a field the record did not have).</li></ul><h5><ul style=\"color: rgb(0, 0, 0); font-family: -webkit-standard; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0.4); -webkit-text-stroke-width: 0px;\"></ul></h5><h5 style=\"color: rgb(0, 0, 0); font-family: -webkit-standard; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0.4); -webkit-text-stroke-width: 0px;\">Version 25.08-beta1</h5><div><ul><li>generated models of all drugs in Drugs.ATC</li><li>tested in OpenModelica 1.25 and Dymola 2025</li><li>added example of PKPD integrated with Physiolibrary 3.0.0</li><li>added example of PGx with various combination of pharmacogene mutation and it's influence on PK</li></ul></div><h5>Version 25.05-beta.3</h5>
<ul>
<li>Introduction of first version&nbsp;</li></ul>

</body></html>"));
end ReleaseNotes;