within Pharmacolibrary.Drugs.N_NervousSystem.N05B_Anxiolytics.N05BA01_Diazepam;
model Diazepam_Klotz1976_reference
  parameter Real Cl_ref = 9.52e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.329 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Diazepam.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>diazepam</td></tr><tr><td>ATC code:</td><td>N05BA01</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Klotz U et al. 1976</td></tr><tr><td>population:</td><td>man, dog, rabbit, guinea pig and rat</td></tr><tr><td>measured compound:</td><td>diazepam</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_diazepam/Diazepam_Klotz1976_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>T1/2(beta)</td><td>1.1</td><td>hours</td><td><small>t1/2z</small></td></tr><tr><td>rates of drug clearance</td><td>81.6</td><td>ml/min/kg</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>4.7</td><td>L/kg</td><td><small>V</small></td></tr><tr><td>Ka (h−1)</td><td>1.21</td><td>h−1</td><td><small>kabs</small></td></tr><tr><td>Tlag (h)</td><td>84.2</td><td>h</td><td><small>tlag</small></td></tr></table><h4>About diazepam</h4><p>Diazepam is a benzodiazepine sedative used for conditions such as anxiety, insomnia, epilepsy including status epilepticus, muscle spasticity, and alcohol withdrawal. It is widely used, appears on the WHO essential medicines list, and is also approved for veterinary use, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q210402\">Wikidata Q210402</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Diazepam\">Diazepam</a>.</p><h4>References</h4><ol><li><p>Klotz U et al. (1976). Pharmacokinetics and plasma binding of diazepam in man, dog, rabbit, guinea pig and rat. <i>The Journal of pharmacology and experimental therapeutics 199(1):67–73</i>. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/789856\">789856</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Klotz_1976: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Diazepam_Klotz1976_reference;
