within Pharmacolibrary.Drugs.R_RespiratorySystem.R05D_CoughSuppressantsExclCombinationsWithExpectorant.R05DA03_Hydrocodone;
model Hydrocodone_Melhem2013_reference
  parameter Real Cl_ref = 1.786111111111111e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.713 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Hydrocodone.M,
    adminMass = 1.5e-05,
    ka = 0.0006333333333333333,
    Tlag = 0.0,
    k12 = 3.5063113604488084e-07,
    k21 = 1.6339869281045755e-06
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>hydrocodone</td></tr><tr><td>ATC code:</td><td>R05DA03</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Melhem MR et al. 2013</td></tr><tr><td>measured compound:</td><td>hydrocodone</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_hydrocodone/Hydrocodone_Melhem2013_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL L/hr</td><td>64.3</td><td>L/hr</td><td><small>CL</small></td></tr><tr><td>Vc L</td><td>713</td><td>L</td><td><small>V1</small></td></tr><tr><td>KA1 1/hr</td><td>2.28</td><td>1/hr</td><td><small>kabs</small></td></tr><tr><td>Vp L</td><td>153</td><td>L</td><td><small>V2</small></td></tr><tr><td>Q L/hr</td><td>0.9</td><td>L/hr</td><td><small>Q</small></td></tr><tr><td>KTR 1/hr</td><td>8.5</td><td>1/hr</td><td><small>ktr</small></td></tr></table><h4>About hydrocodone</h4><p>Hydrocodone is an opioid used to treat pain and to suppress cough. It is an approved medicine, typically given in combination with non-opioid painkillers, and is not authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q411441\">Wikidata Q411441</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Hydrocodone\">Hydrocodone</a>.</p><h4>References</h4><ol><li><p>Melhem MR et al. (2013). Population pharmacokinetic analysis for hydrocodone following the administration of hydrocodone bitartrate extended-release capsules. <i>Clinical pharmacokinetics 52(10):907–917</i>. DOI:<a href=\"https://doi.org/10.1007/s40262-013-0081-6\">10.1007/s40262-013-0081-6</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/23719682\">23719682</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Melhem_2013: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 144000, Tolerance = 1e-9, Interval = 1));
end Hydrocodone_Melhem2013_reference;
