within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B01A_AntithromboticAgents.B01AD12_ProteinC;
model ProteinC_Li2025v2_percentage_relative_standard_error
  parameter Real Cl_ref = 8.611111111111111e-09 "Cl [m3/s]";
  parameter Real Vd_ref = 0.02 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>protein_c</td></tr><tr><td>ATC code:</td><td>B01AD12</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Li Z et al. 2025</td></tr><tr><td>population:</td><td>patients with severe congenital protein C deficiency</td></tr><tr><td>measured compound:</td><td>protein C</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_protein_c/ProteinC_Li2025v2_percentage_relative_standard_error\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL (L/h)</td><td>0.031</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>V (L)</td><td>20.0</td><td>L</td><td><small>V</small></td></tr></table><h4>About protein_c</h4><p>Protein C concentrate is used to treat purpura fulminans and protein C deficiency, acting as an antithrombotic agent. It is authorised in the European Union but appears to be a niche product, used only in these rare conditions.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q28852357\">Wikidata Q28852357</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.ProteinC\">ProteinC</a>.</p><h4>References</h4><ol><li><p>Li Z et al. (2025). Pharmacokinetic Evidence Supporting Subcutaneous Use of Protein C Concentrate in Patients with Protein C Deficiency. <i>TH open : companion journal to thrombosis and haemostasis 9:a27315372</i>. DOI:<a href=\"https://doi.org/10.1055/a-2731-5372\">10.1055/a-2731-5372</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/41383335\">41383335</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Li_2025_2: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 8467200, Tolerance = 1e-9, Interval = 1));
end ProteinC_Li2025v2_percentage_relative_standard_error;
