within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins.A10BJ06_Semaglutide;
model Semaglutide_Overgaard2019_estimate
  parameter Real Cl_ref = 9.666666666666666e-09 "Cl [m3/s]";
  parameter Real cov_body_weight_0 = 0 "body weight covariate";
  parameter Real cov_body_weight_1 = 0 "body weight covariate";
  parameter Real cov_injection_site_2 = 0 "injection site covariate";
  parameter Real Vd_ref = 0.00359 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 0.847,
    Cl = Cl_ref*(1 + (1.01)*cov_body_weight_0)*(1 + (0.923)*cov_body_weight_1)*(1 + (0.883)*cov_injection_site_2),
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Semaglutide.M,
    adminMass = 2.5e-07,
    ka = 7.027777777777778e-06,
    Tlag = 0.0,
    k12 = 2.3522129371711548e-05,
    k21 = 2.0596205962059627e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>semaglutide</td></tr><tr><td>ATC code:</td><td>A10BJ06</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Overgaard RV et al. 2019</td></tr><tr><td>population:</td><td>healthy subjects and those with type 2 diabetes</td></tr><tr><td>measured compound:</td><td>semaglutide</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_semaglutide/Semaglutide_Overgaard2019_estimate\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Absorption rate constant (ka), h−1</td><td>0.0253</td><td>h−1</td><td><small>kabs</small></td></tr><tr><td>Clearance (CL), L/h</td><td>0.0348</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Central volume (Vc), L</td><td>3.59</td><td>L</td><td><small>V1</small></td></tr><tr><td>Intercompartmental clearance (Q), L/h</td><td>0.304</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>Peripheral volume (Vp), L</td><td>4.10</td><td>L</td><td><small>V2</small></td></tr><tr><td>Absolute bioavailability (F)</td><td>0.847</td><td>F</td><td><small>Fab</small></td></tr><tr><td>body_weight_effect_on_cl_and_q</td><td>1.01</td><td></td><td><small>equation variable</small></td></tr><tr><td>body_weight_effect_on_vc_and_vp</td><td>0.923</td><td></td><td><small>equation variable</small></td></tr><tr><td>injection_site_effect_on_f</td><td>0.883</td><td></td><td><small>equation variable</small></td></tr></table><h4>About semaglutide</h4><p>Semaglutide is a GLP-1 analogue medicine used to treat type 2 diabetes and obesity or overweight. It is widely used and authorised in the European Union, with products also studied for fatty liver disease and related liver conditions.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q27261089\">Wikidata Q27261089</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Semaglutide\">Semaglutide</a>.</p><h4>References</h4><ol><li><p>Overgaard RV et al. (2019). Population Pharmacokinetics of Semaglutide for Type 2 Diabetes. <i>Diabetes therapy : research, treatment and education of diabetes and related disorders 10(2):649–662</i>. DOI:<a href=\"https://doi.org/10.1007/s13300-019-0581-y\">10.1007/s13300-019-0581-y</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30788808\">30788808</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Overgaard_2019: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 1728000, Tolerance = 1e-9, Interval = 1));
end Semaglutide_Overgaard2019_estimate;
