within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins.A10BJ06_Semaglutide;
model Semaglutide_Carlsson2018_base
  parameter Real Cl_ref = 1.3333333333333334e-08 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0125 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Semaglutide.M,
    adminMass = 2.5e-07,
    ka = 7.944444444444445e-06,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>semaglutide</td></tr><tr><td>ATC code:</td><td>A10BJ06</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Carlsson Petri KC et al. 2018</td></tr><tr><td>population:</td><td>adults with type 2 diabetes</td></tr><tr><td>measured compound:</td><td>semaglutide</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_semaglutide/Semaglutide_Carlsson2018_base\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>ka (h-1)</td><td>0.0286</td><td>h-1</td><td><small>kabs</small></td></tr><tr><td>CL/F (L/h)</td><td>0.0480</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>V/F (L)</td><td>12.5</td><td>L</td><td><small>V/F</small></td></tr></table><h4>About semaglutide</h4><p>Semaglutide is a GLP-1 analogue medicine used to treat type 2 diabetes and obesity or overweight. It is widely used and authorised in the European Union, with products also studied for fatty liver disease and related liver conditions.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q27261089\">Wikidata Q27261089</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Semaglutide\">Semaglutide</a>.</p><h4>References</h4><ol><li><p>Carlsson Petri KC et al. (2018). Semaglutide s.c. Once-Weekly in Type 2 Diabetes: A Population Pharmacokinetic Analysis. <i>Diabetes therapy : research, treatment and education of diabetes and related disorders 9(4):1533–1547</i>. DOI:<a href=\"https://doi.org/10.1007/s13300-018-0458-5\">10.1007/s13300-018-0458-5</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29907893\">29907893</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Carlsson_2018: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 3628800, Tolerance = 1e-9, Interval = 1));
end Semaglutide_Carlsson2018_base;
