within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01D_CytotoxicAntibioticsAndRelatedSubstances.L01DB01_Doxorubicin;
model Doxorubicin_Mohmaed2024_reference
  parameter Real Cl_ref = 1.2277777777777778e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0116 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Doxorubicin.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>doxorubicin</td></tr><tr><td>ATC code:</td><td>L01DB01</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Mohmaed Ali MI et al. 2024</td></tr><tr><td>population:</td><td>patients across all age groups</td></tr><tr><td>measured compound:</td><td>doxorubicin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_doxorubicin/Doxorubicin_Mohmaed2024_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL (L/h)</td><td>44.2</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>V1 (L)</td><td>11.6</td><td>L</td><td><small>V1</small></td></tr><tr><td>Q2 (L/h)</td><td>8.9</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>Q3 (L/h)</td><td>43.9</td><td>L/h</td><td><small>Q3</small></td></tr><tr><td>V3 (L)</td><td>898</td><td>L</td><td><small>V3</small></td></tr><tr><td>tlI2, min</td><td>2.3</td><td>min</td><td><small>tlag</small></td></tr></table><h4>About doxorubicin</h4><p>Doxorubicin is a chemotherapy drug used to treat many cancers, including breast and ovarian cancer, various lymphomas, and several leukemias. It is widely used and appears on the WHO essential medicines list; several doxorubicin products are authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q18936\">Wikidata Q18936</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Doxorubicin\">Doxorubicin</a>.</p><h4>References</h4><ol><li><p>Mohmaed Ali MI et al. (2024). A Population Pharmacokinetic Study to Evaluate Doxorubicin Exposure Across All Age Groups. <i>Clinical pharmacokinetics 63(12):1711–1722</i>. DOI:<a href=\"https://doi.org/10.1007/s40262-024-01445-5\">10.1007/s40262-024-01445-5</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39549227\">39549227</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Mohmaed_2024: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Doxorubicin_Mohmaed2024_reference;
