within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01D_CytotoxicAntibioticsAndRelatedSubstances.L01DB01_Doxorubicin;
model Doxorubicin_Mody2023_reference
  parameter Real Cl_ref = 1.4805555555555555e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0177 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Doxorubicin.M,
    adminMass = 1e-05,
    k12 = 0.000921217827997489,
    k21 = 8.910139647844566e-06
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>doxorubicin</td></tr><tr><td>ATC code:</td><td>L01DB01</td></tr><tr><td>model:</td><td>two compartments, IV dosing <small>(PK_2C)</small></td></tr><tr><td>source:</td><td>Mody H et al. 2023</td></tr><tr><td>population:</td><td>adults</td></tr><tr><td>measured compound:</td><td>doxorubicin</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL (L/h/1.8m2)</td><td>53.3</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>V (L/1.8m2)</td><td>17.7</td><td>L</td><td><small>V</small></td></tr><tr><td>Q2 (L/h/1.8m2)</td><td>58.7</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>V2 (L/1.8m2)</td><td>1830</td><td>L</td><td><small>V2</small></td></tr><tr><td>Q3 (L/h/1.8m2)</td><td>21.8</td><td>L/h</td><td><small>Q3</small></td></tr><tr><td>V3 (L/1.8m2)</td><td>71.6</td><td>L</td><td><small>V3</small></td></tr><tr><td>kel (h−1)</td><td>1</td><td>h−1</td><td><small>kel</small></td></tr><tr><td>k12 (h−1)</td><td>1</td><td>h−1</td><td><small>k12</small></td></tr><tr><td>k21 (h−1)</td><td>1</td><td>h−1</td><td><small>k21</small></td></tr><tr><td>tlI2, min</td><td>2.3</td><td>min</td><td><small>tlag</small></td></tr></table><h4>About doxorubicin</h4><p>Doxorubicin is a chemotherapy drug used to treat many cancers, including breast and ovarian cancer, various lymphomas, and several leukemias. It is widely used and appears on the WHO essential medicines list; several doxorubicin products are authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q18936\">Wikidata Q18936</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Doxorubicin\">Doxorubicin</a>.</p><h4>References</h4><ol><li><p>Mody H et al. (2023). In vitro to clinical translational pharmacokinetic/pharmacodynamic modeling of doxorubicin (DOX) and dexrazoxane (DEX) interactions: Safety assessment and optimization. <i>Scientific reports 13(1):3100</i>. DOI:<a href=\"https://doi.org/10.1038/s41598-023-29964-4\">10.1038/s41598-023-29964-4</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36813809\">36813809</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Mody_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Doxorubicin_Mody2023_reference;
