within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01B_AntiarrhythmicsClassIAndIii.C01BD01_Amiodarone;
model Amiodarone_Gaete1995_reference
  parameter Real Cl_ref = 4.958333333333334e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.20930000000000004 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 68.6,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Amiodarone.M,
    adminMass = 0.0002,
    ka = 0.00022777777777777775,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>amiodarone</td></tr><tr><td>ATC code:</td><td>C01BD01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Gaete LE et al. 1995</td></tr><tr><td>population:</td><td>healthy adults</td></tr><tr><td>measured compound:</td><td>amiodarone</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_amiodarone/Amiodarone_Gaete1995_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Cmax</td><td>1.17</td><td>mg/ml</td><td><small>Cmax</small></td></tr><tr><td>tmax</td><td>3.25</td><td>h</td><td><small>tmax</small></td></tr><tr><td>Absolute bioavailability</td><td>68.6</td><td>%</td><td><small>Fab</small></td></tr><tr><td>half life</td><td>7.53</td><td>h</td><td><small>t1/2z</small></td></tr><tr><td>total body clearance</td><td>4.25</td><td>ml/kg/min</td><td><small>CL</small></td></tr><tr><td>distribution volume</td><td>2.99</td><td>l/kg</td><td><small>V</small></td></tr><tr><td>K a (h−1)</td><td>0.82</td><td>h−1</td><td><small>kabs</small></td></tr></table><h4>About amiodarone</h4><p>Amiodarone is an antiarrhythmic medicine used to treat and prevent various types of irregular heartbeat, including ventricular tachycardia, atrial fibrillation, and other arrhythmias. It is widely used, is included on the WHO list of essential medicines, and is an approved drug.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q410061\">Wikidata Q410061</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Amiodarone\">Amiodarone</a>.</p><h4>References</h4><ol><li><p>Gaete LE et al. (1995). [Amiodarone absorption and elimination after oral and intravenous administration in healthy individuals]. <i>Revista medica de Chile 123(6):713–719</i>. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/8525224\">8525224</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Gaete_1995: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 151200, Tolerance = 1e-9, Interval = 1));
end Amiodarone_Gaete1995_reference;
