within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01B_AntiarrhythmicsClassIAndIii.C01BD02_BretyliumTosilate;
model Bretylium_Kamath1981_reference
  parameter Real Cl_ref = 3.752777777777778e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 1.05 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Bretylium.M,
    adminMass = 0.0001,
    ka = 0.00014916666666666667,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>bretylium</td></tr><tr><td>ATC code:</td><td>C01BD02</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Kamath BL et al. 1981</td></tr><tr><td>population:</td><td>rats</td></tr><tr><td>measured compound:</td><td>bretylium</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_bretylium/Bretylium_Kamath1981_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>apparent volume of distribution</td><td>15</td><td>liters/kg</td><td><small>V/F</small></td></tr><tr><td>beta half-life</td><td>5.5</td><td>hr</td><td><small>t1/2β</small></td></tr><tr><td>apparent volume of the central compartment</td><td>1</td><td>liter/kg</td><td><small>V1/F</small></td></tr><tr><td>plasma clearance</td><td>1.93</td><td>liters/hr/kg</td><td><small>CL</small></td></tr><tr><td>renal clearance</td><td>1.27</td><td>liters/hr/kg</td><td><small>CLR</small></td></tr><tr><td>excretion rate constants</td><td>1.24</td><td>hr-1</td><td><small>kexcr</small></td></tr><tr><td>population mean absorption rate constant</td><td>0.537</td><td>h−1</td><td><small>kabs</small></td></tr></table><h4>About bretylium</h4><p>Bretylium is a class III antiarrhythmic agent used to treat ventricular fibrillation and heart conduction disease. It is an approved drug, though it is not authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q420026\">Wikidata Q420026</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Bretylium\">Bretylium</a>.</p><h4>References</h4><ol><li><p>Kamath BL et al. (1981). Pharmacokinetics of [14C]bretylium tosylate in rats. <i>Journal of pharmaceutical sciences 70(6):667–669</i>. DOI:<a href=\"https://doi.org/10.1002/jps.2600700623\">10.1002/jps.2600700623</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/7252812\">7252812</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Kamath_1981: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 122400, Tolerance = 1e-9, Interval = 1));
end Bretylium_Kamath1981_reference;
