within Pharmacolibrary.Drugs.C_CardiovascularSystem.C08C_SelectiveCalciumChannelBlockersWithMainlyVascula.C08CA01_Amlodipine;
model Amlodipine_Karalis2023_reference
  parameter Real Cl_ref = 6.166666666666666e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0013 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 5e-06,
    ka = 0.00023616666666666667,
    Tlag = 0.0,
    k21 = 4.8325342465753424e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>amlodipine</td></tr><tr><td>ATC code:</td><td>C08CA01</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Karalis VD 2023</td></tr><tr><td>population:</td><td>virtual subjects</td></tr><tr><td>measured compound:</td><td>hydrochlorothiazide, donepezil, and amlodipine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_amlodipine/Amlodipine_Karalis2023_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Tlag (min)</td><td>24.24</td><td>min</td><td><small>tlag</small></td></tr><tr><td>Ka (min−1)</td><td>0.01417</td><td>min−1</td><td><small>kabs</small></td></tr><tr><td>Cl/F (mL/min)</td><td>370</td><td>mL/min</td><td><small>CL/F</small></td></tr><tr><td>Q/F (mL/min)</td><td>423.33</td><td>mL/min</td><td><small>Q/F</small></td></tr><tr><td>V1/F (mL)</td><td>1300</td><td>mL</td><td><small>V1/F</small></td></tr><tr><td>V2/F (mL)</td><td>146000</td><td>mL</td><td><small>V2/F</small></td></tr></table><h4>About amlodipine</h4><p>Amlodipine is a calcium channel blocker used to treat high blood pressure and angina. It is widely used worldwide and is included on the WHO list of essential medicines, available alone and in many fixed-dose combination products.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q411347\">Wikidata Q411347</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Amlodipine\">Amlodipine</a>.</p><h4>References</h4><ol><li><p>Karalis VD (2023). An In Silico Approach toward the Appropriate Absorption Rate Metric in Bioequivalence. <i>Pharmaceuticals (Basel, Switzerland) 16(5):725</i>. DOI:<a href=\"https://doi.org/10.3390/ph16050725\">10.3390/ph16050725</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37242508\">37242508</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Karalis_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Amlodipine_Karalis2023_reference;
