within Pharmacolibrary.Drugs.C_CardiovascularSystem.C08C_SelectiveCalciumChannelBlockersWithMainlyVascula.C08CA01_Amlodipine;
model Amlodipine_Flynn2006_reference
  parameter Real Cl_ref = 6.583333333333333e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 1.7570000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Amlodipine.M,
    adminMass = 5e-06,
    ka = 0.00040555555555555554,
    Tlag = 3096.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>amlodipine</td></tr><tr><td>ATC code:</td><td>C08CA01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Flynn JT et al. 2006</td></tr><tr><td>population:</td><td>hypertensive children and adolescents</td></tr><tr><td>measured compound:</td><td>amlodipine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_amlodipine/Amlodipine_Flynn2006_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>predicted apparent clearances (CL/F)</td><td>23.7</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>apparent volume of distribution (V/F)</td><td>25.1</td><td>L/kg</td><td><small>V/F</small></td></tr><tr><td>Ka</td><td>1.46</td><td>/h</td><td><small>kabs</small></td></tr><tr><td>ALAG (h)</td><td>0.87</td><td>h</td><td><small>tlag</small></td></tr></table><h4>About amlodipine</h4><p>Amlodipine is a calcium channel blocker used to treat high blood pressure and angina. It is widely used worldwide and is included on the WHO list of essential medicines, available alone and in many fixed-dose combination products.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q411347\">Wikidata Q411347</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Amlodipine\">Amlodipine</a>.</p><h4>References</h4><ol><li><p>Flynn JT et al. (2006). Population pharmacokinetics of amlodipine in hypertensive children and adolescents. <i>Journal of clinical pharmacology 46(8):905–916</i>. DOI:<a href=\"https://doi.org/10.1177/0091270006289844\">10.1177/0091270006289844</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16855075\">16855075</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Flynn_2006: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 950400, Tolerance = 1e-9, Interval = 1));
end Amlodipine_Flynn2006_reference;
