within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B05X_IVSolutionAdditives.B05XB01_ArginineHydrochloride;
model ArginineHydrochloride_Wang2018_reference
  parameter Real Cl_ref = 1.225e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.004326 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Arginine.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>arginine_hydrochloride</td></tr><tr><td>ATC code:</td><td>B05XB01</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Wang J et al. 2018</td></tr><tr><td>population:</td><td>healthy Chinese volunteers</td></tr><tr><td>measured compound:</td><td>arginine</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_arginine_hydrochloride/ArginineHydrochloride_Wang2018_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL</td><td>44.1</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Vd</td><td>61.8</td><td>mL kg−1</td><td><small>V</small></td></tr></table><h4>About arginine_hydrochloride</h4><p>Arginine hydrochloride is an amino acid used as an additive to intravenous solutions, and has also been studied for other uses. It is an approved medicine and is also sold as a nutritional supplement.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q173670\">Wikidata Q173670</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Arginine\">Arginine</a>.</p><h4>References</h4><ol><li><p>Wang J et al. (2018). Population pharmacokinetics of arginine glutamate in healthy Chinese volunteers. <i>Xenobiotica; the fate of foreign compounds in biological systems 48(8):809–817</i>. DOI:<a href=\"https://doi.org/10.1080/00498254.2017.1370745\">10.1080/00498254.2017.1370745</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28925806\">28925806</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Wang_2018: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end ArginineHydrochloride_Wang2018_reference;
