within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B02B_VitaminKAndOtherHemostatics.B02BD10_VonWillebrandFactor;
model VonWillebrandFactor_Bauer2023_pdvwf_fviii_model
  parameter Real Cl_ref = 1.15e-07 "Cl [m3/s]";
  parameter Real cov_wt_0 = 0 "wt covariate";
  parameter Real Vd_ref = 0.0047 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref*(1 + (0.75)*cov_wt_0),
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 0.0001,
    ka = 0.0001388888888888889,
    Tlag = 0.0,
    k21 = 6.433506044905008e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>von_willebrand_factor</td></tr><tr><td>ATC code:</td><td>B02BD10</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Bauer A et al. 2023</td></tr><tr><td>population:</td><td>patients with von Willebrand disease</td></tr><tr><td>measured compound:</td><td>von_willebrand_factor</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_von_willebrand_factor/VonWillebrandFactor_Bauer2023_pdvwf_fviii_model\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL, dL/h</td><td>4.14</td><td>dL/h</td><td><small>CL</small></td></tr><tr><td>Vc, dL</td><td>47.0</td><td>dL</td><td><small>V1</small></td></tr><tr><td>Q, dL/h</td><td>4.47</td><td>dL/h</td><td><small>Q</small></td></tr><tr><td>Vp, dL</td><td>19.3</td><td>dL</td><td><small>V2</small></td></tr><tr><td>wt_effect_on_cl_and_q</td><td>0.750</td><td></td><td><small>equation variable</small></td></tr><tr><td>theta_q61_wt</td><td>1.00</td><td></td><td><small>equation variable</small></td></tr><tr><td>Absorption rate constant (kapop) [h−1]</td><td>0.5</td><td>h−1</td><td><small>kabs</small></td></tr></table><h4>About von_willebrand_factor</h4><p>Von Willebrand factor is a blood protein used as a medicine to treat bleeding problems, particularly von Willebrand disease. It is an approved treatment, given as a blood coagulation factor product, though its use remains limited to specialised care.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q412310\">Wikidata Q412310</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.VonWillebrandFactor\">VonWillebrandFactor</a>.</p><h4>References</h4><ol><li><p>Bauer A et al. (2023). Pharmacokinetic-Pharmacodynamic Comparison of Recombinant and Plasma-Derived von Willebrand Factor in Patients with von Willebrand Disease Type 3. <i>Journal of blood medicine 14:399–411</i>. DOI:<a href=\"https://doi.org/10.2147/JBM.S395845\">10.2147/JBM.S395845</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37332615\">37332615</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Bauer_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end VonWillebrandFactor_Bauer2023_pdvwf_fviii_model;
