within Pharmacolibrary.Drugs.N_NervousSystem.N03A_Antiepileptics.N03AX24_Cannabidiol;
model Cannabidiol_Snchez2023_reference
  parameter Real Cl_ref = 2.8388888888888886e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 2.5200000000000005 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Cannabidiol.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>cannabidiol</td></tr><tr><td>ATC code:</td><td>N03AX24</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Sánchez de Medina A et al. 2023</td></tr><tr><td>population:</td><td>healthy horses</td></tr><tr><td>measured compound:</td><td>cannabidiol</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_cannabidiol/Cannabidiol_Snchez2023_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>volume of distribution</td><td>36</td><td>L/kg</td><td><small>V</small></td></tr><tr><td>systemic clearance</td><td>1.46</td><td>L/h/kg</td><td><small>CL</small></td></tr><tr><td>Oral bioavailability</td><td>14</td><td>%</td><td><small>Fab</small></td></tr></table><h4>About cannabidiol</h4><p>Cannabidiol is an antiepileptic medicine used to treat certain epilepsy syndromes, including Lennox–Gastaut syndrome and myoclonic epilepsies. It is an approved medicine with an authorised product in the European Union, and is also being studied for other investigational uses.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q422917\">Wikidata Q422917</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Cannabidiol\">Cannabidiol</a>.</p><h4>References</h4><ol><li><p>Sánchez de Medina A et al. (2023). Pharmacokinetics and oral bioavailability of cannabidiol in horses after intravenous and oral administration with oil and micellar formulations. <i>Equine veterinary journal 55(6):1094–1103</i>. DOI:<a href=\"https://doi.org/10.1111/evj.13923\">10.1111/evj.13923</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36624043\">36624043</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Sánchez_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 345600, Tolerance = 1e-9, Interval = 1));
end Cannabidiol_Snchez2023_reference;
