within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01A_Tetracyclines.J01AA08_Minocycline;
model Minocycline_Tynan2016_reference
  parameter Real Cl_ref = 3.383333333333333e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.105 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Minocycline.M,
    adminMass = 0.0002
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>minocycline</td></tr><tr><td>ATC code:</td><td>J01AA08</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Tynan BE et al. 2016</td></tr><tr><td>population:</td><td>domestic cats</td></tr><tr><td>measured compound:</td><td>minocycline</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_minocycline/Minocycline_Tynan2016_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Oral bioavailability</td><td>62</td><td>%</td><td><small>Fab</small></td></tr><tr><td>Plasma protein binding</td><td>60</td><td>%</td><td><small>fu</small></td></tr><tr><td>elimination half-life (t(½))</td><td>6.7</td><td>h</td><td><small>t1/2z</small></td></tr><tr><td>apparent volume of distribution at steady-state</td><td>1.5</td><td>l/kg</td><td><small>Vss</small></td></tr><tr><td>systemic clearance</td><td>2.9</td><td>ml/kg/min</td><td><small>CL</small></td></tr><tr><td>peak concentration (Cmax)</td><td>4.77</td><td>µg/ml</td><td><small>Cmax</small></td></tr></table><h4>About minocycline</h4><p>Minocycline is a tetracycline antibiotic used to treat bacterial infections such as acne, rosacea, meningitis, anthrax, brucellosis, and gum disease. It is an approved medicine, used both systemically for infections and topically for acne, as well as in oral preparations for dental infections.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q415336\">Wikidata Q415336</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Minocycline\">Minocycline</a>.</p><h4>References</h4><ol><li><p>Tynan BE et al. (2016). Pharmacokinetics of minocycline in domestic cats. <i>Journal of feline medicine and surgery 18(4):257–263</i>. DOI:<a href=\"https://doi.org/10.1177/1098612X15579114\">10.1177/1098612X15579114</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25851119\">25851119</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Tynan_2016: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 122400, Tolerance = 1e-9, Interval = 1));
end Minocycline_Tynan2016_reference;
