within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01A_Tetracyclines.J01AA08_Minocycline;
model Minocycline_Pardos2024_reference
  parameter Real Cl_ref = 2.058888888888889e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.014155 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Minocycline.M,
    adminMass = 0.0002
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>minocycline</td></tr><tr><td>ATC code:</td><td>J01AA08</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Pardos SL et al. 2024</td></tr><tr><td>population:</td><td>patients with complicated skin and soft tissue infections caused by MRSA</td></tr><tr><td>measured compound:</td><td>minocycline</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_minocycline/Minocycline_Pardos2024_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>clearance</td><td>7.412</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>14.155</td><td>L</td><td><small>V</small></td></tr></table><h4>About minocycline</h4><p>Minocycline is a tetracycline antibiotic used to treat bacterial infections such as acne, rosacea, meningitis, anthrax, brucellosis, and gum disease. It is an approved medicine, used both systemically for infections and topically for acne, as well as in oral preparations for dental infections.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q415336\">Wikidata Q415336</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Minocycline\">Minocycline</a>.</p><h4>References</h4><ol><li><p>Pardos SL et al. (2024). Population pharmacokinetics/pharmacodynamics of minocycline plus rifampicin in patients with complicated skin and skin structure infections caused by MRSA. <i>The Journal of antimicrobial chemotherapy 79(12):3303–3312</i>. DOI:<a href=\"https://doi.org/10.1093/jac/dkae363\">10.1093/jac/dkae363</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39412246\">39412246</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Pardos_2024: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Minocycline_Pardos2024_reference;
