within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01E_OtherCardiacPreparations.C01EB16_Ibuprofen;
model Ibuprofen "Ibuprofen — default model: Ibuprofen_Trocniz2000_reference"
  extends Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero.M01AE01_Ibuprofen.Ibuprofen_Trocniz2000_reference;
  annotation (Documentation(info = "<html><body><p>ibuprofen under ATC C01EB16: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero.M01AE01_Ibuprofen\">M01AE01_Ibuprofen</a> (ATC M01AE01); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Ibuprofen;
