within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01B_AntiarrhythmicsClassIAndIii.C01BB02_Mexiletine;
model Mexiletine_Vozeh1982_reference
  parameter Real Cl_ref = 7.38888888888889e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.371 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Mexiletine.M,
    adminMass = 0.0008,
    ka = 0.0008611111111111111,
    Tlag = 1080.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>mexiletine</td></tr><tr><td>ATC code:</td><td>C01BB02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Vozeh S et al. 1982</td></tr><tr><td>population:</td><td>patients treated for arrhythmias</td></tr><tr><td>measured compound:</td><td>mexiletine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_mexiletine/Mexiletine_Vozeh1982_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>oral total body clearance (Cl)</td><td>0.38</td><td>l/h/kg</td><td><small>CL</small></td></tr><tr><td>apparent volume of distribution (Vd)</td><td>5.3</td><td>l/kg</td><td><small>V/F</small></td></tr><tr><td>absorption rate constant</td><td>3.1</td><td>h-1</td><td><small>kabs</small></td></tr><tr><td>absorption time-lag</td><td>0.3</td><td>h</td><td><small>tlag</small></td></tr></table><h4>About mexiletine</h4><p>Mexiletine is an antiarrhythmic (class Ib) drug used for heart rhythm problems such as ventricular fibrillation, and also for diabetic nerve pain and myotonic disorders. It remains in use, with one product authorised in the European Union, where it is indicated for myotonic disorders.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q420377\">Wikidata Q420377</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Mexiletine\">Mexiletine</a>.</p><h4>References</h4><ol><li><p>Vozeh S et al. (1982). Population pharmacokinetic parameters in patients treated with oral mexiletine. <i>European journal of clinical pharmacology 23(5):445–451</i>. DOI:<a href=\"https://doi.org/10.1007/BF00605996\">10.1007/BF00605996</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/7151850\">7151850</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Vozeh_1982: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 259200, Tolerance = 1e-9, Interval = 1));
end Mexiletine_Vozeh1982_reference;
