within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M02A_TopicalProductsForJointAndMuscularPain.M02AX02_Tolazoline;
model Tolazoline "Tolazoline — default model: Tolazoline"
  extends Pharmacolibrary.Drugs.C_CardiovascularSystem.C04A_PeripheralVasodilators.C04AB02_Tolazoline.Tolazoline;
  annotation (Documentation(info = "<html><body><p>tolazoline under ATC M02AX02: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.C_CardiovascularSystem.C04A_PeripheralVasodilators.C04AB02_Tolazoline\">C04AB02_Tolazoline</a> (ATC C04AB02); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Tolazoline;
