within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A06A_DrugsForConstipation.A06AD04_MagnesiumSulfate;
model MagnesiumSulfate_da2020_reference
  parameter Real Cl_ref = 3.833333333333333e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.013300000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.MagnesiumSulfate.M,
    adminMass = 0.001
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>magnesium_sulfate</td></tr><tr><td>ATC code:</td><td>A06AD04</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>da Costa TX et al. 2020</td></tr><tr><td>population:</td><td>pregnant women with preeclampsia</td></tr><tr><td>measured compound:</td><td>magnesium_sulfate</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>V_pop</td><td>13.3</td><td>L</td><td><small>V</small></td></tr><tr><td>CL_pop</td><td>1.38</td><td>L/h</td><td><small>CL</small></td></tr></table><h4>About magnesium_sulfate</h4><p>Magnesium sulfate is used as a laxative for constipation, as a magnesium supplement, and in electrolyte solutions; it also acts as an anticonvulsant, antiarrhythmic, analgesic, anesthetic, and tocolytic agent. It is widely used in human medicine and is also an approved veterinary drug, with some investigational uses.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q288266\">Wikidata Q288266</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.MagnesiumSulfate\">MagnesiumSulfate</a>.</p><h4>References</h4><ol><li><p>da Costa TX et al. (2020). Population Pharmacokinetics of Magnesium Sulfate in Preeclampsia and Associated Factors. <i>Drugs in R&amp;D 20(3):257–266</i>. DOI:<a href=\"https://doi.org/10.1007/s40268-020-00315-2\">10.1007/s40268-020-00315-2</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32642964\">32642964</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from da_2020: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 122400, Tolerance = 1e-9, Interval = 1));
end MagnesiumSulfate_da2020_reference;
