within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01B_Antimetabolites.L01BA04_Pemetrexed;
model Pemetrexed_Boosman2023_reference
  parameter Real Cl_ref = 6.444444444444444e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.004070000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Pemetrexed.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>pemetrexed</td></tr><tr><td>ATC code:</td><td>L01BA04</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Boosman RJ et al. 2023</td></tr><tr><td>population:</td><td>patients with lung cancer and mesothelioma</td></tr><tr><td>measured compound:</td><td>pemetrexed</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_pemetrexed/Pemetrexed_Boosman2023_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Cl (L/h)</td><td>2.32</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Volume of distribution Central compartment (L)</td><td>4.07</td><td>L</td><td><small>V</small></td></tr><tr><td>Q (L/h)</td><td>4.53</td><td>L/h</td><td><small>Q</small></td></tr></table><h4>About pemetrexed</h4><p>Pemetrexed is an anticancer drug used to treat non-small-cell lung cancer and mesothelioma. It is an approved antifolate chemotherapy, with several products authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q415220\">Wikidata Q415220</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Pemetrexed\">Pemetrexed</a>.</p><h4>References</h4><ol><li><p>Boosman RJ et al. (2023). Prediction of the pharmacokinetics of pemetrexed with a low test dose: A proof-of-concept study. <i>British journal of clinical pharmacology 89(2):699–704</i>. DOI:<a href=\"https://doi.org/10.1111/bcp.15520\">10.1111/bcp.15520</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36053283\">36053283</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Boosman_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Pemetrexed_Boosman2023_reference;
