within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01B_Antimetabolites.L01BA04_Pemetrexed;
model Pemetrexed_Cao2022_reference
  parameter Real Cl_ref = 2.3027777777777774e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.018940000000000002 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Pemetrexed.M,
    adminMass = 1e-05,
    k12 = 1.466619734835152e-06,
    k21 = 5.4253472222222224e-06
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>pemetrexed</td></tr><tr><td>ATC code:</td><td>L01BA04</td></tr><tr><td>model:</td><td>two compartments, IV dosing <small>(PK_2C)</small></td></tr><tr><td>source:</td><td>Cao P et al. 2022</td></tr><tr><td>population:</td><td>Chinese primary advanced non-small cell lung carcinoma patients</td></tr><tr><td>measured compound:</td><td>pemetrexed</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_pemetrexed/Pemetrexed_Cao2022_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>V1 (L)</td><td>18.94</td><td>L</td><td><small>V1</small></td></tr><tr><td>V2 (L)</td><td>5.12</td><td>L</td><td><small>V2</small></td></tr><tr><td>CL (L·h−1)</td><td>8.29</td><td>L·h−1</td><td><small>CL</small></td></tr><tr><td>Q (L·h−1)</td><td>0.10</td><td>L·h−1</td><td><small>Q</small></td></tr></table><h4>About pemetrexed</h4><p>Pemetrexed is an anticancer drug used to treat non-small-cell lung cancer and mesothelioma. It is an approved antifolate chemotherapy, with several products authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q415220\">Wikidata Q415220</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Pemetrexed\">Pemetrexed</a>.</p><h4>References</h4><ol><li><p>Cao P et al. (2022). Population pharmacokinetic study of pemetrexed in chinese primary advanced non-small cell lung carcinoma patients. <i>Frontiers in pharmacology 13:954242</i>. DOI:<a href=\"https://doi.org/10.3389/fphar.2022.954242\">10.3389/fphar.2022.954242</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36105185\">36105185</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Cao_2022: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Pemetrexed_Cao2022_reference;
