within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals.J05AG03_Efavirenz;
model Efavirenz_Chala2023_reference
  parameter Real Cl_ref = 1.1944444444444443e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.1238 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Efavirenz.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>efavirenz</td></tr><tr><td>ATC code:</td><td>J05AG03</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Chala A et al. 2023</td></tr><tr><td>population:</td><td>HIV-1-infected children in Ethiopia</td></tr><tr><td>measured compound:</td><td>efavirenz</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_efavirenz/Efavirenz_Chala2023_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL (L/h)</td><td>4.3</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Vc (L)</td><td>123.8</td><td>L</td><td><small>V1</small></td></tr></table><h4>About efavirenz</h4><p>Efavirenz is a non-nucleoside reverse transcriptase inhibitor used to treat HIV infection and HIV/AIDS. It is widely used, appears on the WHO essential medicines list, and is authorised in the European Union, both alone and in combination antiviral products.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q422645\">Wikidata Q422645</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Efavirenz\">Efavirenz</a>.</p><h4>References</h4><ol><li><p>Chala A et al. (2023). Genetic and non-genetic factors influencing efavirenz population pharmacokinetics among human immunodeficiency virus-1-infected children in Ethiopia. <i>CPT: pharmacometrics &amp; systems pharmacology 12(6):783–794</i>. DOI:<a href=\"https://doi.org/10.1002/psp4.12951\">10.1002/psp4.12951</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36840416\">36840416</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Chala_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 432000, Tolerance = 1e-9, Interval = 1));
end Efavirenz_Chala2023_reference;
