within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero.M01AE01_Ibuprofen;
model Ibuprofen_Trocniz2000_reference
  parameter Real Cl_ref = 6.666666666666667e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0044 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Ibuprofen.M,
    adminMass = 0.0004,
    ka = 0.008611111111111111,
    Tlag = 57600.0,
    k12 = 0.0029040404040404037,
    k21 = 0.00019658119658119656
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>ibuprofen</td></tr><tr><td>ATC code:</td><td>M01AE01</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Trocóniz IF et al. 2000</td></tr><tr><td>population:</td><td>healthy adults</td></tr><tr><td>measured compound:</td><td>ibuprofen</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_ibuprofen/Ibuprofen_Trocniz2000_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>kₐ,susp (h⁻¹)</td><td>0.82</td><td>h⁻¹</td><td><small>kabs</small></td></tr><tr><td>tₗag (h)</td><td>1.33</td><td>h</td><td><small>tlag</small></td></tr><tr><td>F₁</td><td>0.63</td><td></td><td><small>Fab</small></td></tr><tr><td>V1 (L)ᵇ</td><td>4.4</td><td>L</td><td><small>V1</small></td></tr><tr><td>CL (L/h)ᵇ</td><td>4.05</td><td>L/h</td><td><small>CLb</small></td></tr><tr><td>CLd (L/h)ᵇ</td><td>2.09</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>V2 (L)ᵇ</td><td>6.62</td><td>L</td><td><small>V2</small></td></tr></table><h4>About ibuprofen</h4><p>Ibuprofen is a non-steroidal anti-inflammatory medicine used to relieve pain, inflammation and fever, and for conditions such as osteoarthritis, rheumatoid arthritis, migraine and gout. It is widely used and available over the counter in the UK, and is also authorised in the European Union for pain and for treating a heart vessel problem in premature babies.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q186969\">Wikidata Q186969</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Ibuprofen\">Ibuprofen</a>.</p><h4>References</h4><ol><li><p>Trocóniz IF et al. (2000). Pharmacokinetic-Pharmacodynamic Modelling of the antipyretic effect of two oral formulations of ibuprofen. <i>Clinical pharmacokinetics 38(6):505–518</i>. DOI:<a href=\"https://doi.org/10.2165/00003088-200038060-00004\">10.2165/00003088-200038060-00004</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/10885587\">10885587</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Trocóniz_2000: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Ibuprofen_Trocniz2000_reference;
