within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero.M01AE01_Ibuprofen;
model Ibuprofen_DeGraves1993v2_reference
  parameter Real Cl_ref = 1.676111111111111e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.009800000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Ibuprofen.M,
    adminMass = 3e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>ibuprofen</td></tr><tr><td>ATC code:</td><td>M01AE01</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>DeGraves FJ et al. 1993</td></tr><tr><td>population:</td><td>lactating dairy cows</td></tr><tr><td>measured compound:</td><td>ibuprofen</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_ibuprofen/Ibuprofen_DeGraves1993v2_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Harmonic mean volume of distribution at steady state</td><td>0.14</td><td>L/kg</td><td><small>Vss</small></td></tr><tr><td>elimination half-life</td><td>1.55</td><td>hours</td><td><small>t1/2z</small></td></tr><tr><td>total clearance</td><td>86.2</td><td>ml/kg/h</td><td><small>CL</small></td></tr><tr><td>Harmonic mean oral bioavailability</td><td>99</td><td>%</td><td><small>Fab</small></td></tr></table><h4>About ibuprofen</h4><p>Ibuprofen is a non-steroidal anti-inflammatory medicine used to relieve pain, inflammation and fever, and for conditions such as osteoarthritis, rheumatoid arthritis, migraine and gout. It is widely used and available over the counter in the UK, and is also authorised in the European Union for pain and for treating a heart vessel problem in premature babies.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q186969\">Wikidata Q186969</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Ibuprofen\">Ibuprofen</a>.</p><h4>References</h4><ol><li><p>DeGraves FJ et al. (1993). Pharmacokinetics of ibuprofen in lactating dairy cows. <i>American journal of veterinary research 54(7):1133–1135</i>. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/8368610\">8368610</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from DeGraves_1993_2: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Ibuprofen_DeGraves1993v2_reference;
