within Pharmacolibrary.Drugs.D_Dermatologicals.D11A_OtherDermatologicalPreparations.D11AX05_MagnesiumSulfate;
model MagnesiumSulfate "MagnesiumSulfate — default model: MagnesiumSulfate"
  extends Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A06A_DrugsForConstipation.A06AD04_MagnesiumSulfate.MagnesiumSulfate;
  annotation (Documentation(info = "<html><body><p>magnesium sulfate under ATC D11AX05: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A06A_DrugsForConstipation.A06AD04_MagnesiumSulfate\">A06AD04_MagnesiumSulfate</a> (ATC A06AD04); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end MagnesiumSulfate;
