within Pharmacolibrary.Drugs.N_NervousSystem.N02A_Opioids.N02AB02_Pethidine;
model Pethidine_Chmelar1975_reference
  parameter Real Cl_ref = 1.7694444444444443e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.35000000000000003 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Pethidine.M,
    adminMass = 0.0004
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>pethidine</td></tr><tr><td>ATC code:</td><td>N02AB02</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Chmelar V et al. 1975</td></tr><tr><td>population:</td><td>rats</td></tr><tr><td>measured compound:</td><td>pethidine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_pethidine/Pethidine_Chmelar1975_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Clearance</td><td>0.637</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Vd threshold</td><td>5.0</td><td>L/kg</td><td><small>V</small></td></tr><tr><td>TLAG (min)</td><td>5.3</td><td>min</td><td><small>tlag</small></td></tr></table><h4>About pethidine</h4><p>Pethidine is an opioid painkiller used to treat moderate to severe pain. It is an approved medicine, though as a narcotic opioid its use is controlled and often limited to hospital settings.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q55434\">Wikidata Q55434</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Pethidine\">Pethidine</a>.</p><h4>References</h4><ol><li><p>Chmelar V et al. (1975). Sex differences in the fate of N-methyl-14C-pethidine in rats. <i>Materia medica Polona. Polish journal of medicine and pharmacy 7(4):276–281</i>. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/1214512\">1214512</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Chmelar_1975: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 7257600, Tolerance = 1e-9, Interval = 1));
end Pethidine_Chmelar1975_reference;
