within Pharmacolibrary.Drugs.N_NervousSystem.N02A_Opioids.N02AB02_Pethidine;
model Pethidine_Qiao1993_reference
  parameter Real Cl_ref = 0.00014583333333333335 "Cl [m3/s]";
  parameter Real Vd_ref = 0.19341 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 0.0004
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>pethidine</td></tr><tr><td>ATC code:</td><td>N02AB02</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Qiao GL et al. 1993</td></tr><tr><td>population:</td><td>adult goats</td></tr><tr><td>measured compound:</td><td>meperidine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_pethidine/Pethidine_Qiao1993_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>tmax</td><td>8.3</td><td>min</td><td><small>tmax</small></td></tr><tr><td>Vd</td><td>2.763</td><td>l/kg</td><td><small>V</small></td></tr><tr><td>Clb</td><td>0.125</td><td>l/kg/min</td><td><small>CLb</small></td></tr><tr><td>Ke</td><td>0.0563</td><td>min-1</td><td><small>kel</small></td></tr></table><h4>About pethidine</h4><p>Pethidine is an opioid painkiller used to treat moderate to severe pain. It is an approved medicine, though as a narcotic opioid its use is controlled and often limited to hospital settings.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q55434\">Wikidata Q55434</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Pethidine\">Pethidine</a>.</p><h4>References</h4><ol><li><p>Qiao GL et al. (1993). Pharmacokinetic-pharmacodynamic modelling of meperidine in goats (I): Pharmacokinetics. <i>Journal of veterinary pharmacology and therapeutics 16(4):426–437</i>. DOI:<a href=\"https://doi.org/10.1111/j.1365-2885.1993.tb00208.x\">10.1111/j.1365-2885.1993.tb00208.x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/8126759\">8126759</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Qiao_1993: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Pethidine_Qiao1993_reference;
