within Pharmacolibrary.Drugs.N_NervousSystem.N03A_Antiepileptics.N03AF01_Carbamazepine;
model Carbamazepine_Punyawudho2012_reference
  parameter Real Cl_ref = 9.972222222222222e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.10200000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Carbamazepine.M,
    adminMass = 0.001,
    ka = 5.472222222222223e-05,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>carbamazepine</td></tr><tr><td>ATC code:</td><td>N03AF01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Punyawudho B et al. 2012</td></tr><tr><td>population:</td><td>elderly patients with epilepsy</td></tr><tr><td>measured compound:</td><td>carbamazepine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_carbamazepine/Carbamazepine_Punyawudho2012_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F (L/hr)</td><td>3.59</td><td>L/hr</td><td><small>CL/F</small></td></tr><tr><td>V/F (L)</td><td>102</td><td>L</td><td><small>V/F</small></td></tr><tr><td>Ka (hr−1)</td><td>0.197</td><td>hr−1</td><td><small>kabs</small></td></tr></table><h4>About carbamazepine</h4><p>Carbamazepine is an anticonvulsant used for epilepsy and seizures, trigeminal neuralgia, and bipolar disorder, and has also been used for other mood and psychiatric conditions. It remains widely used and is included on the WHO essential medicines list, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q410412\">Wikidata Q410412</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Carbamazepine\">Carbamazepine</a>.</p><h4>References</h4><ol><li><p>Punyawudho B et al. (2012). Population pharmacokinetics of carbamazepine in elderly patients. <i>Therapeutic drug monitoring 34(2):176–181</i>. DOI:<a href=\"https://doi.org/10.1097/FTD.0b013e31824d6a4e\">10.1097/FTD.0b013e31824d6a4e</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/22406657\">22406657</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Punyawudho_2012: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 432000, Tolerance = 1e-9, Interval = 1));
end Carbamazepine_Punyawudho2012_reference;
