within Pharmacolibrary.Drugs.N_NervousSystem.N03A_Antiepileptics.N03AF01_Carbamazepine;
model Carbamazepine_Milovanovic2016_reference
  parameter Real Cl_ref = 5.972222222222223e-08 "Cl [m3/s]";
  parameter Real Vd_ref = 0.17450000000000002 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Carbamazepine.M,
    adminMass = 0.00026,
    ka = 0.0002425,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>carbamazepine</td></tr><tr><td>ATC code:</td><td>N03AF01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Milovanovic DD et al. 2016</td></tr><tr><td>population:</td><td>epileptic pediatric patients</td></tr><tr><td>measured compound:</td><td>carbamazepine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_carbamazepine/Carbamazepine_Milovanovic2016_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Clearance (L/h)</td><td>0.215</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>V</td><td>0.86</td><td>L/kg</td><td><small>V</small></td></tr><tr><td>ka</td><td>0.873</td><td>/h</td><td><small>kabs</small></td></tr></table><h4>About carbamazepine</h4><p>Carbamazepine is an anticonvulsant used for epilepsy and seizures, trigeminal neuralgia, and bipolar disorder, and has also been used for other mood and psychiatric conditions. It remains widely used and is included on the WHO essential medicines list, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q410412\">Wikidata Q410412</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Carbamazepine\">Carbamazepine</a>.</p><h4>References</h4><ol><li><p>Milovanovic DD et al. (2016). The influence of CYP2C8*3 on carbamazepine serum concentration in epileptic pediatric patients. <i>Balkan journal of medical genetics : BJMG 19(1):21–28</i>. DOI:<a href=\"https://doi.org/10.1515/bjmg-2016-0003\">10.1515/bjmg-2016-0003</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27785404\">27785404</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Milovanovic_2016: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 10281600, Tolerance = 1e-9, Interval = 1));
end Carbamazepine_Milovanovic2016_reference;
