within Pharmacolibrary.Drugs.N_NervousSystem.N03A_Antiepileptics.N03AF01_Carbamazepine;
model Carbamazepine_Yip2021_reference
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_General_Linear(
    nComp = 1, centralIdx = 1, F = 1,
    V = {0.17450000000000002},
    CLelim = {2.5250000000000004e-06},
    nEdge = 0,
    edge = fill(0,0,2),
    CLedge = fill(0.0, 0)
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>carbamazepine</td></tr><tr><td>ATC code:</td><td>N03AF01</td></tr><tr><td>model:</td><td>PK_General_Linear <small>(PK_General_Linear)</small></td></tr><tr><td>source:</td><td>Yip VLM et al. 2021</td></tr><tr><td>population:</td><td>healthy volunteers and epilepsy patients</td></tr><tr><td>measured compound:</td><td>carbamazepine</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>About carbamazepine</h4><p>Carbamazepine is an anticonvulsant used for epilepsy and seizures, trigeminal neuralgia, and bipolar disorder, and has also been used for other mood and psychiatric conditions. It remains widely used and is included on the WHO essential medicines list, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q410412\">Wikidata Q410412</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Carbamazepine\">Carbamazepine</a>.</p><h4>References</h4><ol><li><p>Yip VLM et al. (2021). Evaluation of clinical and genetic factors in the population pharmacokinetics of carbamazepine. <i>British journal of clinical pharmacology 87(6):2572–2588</i>. DOI:<a href=\"https://doi.org/10.1111/bcp.14667\">10.1111/bcp.14667</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33217013\">33217013</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Yip_2021: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Carbamazepine_Yip2021_reference;
