within Pharmacolibrary.Drugs.N_NervousSystem.N03A_Antiepileptics.N03AF01_Carbamazepine;
model Carbamazepine_Djordjevic2025_reference
  parameter Real Cl_ref = 4.861111111111111e-08 "Cl [m3/s]";
  parameter Real cov_cyp1a2_0 = 0 "cyp1a2 covariate";
  parameter Real cov_abcb1_1 = 0 "abcb1 covariate";
  parameter Real Vd_ref = 1.26 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref*(1 + (0.0176)*cov_cyp1a2_0)*(1 + (0.0332)*cov_abcb1_1),
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Carbamazepine.M,
    adminMass = 0.001,
    ka = 0.0002425,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>carbamazepine</td></tr><tr><td>ATC code:</td><td>N03AF01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Djordjevic N et al. 2025</td></tr><tr><td>population:</td><td>pediatric epileptic patients</td></tr><tr><td>measured compound:</td><td>carbamazepine</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_carbamazepine/Carbamazepine_Djordjevic2025_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F (L/h)</td><td>0.175</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>cyp1a2</td><td>0.0176</td><td></td><td><small>equation variable</small></td></tr><tr><td>abcb1</td><td>0.0332</td><td></td><td><small>equation variable</small></td></tr><tr><td>apparent volumes of distribution (V z )</td><td>1260.0</td><td>L</td><td><small>V/F</small></td></tr><tr><td>ka</td><td>0.873</td><td>/h</td><td><small>kabs</small></td></tr></table><h4>About carbamazepine</h4><p>Carbamazepine is an anticonvulsant used for epilepsy and seizures, trigeminal neuralgia, and bipolar disorder, and has also been used for other mood and psychiatric conditions. It remains widely used and is included on the WHO essential medicines list, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q410412\">Wikidata Q410412</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Carbamazepine\">Carbamazepine</a>.</p><h4>References</h4><ol><li><p>Djordjevic N et al. (2025). ABCB1 Polymorphism Is Associated with Higher Carbamazepine Clearance in Children. <i>Pediatric reports 17(1)</i>. DOI:<a href=\"https://doi.org/10.3390/pediatric17010010\">10.3390/pediatric17010010</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39846525\">39846525</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Djordjevic_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 15552000, Tolerance = 1e-9, Interval = 1));
end Carbamazepine_Djordjevic2025_reference;
