within Pharmacolibrary.Drugs.C_CardiovascularSystem.C08C_SelectiveCalciumChannelBlockersWithMainlyVascula.C08CA04_Nicardipine;
model Nicardipine_Modi1993_reference
  parameter Real Cl_ref = 1.7888888888888892e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.01925 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Nicardipine.M,
    adminMass = 9e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>nicardipine</td></tr><tr><td>ATC code:</td><td>C08CA04</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Modi NB et al. 1993</td></tr><tr><td>population:</td><td>healthy males</td></tr><tr><td>measured compound:</td><td>nicardipine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_nicardipine/Nicardipine_Modi1993_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>average total body clearance of nicardipine</td><td>0.92</td><td>L/h/kg</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>0.275</td><td>L/kg</td><td><small>V</small></td></tr></table><h4>About nicardipine</h4><p>Nicardipine is a dihydropyridine calcium channel blocker used to treat arterial hypertension and angina pectoris. It is an approved drug, though it is not authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q729213\">Wikidata Q729213</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Nicardipine\">Nicardipine</a>.</p><h4>References</h4><ol><li><p>Modi NB et al. (1993). Application of a system analysis approach to population pharmacokinetics and pharmacodynamics of nicardipine hydrochloride in healthy males. <i>Journal of pharmaceutical sciences 82(7):705–713</i>. DOI:<a href=\"https://doi.org/10.1002/jps.2600820707\">10.1002/jps.2600820707</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/8360844\">8360844</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Modi_1993: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Nicardipine_Modi1993_reference;
