within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01M_QuinoloneAntibacterials.J01MA02_Ciprofloxacin;
model Ciprofloxacin_Santavy2023_reference
  parameter Real Cl_ref = 2.472222222222222e-08 "Cl [m3/s]";
  parameter Real Vd_ref = 0.01009 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Ciprofloxacin.M,
    adminMass = 0.001,
    ka = 0.0002777777777777778,
    Tlag = 0.0,
    k21 = 3.922111480251016e-06
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>ciprofloxacin</td></tr><tr><td>ATC code:</td><td>J01MA02</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Santavy P et al. 2023</td></tr><tr><td>population:</td><td>adults undergoing cardiac surgery with extracorporeal circulation</td></tr><tr><td>measured compound:</td><td>ciprofloxacin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_ciprofloxacin/Ciprofloxacin_Santavy2023_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL_pop (L/h)</td><td>0.089</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>V1_pop (L)</td><td>10.09</td><td>L</td><td><small>V1</small></td></tr><tr><td>Q_pop (L/h)</td><td>0.17</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>V2_pop (L)</td><td>12.04</td><td>L</td><td><small>V2</small></td></tr><tr><td>Ka (h−1)</td><td>1.0</td><td>h−1</td><td><small>kabs</small></td></tr></table><h4>About ciprofloxacin</h4><p>Ciprofloxacin is a fluoroquinolone antibiotic used to treat many bacterial infections, including urinary tract infections, pneumonia, typhoid fever, gonorrhea, and bone and joint infections. It is widely used worldwide and appears on the WHO list of essential medicines, available as tablets and also as eye and ear preparations.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q256602\">Wikidata Q256602</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Ciprofloxacin\">Ciprofloxacin</a>.</p><h4>References</h4><ol><li><p>Santavy P et al. (2023). Population pharmacokinetics of three alternative prophylactic antibiotics during cardiac surgery with extracorporeal circulation. <i>Biomedical papers of the Medical Faculty of the University Palacky, Olomouc, Czechoslovakia 167(2):208–211</i>. DOI:<a href=\"https://doi.org/10.5507/bp.2022.033\">10.5507/bp.2022.033</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35775358\">35775358</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Santavy_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 1468800, Tolerance = 1e-9, Interval = 1));
end Ciprofloxacin_Santavy2023_reference;
