within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01M_QuinoloneAntibacterials.J01MA02_Ciprofloxacin;
model Ciprofloxacin_Dowling1995_reference
  parameter Real Cl_ref = 2.1139999999999997e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0147 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 6.8,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Ciprofloxacin.M,
    adminMass = 0.001,
    ka = 0.0002777777777777778,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>ciprofloxacin</td></tr><tr><td>ATC code:</td><td>J01MA02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Dowling PM et al. 1995</td></tr><tr><td>population:</td><td>healthy mature ponies</td></tr><tr><td>measured compound:</td><td>ciprofloxacin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_ciprofloxacin/Ciprofloxacin_Dowling1995_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Mean plasma half-life, based on the terminal phase</td><td>157.89</td><td>min</td><td><small>t1/2z</small></td></tr><tr><td>Total body clearance of ciprofloxacin</td><td>18.12</td><td>mL/min/kg</td><td><small>CL</small></td></tr><tr><td>Volume of distribution at steady-state</td><td>3.45</td><td>L/kg</td><td><small>Vss</small></td></tr><tr><td>Bioavailability of oral ciprofloxacin in ponies</td><td>6.8</td><td>%</td><td><small>Fab</small></td></tr><tr><td>Vd (L)</td><td>14.7</td><td>L</td><td><small>V</small></td></tr><tr><td>Ka (h−1)</td><td>1.0</td><td>h−1</td><td><small>kabs</small></td></tr></table><h4>About ciprofloxacin</h4><p>Ciprofloxacin is a fluoroquinolone antibiotic used to treat many bacterial infections, including urinary tract infections, pneumonia, typhoid fever, gonorrhea, and bone and joint infections. It is widely used worldwide and appears on the WHO list of essential medicines, available as tablets and also as eye and ear preparations.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q256602\">Wikidata Q256602</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Ciprofloxacin\">Ciprofloxacin</a>.</p><h4>References</h4><ol><li><p>Dowling PM et al. (1995). Pharmacokinetics of ciprofloxacin in ponies. <i>Journal of veterinary pharmacology and therapeutics 18(1):7–12</i>. DOI:<a href=\"https://doi.org/10.1111/j.1365-2885.1995.tb00543.x\">10.1111/j.1365-2885.1995.tb00543.x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/7752310\">7752310</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Dowling_1995: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Ciprofloxacin_Dowling1995_reference;
