within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10A_LipidModifyingAgentsPlain.C10AA05_Atorvastatin;
model Atorvastatin_Kong2025_reference
  parameter Real Cl_ref = 0.00010083333333333334 "Cl [m3/s]";
  parameter Real Vd_ref = 0.835 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Atorvastatin.M,
    adminMass = 1e-08,
    ka = 0.0020916666666666666,
    Tlag = 0.0,
    k21 = 0.00018677339432056413
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>atorvastatin</td></tr><tr><td>ATC code:</td><td>C10AA05</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Kong W et al. 2025</td></tr><tr><td>population:</td><td>healthy volunteers and end-stage renal disease patients</td></tr><tr><td>measured compound:</td><td>atorvastatin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_atorvastatin/Atorvastatin_Kong2025_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>k a</td><td>7.53</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>CL/F</td><td>363</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>V c/F</td><td>835</td><td>L</td><td><small>V1/F</small></td></tr><tr><td>V p/F</td><td>5830</td><td>L</td><td><small>V2/F</small></td></tr><tr><td>Q/F</td><td>3920</td><td>L/h</td><td><small>Q/F</small></td></tr></table><h4>About atorvastatin</h4><p>Atorvastatin is a statin used to lower blood lipids, treating conditions such as hypercholesterolemia, hypertriglyceridemia, arteriosclerosis, and coronary artery disease. It is an approved prescription medicine, widely used, and also available in combination lipid-modifying products.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q668093\">Wikidata Q668093</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Atorvastatin\">Atorvastatin</a>.</p><h4>References</h4><ol><li><p>Kong W et al. (2025). Microdose Cocktail Study Reveals the Activity and Key Influencing Factors of OATP1B, P-Gp, BCRP, and CYP3A in End-Stage Renal Disease Patients. <i>Clinical pharmacology and therapeutics 117(5):1303–1312</i>. DOI:<a href=\"https://doi.org/10.1002/cpt.3546\">10.1002/cpt.3546</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39789999\">39789999</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Kong_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Atorvastatin_Kong2025_reference;
