within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10A_LipidModifyingAgentsPlain.C10AA05_Atorvastatin;
model Atorvastatin_Li2024_reference
  parameter Real Cl_ref = 4.839444444444445e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 1.1196199999999998 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Atorvastatin.M,
    adminMass = 2e-05,
    ka = 0.0002111111111111111,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>atorvastatin</td></tr><tr><td>ATC code:</td><td>C10AA05</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Li Y et al. 2024</td></tr><tr><td>population:</td><td>patients with hyperlipidemia</td></tr><tr><td>measured compound:</td><td>atorvastatin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_atorvastatin/Atorvastatin_Li2024_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>first-order absorption rate</td><td>0.76</td><td>hour-1</td><td><small>kabs</small></td></tr><tr><td>clearance</td><td>174.22</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>apparent volume of distribution</td><td>1119.62</td><td>L</td><td><small>V/F</small></td></tr></table><h4>About atorvastatin</h4><p>Atorvastatin is a statin used to lower blood lipids, treating conditions such as hypercholesterolemia, hypertriglyceridemia, arteriosclerosis, and coronary artery disease. It is an approved prescription medicine, widely used, and also available in combination lipid-modifying products.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q668093\">Wikidata Q668093</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Atorvastatin\">Atorvastatin</a>.</p><h4>References</h4><ol><li><p>Li Y et al. (2024). Population Pharmacokinetics of Atorvastatin in High-Altitude and Plain Patients with Hyperlipidemic. <i>Journal of clinical pharmacology 64(3):345–352</i>. DOI:<a href=\"https://doi.org/10.1002/jcph.2376\">10.1002/jcph.2376</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37864509\">37864509</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Li_2024: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 97200, Tolerance = 1e-9, Interval = 1));
end Atorvastatin_Li2024_reference;
