within Pharmacolibrary.Drugs.N_NervousSystem.N02A_Opioids.N02AX02_Tramadol;
model Tramadol_Elghazali2008_reference
  parameter Real Cl_ref = 5.388888888888888e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.6258 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 101.62,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Tramadol.M,
    adminMass = 0.0003,
    ka = 0.00018055555555555557,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>tramadol</td></tr><tr><td>ATC code:</td><td>N02AX02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Elghazali M et al. 2008</td></tr><tr><td>population:</td><td>camels</td></tr><tr><td>measured compound:</td><td>tramadol</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>distribution half-life (t(1/2)(alpha))</td><td>0.22</td><td>h</td><td><small>t1/2α</small></td></tr><tr><td>elimination half-life (t(1/2)(beta))</td><td>1.33</td><td>h</td><td><small>t1/2β</small></td></tr><tr><td>total body clearance (Cl(T))</td><td>1.94</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>volume of distribution at steady state (Vd(ss))</td><td>2.58</td><td>L kg(-1)</td><td><small>Vss</small></td></tr><tr><td>area under the concentration vs. time curve (AUC(0-infinity))</td><td>1.25</td><td>mg*h/L</td><td><small>AUC∞</small></td></tr><tr><td>maximal plasma tramadol concentration (C(max))</td><td>0.44</td><td>microg mL(-1)</td><td><small>Cmax</small></td></tr><tr><td>time (T(max))</td><td>0.57</td><td>h</td><td><small>tmax</small></td></tr><tr><td>absorption half-life (t(1/2 ka))</td><td>0.17</td><td>h</td><td><small>t1/2ka </small></td></tr><tr><td>(Vd(area))</td><td>8.94</td><td>L kg(-1)</td><td><small>V</small></td></tr><tr><td>mean systemic bioavailability (F)</td><td>101.62</td><td>%</td><td><small>Fab</small></td></tr><tr><td>kₐ</td><td>0.65</td><td>1/h</td><td><small>kabs</small></td></tr></table><h4>About tramadol</h4><p>Tramadol is an opioid painkiller used to treat pain. It is an approved medicine and is widely used, available both alone and in combination with non-opioid analgesics.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q407592\">Wikidata Q407592</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Tramadol\">Tramadol</a>.</p><h4>References</h4><ol><li><p>Elghazali M et al. (2008). The pharmacokinetics, metabolism and urinary detection time of tramadol in camels. <i>Veterinary journal (London, England : 1997) 178(2):272–277</i>. DOI:<a href=\"https://doi.org/10.1016/j.tvjl.2007.07.008\">10.1016/j.tvjl.2007.07.008</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/17904881\">17904881</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Elghazali_2008: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Tramadol_Elghazali2008_reference;
