within Pharmacolibrary.Drugs.N_NervousSystem.N02A_Opioids.N02AX02_Tramadol;
model Tramadol_Yoo2022_reference
  parameter Real Cl_ref = 4.833333333333334e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.041999999999999996 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1.25,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Tramadol.M,
    adminMass = 0.0003,
    ka = 0.00018055555555555557,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>tramadol</td></tr><tr><td>ATC code:</td><td>N02AX02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Yoo O et al. 2022</td></tr><tr><td>population:</td><td>children aged 3-16 years</td></tr><tr><td>measured compound:</td><td>tramadol</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_tramadol/Tramadol_Yoo2022_reference\">pharmacolibrary-docs</a></td></tr></table><h4>About tramadol</h4><p>Tramadol is an opioid painkiller used to treat pain. It is an approved medicine and is widely used, available both alone and in combination with non-opioid analgesics.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q407592\">Wikidata Q407592</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Tramadol\">Tramadol</a>.</p><h4>References</h4><ol><li><p>Yoo O et al. (2022). A randomised controlled trial of a novel tramadol chewable tablet: pharmacokinetics and tolerability in children. <i>Anaesthesia 77(4):438–448</i>. DOI:<a href=\"https://doi.org/10.1111/anae.15650\">10.1111/anae.15650</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35083739\">35083739</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Yoo_2022: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 345600, Tolerance = 1e-9, Interval = 1));
end Tramadol_Yoo2022_reference;
