within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A12A_Calcium.A12AA07_CalciumChloride;
model CalciumChloride_Ansari2022_reference
  parameter Real Cl_ref = 1.55e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.076 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.CalciumChloride.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>calcium_chloride</td></tr><tr><td>ATC code:</td><td>A12AA07</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Ansari JR et al. 2022</td></tr><tr><td>population:</td><td>adults undergoing cesarean delivery</td></tr><tr><td>measured compound:</td><td>calcium</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_calcium_chloride/CalciumChloride_Ansari2022_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>clearance</td><td>0.93</td><td>L/min</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>76</td><td>L</td><td><small>V</small></td></tr></table><h4>About calcium_chloride</h4><p>Calcium chloride is a calcium salt used to treat conditions such as cardiac arrest and tetany, and as a calcium supplement or electrolyte additive. It is an approved medicine, used mainly in hospital settings for intravenous electrolyte replacement and emergency care.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q208451\">Wikidata Q208451</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.CalciumChloride\">CalciumChloride</a>.</p><h4>References</h4><ol><li><p>Ansari JR et al. (2022). Calcium chloride for the prevention of uterine atony during cesarean delivery: A pilot randomized controlled trial and pharmacokinetic study. <i>Journal of clinical anesthesia 80:110796</i>. DOI:<a href=\"https://doi.org/10.1016/j.jclinane.2022.110796\">10.1016/j.jclinane.2022.110796</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35447502\">35447502</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Ansari_2022: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end CalciumChloride_Ansari2022_reference;
