within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09C_AngiotensinIiReceptorBlockersArbsPlain.C09CA07_Telmisartan;
model Telmisartan_Jeong2025_reference
  parameter Real Cl_ref = 5.0833333333333335e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0207 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Telmisartan.M,
    adminMass = 1e-05,
    ka = 5.055555555555555e-05,
    Tlag = 820.8000000000001,
    k12 = 0.00017042404723564142,
    k21 = 9.799382716049382e-06
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>telmisartan</td></tr><tr><td>ATC code:</td><td>C09CA07</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Jeong IH et al. 2025</td></tr><tr><td>population:</td><td>healthy subjects and hypertensive patients</td></tr><tr><td>measured compound:</td><td>telmisartan</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_telmisartan/Telmisartan_Jeong2025_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>k a (h -1 )</td><td>0.182</td><td>h -1</td><td><small>kabs</small></td></tr><tr><td>V 1 /F (L)</td><td>20.7</td><td>L</td><td><small>V1/F</small></td></tr><tr><td>CL/F (L/h)</td><td>18.3</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>V 2 /F (L)</td><td>360</td><td>L</td><td><small>V2/F</small></td></tr><tr><td>Q/F (L/h)</td><td>12.7</td><td>L/h</td><td><small>Q/F</small></td></tr><tr><td>ALAG (h)</td><td>0.228</td><td>h</td><td><small>tlag</small></td></tr></table><h4>About telmisartan</h4><p>Telmisartan is an angiotensin II receptor blocker used to treat high blood pressure and congestive heart failure. It is widely used and authorised in the European Union, available alone and in combination products.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q733186\">Wikidata Q733186</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Telmisartan\">Telmisartan</a>.</p><h4>References</h4><ol><li><p>Jeong IH et al. (2025). Population Pharmacokinetics of Telmisartan in Healthy Subjects and Hypertensive Patients. <i>Clinical pharmacokinetics 64(2):285–295</i>. DOI:<a href=\"https://doi.org/10.1007/s40262-024-01471-3\">10.1007/s40262-024-01471-3</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39808372\">39808372</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Jeong_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Telmisartan_Jeong2025_reference;
