within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A01A_StomatologicalPreparations.A01AB22_Doxycycline;
model Doxycycline "Doxycycline — default model: Doxycycline"
  extends Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01A_Tetracyclines.J01AA02_Doxycycline.Doxycycline;
  annotation (Documentation(info = "<html><body><p>doxycycline under ATC A01AB22: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01A_Tetracyclines.J01AA02_Doxycycline\">J01AA02_Doxycycline</a> (ATC J01AA02); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Doxycycline;
