within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B01A_AntithromboticAgents.B01AA03_Warfarin;
model Warfarin_NeffDavis1981_reference
  parameter Real Cl_ref = 9.666666666666667e-08 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0154 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Warfarin.M,
    adminMass = 7.5e-06,
    ka = 5.9444444444444445e-05,
    Tlag = 4644.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>warfarin</td></tr><tr><td>ATC code:</td><td>B01AA03</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Neff-Davis CA et al. 1981</td></tr><tr><td>population:</td><td>healthy dogs</td></tr><tr><td>measured compound:</td><td>warfarin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_warfarin/Warfarin_NeffDavis1981_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>elimination half-life</td><td>14.5</td><td>h</td><td><small>t1/2z</small></td></tr><tr><td>apparent specific volume of distribution</td><td>0.22</td><td>litre/kg</td><td><small>V</small></td></tr><tr><td>CL</td><td>0.348</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>ka (1/h)</td><td>0.214</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>Lag (h)</td><td>1.29</td><td>h</td><td><small>tlag</small></td></tr></table><h4>About warfarin</h4><p>Warfarin is an anticoagulant used to prevent and treat blood clots in conditions such as atrial fibrillation, heart valve disease, pulmonary embolism, thrombosis, and heart disease. It is widely used in human medicine and is included on the WHO list of essential medicines, though it also serves as a rodenticide and carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q113368879\">Wikidata Q113368879</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Warfarin\">Warfarin</a>.</p><h4>References</h4><ol><li><p>Neff-Davis CA et al. (1981). Warfarin in the dog: pharmacokinetics as related to clinical response. <i>Journal of veterinary pharmacology and therapeutics 4(2):135–140</i>. DOI:<a href=\"https://doi.org/10.1111/j.1365-2885.1981.tb00722.x\">10.1111/j.1365-2885.1981.tb00722.x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/7349326\">7349326</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Neff-Davis_1981: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 345600, Tolerance = 1e-9, Interval = 1));
end Warfarin_NeffDavis1981_reference;
