within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B01A_AntithromboticAgents.B01AA03_Warfarin;
model Warfarin_Aoyama2022_reference
  parameter Real Cl_ref = 9.666666666666667e-08 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0143 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 3.2000000000000003e-06,
    ka = 5.9444444444444445e-05,
    Tlag = 4644.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>warfarin</td></tr><tr><td>ATC code:</td><td>B01AA03</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Aoyama T et al. 2022</td></tr><tr><td>population:</td><td>adult patients</td></tr><tr><td>measured compound:</td><td>S-warfarin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_warfarin/Warfarin_Aoyama2022_reference\">pharmacolibrary-docs</a></td></tr></table><h4>About warfarin</h4><p>Warfarin is an anticoagulant used to prevent and treat blood clots in conditions such as atrial fibrillation, heart valve disease, pulmonary embolism, thrombosis, and heart disease. It is widely used in human medicine and is included on the WHO list of essential medicines, though it also serves as a rodenticide and carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q113368879\">Wikidata Q113368879</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Warfarin\">Warfarin</a>.</p><h4>References</h4><ol><li><p>Aoyama T et al. (2022). External Evaluation of a Bayesian Warfarin Dose Optimization Based on a Kinetic-Pharmacodynamic Model. <i>Biological &amp; pharmaceutical bulletin 45(1):136–142</i>. DOI:<a href=\"https://doi.org/10.1248/bpb.b21-00778\">10.1248/bpb.b21-00778</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34980775\">34980775</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Aoyama_2022: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 604800, Tolerance = 1e-9, Interval = 1));
end Warfarin_Aoyama2022_reference;
