within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B01A_AntithromboticAgents.B01AA03_Warfarin;
model Warfarin_Yuen2010_reference
  parameter Real Cl_ref = 7.666666666666668e-08 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0143 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 7.5e-06,
    ka = 5.9444444444444445e-05,
    Tlag = 4644.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>warfarin</td></tr><tr><td>ATC code:</td><td>B01AA03</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Yuen E et al. 2010</td></tr><tr><td>population:</td><td>healthy Chinese and Indian volunteers</td></tr><tr><td>measured compound:</td><td>S-warfarin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_warfarin/Warfarin_Yuen2010_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>S-warfarin clearance</td><td>0.276</td><td>l/h</td><td><small>CLm/F</small></td></tr><tr><td>ka (1/h)</td><td>0.214</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>Lag (h)</td><td>1.29</td><td>h</td><td><small>tlag</small></td></tr></table><h4>About warfarin</h4><p>Warfarin is an anticoagulant used to prevent and treat blood clots in conditions such as atrial fibrillation, heart valve disease, pulmonary embolism, thrombosis, and heart disease. It is widely used in human medicine and is included on the WHO list of essential medicines, though it also serves as a rodenticide and carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q113368879\">Wikidata Q113368879</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Warfarin\">Warfarin</a>.</p><h4>References</h4><ol><li><p>Yuen E et al. (2010). Ethnic differences in the population pharmacokinetics and pharmacodynamics of warfarin. <i>Journal of pharmacokinetics and pharmacodynamics 37(1):3–24</i>. DOI:<a href=\"https://doi.org/10.1007/s10928-009-9138-4\">10.1007/s10928-009-9138-4</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/19941044\">19941044</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Yuen_2010: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 777600, Tolerance = 1e-9, Interval = 1));
end Warfarin_Yuen2010_reference;
