within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A01A_StomatologicalPreparations.A01AB23_Minocycline;
model Minocycline "Minocycline — default model: Minocycline"
  extends Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01A_Tetracyclines.J01AA08_Minocycline.Minocycline;
  annotation (Documentation(info = "<html><body><p>minocycline under ATC A01AB23: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01A_Tetracyclines.J01AA08_Minocycline\">J01AA08_Minocycline</a> (ATC J01AA08); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Minocycline;
