within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics.N02BE01_Paracetamol;
model Paracetamol_Fritz1984_reference
  parameter Real Cl_ref = 7.233333333333333e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.00635 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Paracetamol.M,
    adminMass = 0.003
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>paracetamol</td></tr><tr><td>ATC code:</td><td>N02BE01</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Fritz AK et al. 1984</td></tr><tr><td>population:</td><td>healthy human males</td></tr><tr><td>measured compound:</td><td>acetaminophen</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_paracetamol/Paracetamol_Fritz1984_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>bioavailability of the tablet relative to that of the solution</td><td>85.0</td><td>%</td><td><small>Fab</small></td></tr><tr><td>propofol clearance capacity in a 38 postmenstrual weeks newborn at birth</td><td>0.029</td><td>l.min−1</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>6.35</td><td>liters</td><td><small>V</small></td></tr><tr><td>Tlag</td><td>4.2</td><td>min</td><td><small>tlag</small></td></tr></table><h4>About paracetamol</h4><p>Paracetamol is a pain-relieving and fever-lowering medicine used to treat pain, fever, and related conditions such as colds and flu. It is very widely used worldwide, appears on the WHO essential medicines list, and is available over the counter in the UK and approved by the FDA.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q57055\">Wikidata Q57055</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Paracetamol\">Paracetamol</a>.</p><h4>References</h4><ol><li><p>Fritz AK et al. (1984). Relative bioavailability and pharmacokinetics: a combination of pentazocine and acetaminophen. <i>Journal of pharmaceutical sciences 73(3):326–331</i>. DOI:<a href=\"https://doi.org/10.1002/jps.2600730311\">10.1002/jps.2600730311</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/6716239\">6716239</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Fritz_1984: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Paracetamol_Fritz1984_reference;
