within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02C_AntiadrenergicAgentsPeripherallyActing.C02CA02_Indoramin;
model Indoramin_Norbury1983_reference
  parameter Real Cl_ref = 2.3216666666666664e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.518 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Indoramin.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>indoramin</td></tr><tr><td>ATC code:</td><td>C02CA02</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Norbury HM et al. 1983</td></tr><tr><td>population:</td><td>middle-aged healthy volunteers</td></tr><tr><td>measured compound:</td><td>indoramin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_indoramin/Indoramin_Norbury1983_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>mean elimination half-life</td><td>4.0</td><td>h</td><td><small>t1/2z</small></td></tr><tr><td>mean plasma clearance</td><td>19.9</td><td>ml/min/kg</td><td><small>CL</small></td></tr><tr><td>mean volume of distribution</td><td>7.4</td><td>l/kg</td><td><small>V</small></td></tr><tr><td>Protein binding of indoramin</td><td>85.6</td><td>%</td><td><small>fu</small></td></tr></table><h4>About indoramin</h4><p>Indoramin is an alpha-1 adrenergic blocker that was used to treat high blood pressure and enlarged prostate. It has been withdrawn and is no longer in use.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q408963\">Wikidata Q408963</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Indoramin\">Indoramin</a>.</p><h4>References</h4><ol><li><p>Norbury HM et al. (1983). Pharmacokinetics of intravenous indoramin in middle-aged male and female volunteers. <i>European journal of clinical pharmacology 25(2):243–246</i>. DOI:<a href=\"https://doi.org/10.1007/BF00543798\">10.1007/BF00543798</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/6628508\">6628508</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Norbury_1983: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Indoramin_Norbury1983_reference;
