within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics.N02BF01_Gabapentin;
model Gabapentin_AlZubaydi2024_reference
  parameter Real Cl_ref = 1.591666666666667e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.044610000000000004 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Gabapentin.M,
    adminMass = 0.0001,
    ka = 0.00021611111111111112,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>gabapentin</td></tr><tr><td>ATC code:</td><td>N02BF01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Al-Zubaydi F et al. 2024</td></tr><tr><td>population:</td><td>hospitalized adults</td></tr><tr><td>measured compound:</td><td>gabapentin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_gabapentin/Gabapentin_AlZubaydi2024_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>ka (h−1)</td><td>0.778</td><td>h−1</td><td><small>kabs</small></td></tr><tr><td>Vd (L)</td><td>44.61</td><td>L</td><td><small>V</small></td></tr><tr><td>Cl (L/h)</td><td>5.73</td><td>L/h</td><td><small>CL</small></td></tr></table><h4>About gabapentin</h4><p>Gabapentin is an anticonvulsant and pain-relieving medicine used for epilepsy and various types of pain and neurological conditions, such as neuropathy, restless legs syndrome, and fibromyalgia. It is an approved medicine in widespread clinical use, and has also been studied for other conditions.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q410352\">Wikidata Q410352</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Gabapentin\">Gabapentin</a>.</p><h4>References</h4><ol><li><p>Al-Zubaydi F et al. (2024). Development of a Population Pharmacokinetic Gabapentin Model Leveraging Therapeutic Drug Monitoring Concentrations. <i>Pharmaceutics 16(12)</i>. DOI:<a href=\"https://doi.org/10.3390/pharmaceutics16121514\">10.3390/pharmaceutics16121514</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39771494\">39771494</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Al-Zubaydi_2024: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 111600, Tolerance = 1e-9, Interval = 1));
end Gabapentin_AlZubaydi2024_reference;
