within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics.N02BF01_Gabapentin;
model Gabapentin_Siao2010_reference
  parameter Real Cl_ref = 3.5000000000000004e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.006328 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Gabapentin.M,
    adminMass = 0.0018,
    ka = 0.0014555555555555556,
    Tlag = 1620.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>gabapentin</td></tr><tr><td>ATC code:</td><td>N02BF01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Siao KT et al. 2010</td></tr><tr><td>population:</td><td>healthy adult cats</td></tr><tr><td>measured compound:</td><td>gabapentin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_gabapentin/Gabapentin_Siao2010_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>apparent volume of the central compartment</td><td>90.4</td><td>mL/kg</td><td><small>V/F</small></td></tr><tr><td>apparent volume of distribution at steady state</td><td>650</td><td>mL/kg</td><td><small>Vss</small></td></tr><tr><td>clearance</td><td>3</td><td>mL/min/kg</td><td><small>CL</small></td></tr><tr><td>terminal half-life</td><td>170</td><td>minutes</td><td><small>t1/2z</small></td></tr><tr><td>systemic availability</td><td>88.7</td><td>%</td><td><small>Fab</small></td></tr><tr><td>K01 (1/hr)</td><td>5.24</td><td>1/hr</td><td><small>kabs</small></td></tr><tr><td>TLAG (hr)</td><td>0.45</td><td>hr</td><td><small>tlag</small></td></tr></table><h4>About gabapentin</h4><p>Gabapentin is an anticonvulsant and pain-relieving medicine used for epilepsy and various types of pain and neurological conditions, such as neuropathy, restless legs syndrome, and fibromyalgia. It is an approved medicine in widespread clinical use, and has also been studied for other conditions.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q410352\">Wikidata Q410352</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Gabapentin\">Gabapentin</a>.</p><h4>References</h4><ol><li><p>Siao KT et al. (2010). Pharmacokinetics of gabapentin in cats. <i>American journal of veterinary research 71(7):817–821</i>. DOI:<a href=\"https://doi.org/10.2460/ajvr.71.7.817\">10.2460/ajvr.71.7.817</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/20594085\">20594085</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Siao_2010: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Gabapentin_Siao2010_reference;
