within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B06A_OtherHematologicalAgents.B06AC01_C1InhibitorPlasmaDerived;
model C1InhibitorPlasmaDerived_Pawaskar2018_reference
  parameter Real Cl_ref = 2.0027777777777774e-08 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0035 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 43.0,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 0.0001,
    ka = 4.055555555555556e-06,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>c1_inhibitor_plasma_derived</td></tr><tr><td>ATC code:</td><td>B06AC01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Pawaskar D et al. 2018</td></tr><tr><td>population:</td><td>healthy volunteers and patients with hereditary angioedema</td></tr><tr><td>measured compound:</td><td>C1-inhibitor functional activity</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_c1_inhibitor_plasma_derived/C1InhibitorPlasmaDerived_Pawaskar2018_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>mean population bioavailability of C1-INH (SC)</td><td>43</td><td>%</td><td><small>Fab</small></td></tr><tr><td>clearance (CL)</td><td>1.03</td><td>mL/hour/kg</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>0.05</td><td>L/kg</td><td><small>V</small></td></tr><tr><td>absorption rate</td><td>0.0146</td><td>hour-1</td><td><small>kabs</small></td></tr><tr><td>median time to peak concentration</td><td>59</td><td>hours</td><td><small>tmax</small></td></tr><tr><td>median apparent plasma half-life</td><td>69</td><td>hours</td><td><small>t1/2z</small></td></tr></table><h4>About c1_inhibitor_plasma_derived</h4><p>Plasma-derived C1 inhibitor is used to treat hereditary angioedema. It is an approved medicine, with an authorised product in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q22075742\">Wikidata Q22075742</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.C1InhibitorPlasmaDerived\">C1InhibitorPlasmaDerived</a>.</p><h4>References</h4><ol><li><p>Pawaskar D et al. (2018). Population pharmacokinetics of subcutaneous C1-inhibitor for prevention of attacks in patients with hereditary angioedema. <i>Clinical and experimental allergy : journal of the British Society for Allergy and Clinical Immunology 48(10):1325–1332</i>. DOI:<a href=\"https://doi.org/10.1111/cea.13220\">10.1111/cea.13220</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29998524\">29998524</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Pawaskar_2018: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end C1InhibitorPlasmaDerived_Pawaskar2018_reference;
