within Pharmacolibrary.Drugs.N_NervousSystem.N06A_Antidepressants.N06AB04_Citalopram;
model Citalopram_Friberg2006_reference
  parameter Real Cl_ref = 6.138888888888889e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 1.28 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Citalopram.M,
    adminMass = 8e-05,
    ka = 0.0004111111111111111,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>citalopram</td></tr><tr><td>ATC code:</td><td>N06AB04</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Friberg LE et al. 2006</td></tr><tr><td>population:</td><td>patients with citalopram overdose</td></tr><tr><td>measured compound:</td><td>citalopram</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_citalopram/Citalopram_Friberg2006_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>apparent (oral) clearance</td><td>22.1</td><td>l h -1</td><td><small>CL</small></td></tr><tr><td>apparent volume of distribution</td><td>1280</td><td>l</td><td><small>V/F</small></td></tr><tr><td>absorption rate constant</td><td>1.48</td><td>h -1</td><td><small>kabs</small></td></tr></table><h4>About citalopram</h4><p>Citalopram is an antidepressant of the selective serotonin reuptake inhibitor class used to treat depression and related mental and mood disorders, as well as anxiety conditions such as generalized anxiety disorder and obsessive-compulsive disorder. It is an approved medicine in widespread clinical use, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q409672\">Wikidata Q409672</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Citalopram\">Citalopram</a>.</p><h4>References</h4><ol><li><p>Friberg LE et al. (2006). Pharmacokinetic-pharmacodynamic modelling of QT interval prolongation following citalopram overdoses. <i>British journal of clinical pharmacology 61(2):177–190</i>. DOI:<a href=\"https://doi.org/10.1111/j.1365-2125.2005.02546.x\">10.1111/j.1365-2125.2005.02546.x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16433872\">16433872</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Friberg_2006: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 777600, Tolerance = 1e-9, Interval = 1));
end Citalopram_Friberg2006_reference;
