within Pharmacolibrary.Drugs.C_CardiovascularSystem.C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresFo.C05AD05_Procaine;
model Procaine_Seifen1979_reference
  parameter Real Cl_ref = 9.333333333333334e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0553 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Procaine.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>procaine</td></tr><tr><td>ATC code:</td><td>C05AD05</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Seifen AB et al. 1979</td></tr><tr><td>population:</td><td>women undergoing hysterectomy</td></tr><tr><td>measured compound:</td><td>procaine</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>distribution half-life (t1/2 alpha)</td><td>2.49</td><td>minutes</td><td><small>t1/2α</small></td></tr><tr><td>elimination half-life (t1/2 beta)</td><td>7.69</td><td>minutes</td><td><small>t1/2β</small></td></tr><tr><td>volume of distribution at steady-state</td><td>0.79</td><td>L/kg</td><td><small>Vss</small></td></tr><tr><td>total body clearance</td><td>0.08</td><td>L/kg/min</td><td><small>CL</small></td></tr></table><h4>About procaine</h4><p>Procaine is a local anesthetic used to relieve pain, for example in procedures involving the skin, eye, or hemorrhoids. It is an approved drug, also approved for veterinary use, and remains in use mainly as a local anesthetic.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q423741\">Wikidata Q423741</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Procaine\">Procaine</a>.</p><h4>References</h4><ol><li><p>Seifen AB et al. (1979). Pharmacokinetics of intravenous procaine infusion in humans. <i>Anesthesia and analgesia 58(5):382–386</i>. DOI:<a href=\"https://doi.org/10.1213/00000539-197909000-00007\">10.1213/00000539-197909000-00007</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/573562\">573562</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Seifen_1979: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Procaine_Seifen1979_reference;
