within Pharmacolibrary.Drugs.N_NervousSystem.N05A_Antipsychotics.N05AD01_Haloperidol;
model Haloperidol_Li2022_reference
  parameter Real Cl_ref = 1.7705555555555556e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 2.3051999999999997 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Haloperidol.M,
    adminMass = 5e-07
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>haloperidol</td></tr><tr><td>ATC code:</td><td>N05AD01</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Li L et al. 2022</td></tr><tr><td>population:</td><td>critically ill adult patients with ICU delirium</td></tr><tr><td>measured compound:</td><td>haloperidol</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_haloperidol/Haloperidol_Li2022_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL (L/h)</td><td>63.74</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Vd (L)</td><td>2305.2</td><td>L</td><td><small>V</small></td></tr></table><h4>About haloperidol</h4><p>Haloperidol is an antipsychotic used to treat conditions such as schizophrenia, psychosis, delirium, Tourette syndrome, and vomiting. It is widely used and appears on the WHO list of essential medicines, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q251347\">Wikidata Q251347</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Haloperidol\">Haloperidol</a>.</p><h4>References</h4><ol><li><p>Li L et al. (2022). Pharmacokinetics of Haloperidol in Critically Ill Patients: Is There an Association with Inflammation?. <i>Pharmaceutics 14(3)</i>. DOI:<a href=\"https://doi.org/10.3390/pharmaceutics14030549\">10.3390/pharmaceutics14030549</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35335925\">35335925</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Li_2022: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 518400, Tolerance = 1e-9, Interval = 1));
end Haloperidol_Li2022_reference;
