within Pharmacolibrary.Drugs.C_CardiovascularSystem.C04A_PeripheralVasodilators.C04AB02_Tolazoline;
model Tolazoline_Casbeer2013_reference
  parameter Real Cl_ref = 1.5944444444444445e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.11760000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Tolazoline.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>tolazoline</td></tr><tr><td>ATC code:</td><td>C04AB02</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Casbeer HC et al. 2013</td></tr><tr><td>population:</td><td>healthy adult horses</td></tr><tr><td>measured compound:</td><td>tolazoline</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Systemic clearance</td><td>0.82</td><td>L/h/kg</td><td><small>CL</small></td></tr><tr><td>steady state volume of distribution</td><td>1.68</td><td>L/kg</td><td><small>Vss</small></td></tr><tr><td>terminal elimination half-life</td><td>2.69</td><td>h</td><td><small>t1/2z</small></td></tr></table><h4>About tolazoline</h4><p>Tolazoline is a vasodilator that was used for circulatory disorders such as Raynaud disease, thrombophlebitis, thromboangiitis obliterans, arteriosclerosis obliterans, systemic scleroderma, causalgia, and persistent fetal circulation syndrome. It has been withdrawn for human use but remains an approved veterinary drug.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q413772\">Wikidata Q413772</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Tolazoline\">Tolazoline</a>.</p><h4>References</h4><ol><li><p>Casbeer HC et al. (2013). Pharmacokinetics and pharmacodynamic effects of tolazoline following intravenous administration to horses. <i>Veterinary journal (London, England : 1997) 196(3):504–509</i>. DOI:<a href=\"https://doi.org/10.1016/j.tvjl.2012.12.006\">10.1016/j.tvjl.2012.12.006</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/23321455\">23321455</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Casbeer_2013: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Tolazoline_Casbeer2013_reference;
