within Pharmacolibrary.Drugs.N_NervousSystem.N06A_Antidepressants.N06AB08_Fluvoxamine;
model Fluvoxamine_Strauss1999_reference
  parameter Real Cl_ref = 2.8055555555555556e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.07840000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Fluvoxamine.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>fluvoxamine</td></tr><tr><td>ATC code:</td><td>N06AB08</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Strauss WL et al. 1999</td></tr><tr><td>population:</td><td>adults</td></tr><tr><td>measured compound:</td><td>fluvoxamine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_fluvoxamine/Fluvoxamine_Strauss1999_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>brain volume of distribution</td><td>1.12</td><td>L/kg</td><td><small>V</small></td></tr><tr><td>clearance</td><td>1.01</td><td>L/hour</td><td><small>CL</small></td></tr><tr><td>bioavailability of fluvoxamine to the brain from plasma</td><td>1.85</td><td></td><td><small>Fab</small></td></tr></table><h4>About fluvoxamine</h4><p>Fluvoxamine is a selective serotonin reuptake inhibitor antidepressant used for depression, obsessive-compulsive disorder, anxiety disorders and panic disorder. It is an approved medicine used worldwide in everyday clinical practice, mainly for obsessive-compulsive disorder and depression.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q409236\">Wikidata Q409236</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Fluvoxamine\">Fluvoxamine</a>.</p><h4>References</h4><ol><li><p>Strauss WL et al. (1999). Characterization of human brain pharmacokinetics using a two-compartment model. <i>Biological psychiatry 45(10):1384–1388</i>. DOI:<a href=\"https://doi.org/10.1016/s0006-3223(98)00324-2\">10.1016/s0006-3223(98)00324-2</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/10349045\">10349045</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Strauss_1999: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 1036800, Tolerance = 1e-9, Interval = 1));
end Fluvoxamine_Strauss1999_reference;
