within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins.A10BX18_Dorzagliatin;
model Dorzagliatin_Wang2023_reference
  parameter Real Cl_ref = 2.8888888888888894e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.08059999999999999 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_3C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Dorzagliatin.M,
    adminMass = 0.0001,
    ka = 0.0009138888888888889,
    Tlag = 0.0,
    k12 = 1.0408050730631377e-05,
    k21 = 3.165618448637317e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>dorzagliatin</td></tr><tr><td>ATC code:</td><td>A10BX18</td></tr><tr><td>model:</td><td>three compartments, oral dosing <small>(PK_3C_enteral)</small></td></tr><tr><td>source:</td><td>Wang K et al. 2023</td></tr><tr><td>population:</td><td>healthy subjects and patients with type 2 diabetes mellitus</td></tr><tr><td>measured compound:</td><td>dorzagliatin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_dorzagliatin/Dorzagliatin_Wang2023_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F (L/h)</td><td>10.4</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>Vc/F (L)</td><td>80.6</td><td>L</td><td><small>V1/F</small></td></tr><tr><td>Q/F (L/h)</td><td>3.02</td><td>L/h</td><td><small>Q/F</small></td></tr><tr><td>Vp/F (L)</td><td>26.5</td><td>L</td><td><small>V2/F</small></td></tr><tr><td>Ka (h−1)</td><td>3.29</td><td>h−1</td><td><small>kabs</small></td></tr><tr><td>D1 (h)</td><td>0.418</td><td>h</td><td><small>D1</small></td></tr><tr><td>CLBW</td><td>0.255</td><td>L/h/kg</td><td><small>CL</small></td></tr><tr><td>Vc,BW</td><td>0.553</td><td>L/kg</td><td><small>V1</small></td></tr></table><h4>About dorzagliatin</h4><p>Dorzagliatin is an investigational blood glucose-lowering drug studied for diabetes. It is not yet an approved medicine and has no marketing authorisation in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q76754209\">Wikidata Q76754209</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Dorzagliatin\">Dorzagliatin</a>.</p><h4>References</h4><ol><li><p>Wang K et al. (2023). Population Pharmacokinetic Analysis of Dorzagliatin in Healthy Subjects and Patients with Type 2 Diabetes Mellitus. <i>Clinical pharmacokinetics 62(10):1413–1425</i>. DOI:<a href=\"https://doi.org/10.1007/s40262-023-01286-8\">10.1007/s40262-023-01286-8</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37537410\">37537410</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Wang_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 100800, Tolerance = 1e-9, Interval = 1));
end Dorzagliatin_Wang2023_reference;
