within Pharmacolibrary.Drugs.C_CardiovascularSystem.C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresFo.C05AE03_Diltiazem;
model Diltiazem "Diltiazem — default model: Diltiazem"
  extends Pharmacolibrary.Drugs.C_CardiovascularSystem.C08D_SelectiveCalciumChannelBlockersWithDirectCardiac.C08DB01_Diltiazem.Diltiazem;
  annotation (Documentation(info = "<html><body><p>diltiazem under ATC C05AE03: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.C_CardiovascularSystem.C08D_SelectiveCalciumChannelBlockersWithDirectCardiac.C08DB01_Diltiazem\">C08DB01_Diltiazem</a> (ATC C08DB01); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Diltiazem;
