within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01B_Antimalarials.P01BA02_Hydroxychloroquine;
model Hydroxychloroquine_Thmans2020_reference
  parameter Real Cl_ref = 2.7472222222222226e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.605 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.746,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Hydroxychloroquine.M,
    adminMass = 0.0002,
    ka = 0.00021250000000000002,
    Tlag = 1602.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>hydroxychloroquine</td></tr><tr><td>ATC code:</td><td>P01BA02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Thémans P et al. 2020</td></tr><tr><td>population:</td><td>COVID-19 patients</td></tr><tr><td>measured compound:</td><td>hydroxychloroquine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_hydroxychloroquine/Hydroxychloroquine_Thmans2020_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Ka (/h)</td><td>0.765</td><td>/h</td><td><small>kabs</small></td></tr><tr><td>V (L)</td><td>605</td><td>L</td><td><small>V</small></td></tr><tr><td>CL (L/h)</td><td>9.89</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Tlag (h)</td><td>0.445</td><td>h</td><td><small>tlag</small></td></tr><tr><td>Εprop ( 2 )</td><td>0.044</td><td></td><td><small>prop_error</small></td></tr><tr><td>Εadd ( 2 )</td><td>0.000365</td><td></td><td><small>E</small></td></tr></table><h4>About hydroxychloroquine</h4><p>Hydroxychloroquine is used to treat and prevent malaria and to manage autoimmune conditions such as systemic lupus erythematosus, rheumatoid arthritis, Sjögren's syndrome, and certain skin diseases. It is widely used and is included on the WHO list of essential medicines.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q421094\">Wikidata Q421094</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Hydroxychloroquine\">Hydroxychloroquine</a>.</p><h4>References</h4><ol><li><p>Thémans P et al. (2020). Population Pharmacokinetics of Hydroxychloroquine in COVID-19 Patients: Implications for Dose Optimization. <i>European journal of drug metabolism and pharmacokinetics 45(6):703–713</i>. DOI:<a href=\"https://doi.org/10.1007/s13318-020-00648-y\">10.1007/s13318-020-00648-y</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32968954\">32968954</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Thémans_2020: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 777600, Tolerance = 1e-9, Interval = 1));
end Hydroxychloroquine_Thmans2020_reference;
