within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01C_CardiacStimulantsExclCardiacGlycosides.C01CX08_Levosimendan;
model Levosimendan_Jonsson2003_reference
  parameter Real Cl_ref = 3.6944444444444446e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.016800000000000002 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Levosimendan.M,
    adminMass = 1.1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>levosimendan</td></tr><tr><td>ATC code:</td><td>C01CX08</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Jonsson EN et al. 2003</td></tr><tr><td>population:</td><td>patients with congestive heart failure</td></tr><tr><td>measured compound:</td><td>levosimendan</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_levosimendan/Levosimendan_Jonsson2003_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>clearance</td><td>13.3</td><td>l h-1</td><td><small>CL</small></td></tr><tr><td>central volume of distribution</td><td>16.8</td><td>l</td><td><small>V</small></td></tr></table><h4>About levosimendan</h4><p>Levosimendan is a calcium sensitiser used to treat acutely decompensated congestive heart failure. It is an approved cardiac stimulant, though its use appears limited and it has also been investigated and withdrawn in some settings.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q162541\">Wikidata Q162541</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Levosimendan\">Levosimendan</a>.</p><h4>References</h4><ol><li><p>Jonsson EN et al. (2003). Population pharmacokinetics of levosimendan in patients with congestive heart failure. <i>British journal of clinical pharmacology 55(6):544–551</i>. DOI:<a href=\"https://doi.org/10.1046/j.1365-2125.2003.01778.x\">10.1046/j.1365-2125.2003.01778.x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/12814448\">12814448</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Jonsson_2003: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Levosimendan_Jonsson2003_reference;
