within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02A_AntiadrenergicAgentsCentrallyActing.C02AC02_Guanfacine;
model Guanfacine_Knebel2015_reference
  parameter Real Cl_ref = 9.194444444444445e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.804 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Guanfacine.M,
    adminMass = 3e-06,
    ka = 0.00015333333333333334,
    Tlag = 2343.6
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>guanfacine</td></tr><tr><td>ATC code:</td><td>C02AC02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Knebel W et al. 2015</td></tr><tr><td>population:</td><td>pediatric patients</td></tr><tr><td>measured compound:</td><td>guanfacine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_guanfacine/Guanfacine_Knebel2015_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>apparent clearance (CL/F)</td><td>33.1</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>apparent volume of distribution</td><td>804</td><td>L</td><td><small>V/F</small></td></tr><tr><td>absorption rate constant</td><td>0.552</td><td>h(-1)</td><td><small>kabs</small></td></tr><tr><td>absorption lag time</td><td>0.651</td><td>h</td><td><small>tlag</small></td></tr></table><h4>About guanfacine</h4><p>Guanfacine is used to treat high blood pressure and attention deficit hyperactivity disorder. It is an approved medicine, with products authorised in the European Union for ADHD, and it is also being studied for other uses.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q5613599\">Wikidata Q5613599</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Guanfacine\">Guanfacine</a>.</p><h4>References</h4><ol><li><p>Knebel W et al. (2015). Population Pharmacokinetic Modeling of Guanfacine in Pediatric Patients. <i>Clinical pharmacokinetics 54(8):875–883</i>. DOI:<a href=\"https://doi.org/10.1007/s40262-015-0245-7\">10.1007/s40262-015-0245-7</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25724291\">25724291</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Knebel_2015: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 345600, Tolerance = 1e-9, Interval = 1));
end Guanfacine_Knebel2015_reference;
