within Pharmacolibrary.Drugs.R_RespiratorySystem.R03C_AdrenergicsForSystemicUse.R03CC02_Salbutamol;
model Salbutamol "Salbutamol — default model: Salbutamol"
  extends Pharmacolibrary.Drugs.R_RespiratorySystem.R03A_AdrenergicsInhalants.R03AC02_Salbutamol.Salbutamol;
  annotation (Documentation(info = "<html><body><p>salbutamol under ATC R03CC02: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.R_RespiratorySystem.R03A_AdrenergicsInhalants.R03AC02_Salbutamol\">R03AC02_Salbutamol</a> (ATC R03AC02); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Salbutamol;
