within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01C_CardiacStimulantsExclCardiacGlycosides.C01CA07_Dobutamine;
model Dobutamine_Hallik2020_reference
  parameter Real Cl_ref = 1.1444444444444444e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.00529 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Dobutamine.M,
    adminMass = 0.0005
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>dobutamine</td></tr><tr><td>ATC code:</td><td>C01CA07</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Hallik M et al. 2020</td></tr><tr><td>population:</td><td>critically ill neonates</td></tr><tr><td>measured compound:</td><td>dobutamine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_dobutamine/Dobutamine_Hallik2020_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL</td><td>41.2</td><td>L h-1</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>5.29</td><td>L</td><td><small>V</small></td></tr></table><h4>About dobutamine</h4><p>Dobutamine is a cardiotonic sympathomimetic drug used to treat heart disease. It is an approved medication given as a cardiac stimulant, typically in hospital settings for acute heart conditions.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q422782\">Wikidata Q422782</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Dobutamine\">Dobutamine</a>.</p><h4>References</h4><ol><li><p>Hallik M et al. (2020). Population pharmacokinetics and pharmacodynamics of dobutamine in neonates on the first days of life. <i>British journal of clinical pharmacology 86(2):318–328</i>. DOI:<a href=\"https://doi.org/10.1111/bcp.14146\">10.1111/bcp.14146</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31657867\">31657867</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Hallik_2020: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Dobutamine_Hallik2020_reference;
