within Pharmacolibrary.Drugs.S_SensoryOrgans.S01F_MydriaticsAndCycloplegics.S01FA02_Scopolamine;
model Scopolamine "Scopolamine — default model: Scopolamine"
  extends Pharmacolibrary.Drugs.N_NervousSystem.N05C_HypnoticsAndSedatives.N05CM05_Scopolamine.Scopolamine;
  annotation (Documentation(info = "<html><body><p>scopolamine under ATC S01FA02: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.N_NervousSystem.N05C_HypnoticsAndSedatives.N05CM05_Scopolamine\">N05CM05_Scopolamine</a> (ATC N05CM05); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Scopolamine;
