within Pharmacolibrary.Drugs.D_Dermatologicals.D06A_AntibioticsForTopicalUse.D06AX07_Gentamicin;
model Gentamicin "Gentamicin — default model: Gentamicin"
  extends Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01G_AminoglycosideAntibacterials.J01GB03_Gentamicin.Gentamicin;
  annotation (Documentation(info = "<html><body><p>gentamicin under ATC D06AX07: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01G_AminoglycosideAntibacterials.J01GB03_Gentamicin\">J01GB03_Gentamicin</a> (ATC J01GB03); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Gentamicin;
