within Pharmacolibrary.Drugs.D_Dermatologicals.D08A_AntisepticsAndDisinfectants.D08AE05_Chloroxylenol;
model Chloroxylenol_Dorantes1992_reference
  parameter Real Cl_ref = 4.055555555555556e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0224 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Chloroxylenol.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>chloroxylenol</td></tr><tr><td>ATC code:</td><td>D08AE05</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Dorantes A et al. 1992</td></tr><tr><td>population:</td><td>healthy mongrel dogs</td></tr><tr><td>measured compound:</td><td>chloroxylenol</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>elimination half-life</td><td>1.84</td><td>hr</td><td><small>t1/2z</small></td></tr><tr><td>mean residence time</td><td>1.69</td><td>hr</td><td><small>MRT</small></td></tr><tr><td>apparent volume of distribution at steady state</td><td>22.4</td><td>liters</td><td><small>Vss</small></td></tr><tr><td>plasma clearance</td><td>14.6</td><td>liters/hr</td><td><small>CL</small></td></tr><tr><td>bioavailability of PCMX</td><td>21</td><td>%</td><td><small>Fab</small></td></tr></table><h4>About chloroxylenol</h4><p>Chloroxylenol is an antiseptic and disinfectant used to treat or prevent local skin infections. It is widely used, including in household antiseptic products, and is included on the WHO list of essential medicines.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q426460\">Wikidata Q426460</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Chloroxylenol\">Chloroxylenol</a>.</p><h4>References</h4><ol><li><p>Dorantes A et al. (1992). Pharmacokinetic and metabolic disposition of p-chloro-m-xylenol (PCMX) in dogs. <i>Pharmaceutical research 9(5):677–682</i>. DOI:<a href=\"https://doi.org/10.1023/a:1015814513373\">10.1023/a:1015814513373</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/1608902\">1608902</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Dorantes_1992: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Chloroxylenol_Dorantes1992_reference;
