within Pharmacolibrary.Drugs.N_NervousSystem.N03A_Antiepileptics.N03AA02_Phenobarbital;
model Phenobarbital_Stoschus2025_reference
  parameter Real Cl_ref = 1.6333333333333333e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.00182 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Phenobarbital.M,
    adminMass = 0.0007,
    ka = 0.0007333333333333333,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>phenobarbital</td></tr><tr><td>ATC code:</td><td>N03AA02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Stoschus M et al. 2025</td></tr><tr><td>population:</td><td>critically ill patients with refractory and superrefractory status epilepticus</td></tr><tr><td>measured compound:</td><td>phenobarbital</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_phenobarbital/Phenobarbital_Stoschus2025_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Cl</td><td>1.4</td><td>mL/kg/min</td><td><small>CL</small></td></tr><tr><td>Vd</td><td>1.82</td><td>L</td><td><small>V</small></td></tr><tr><td>absorption rate constant (Ka)</td><td>2.64</td><td>h−1</td><td><small>kabs</small></td></tr></table><h4>About phenobarbital</h4><p>Phenobarbital is a barbiturate anticonvulsant used to treat epilepsy and seizures, including status epilepticus and neonatal seizures, and has also been used for sleep problems and anxiety. It remains in use, is listed as an essential medicine by the WHO, and is approved, though today it is used relatively sparingly for epilepsy.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q407241\">Wikidata Q407241</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Phenobarbital\">Phenobarbital</a>.</p><h4>References</h4><ol><li><p>Stoschus M et al. (2025). Optimizing phenobarbital dosing in critically ill patients with refractory and superrefractory status epilepticus using a population pharmacokinetic model. <i>Epilepsia 66(10):3757–3768</i>. DOI:<a href=\"https://doi.org/10.1111/epi.18517\">10.1111/epi.18517</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/40569218\">40569218</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Stoschus_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Phenobarbital_Stoschus2025_reference;
