within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01A_AlkylatingAgents.L01AD01_Carmustine;
model Carmustine_Russo1981_reference
  parameter Real Cl_ref = 1.948333333333333e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.1813 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Carmustine.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>carmustine</td></tr><tr><td>ATC code:</td><td>L01AD01</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Russo R et al. 1981</td></tr><tr><td>population:</td><td>patients with lung cancer</td></tr><tr><td>measured compound:</td><td>BCNU</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_carmustine/Carmustine_Russo1981_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>half-life of BCNU added to plasma in vitro</td><td>1413</td><td>mins</td><td><small>t1/2z</small></td></tr><tr><td>Mean distribution volume</td><td>2.59</td><td>liters/kg</td><td><small>V</small></td></tr><tr><td>plasma clearance</td><td>16.7</td><td>ml/min/kg</td><td><small>CL</small></td></tr></table><h4>About carmustine</h4><p>Carmustine is an alkylating anticancer drug used to treat cancers such as Hodgkin disease and non-Hodgkin lymphoma. It remains an approved medicine, with an authorised product in the European Union, and carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q415869\">Wikidata Q415869</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Carmustine\">Carmustine</a>.</p><h4>References</h4><ol><li><p>Russo R et al. (1981). Differential pulse polarographic determination of BCNU pharmacokinetics in patients with lung cancer. <i>Cancer treatment reports 65(7-8):555–562</i>. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/7248980\">7248980</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Russo_1981: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Carmustine_Russo1981_reference;
