within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09C_AngiotensinIiReceptorBlockersArbsPlain.C09CA08_OlmesartanMedoxomil;
model Olmesartan_Kodati2017_reference
  parameter Real Cl_ref = 8.768055555555556e-08 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0445162 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.OlmesartanMedoxomil.M,
    adminMass = 0.0001,
    ka = 0.0005555555555555556,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>olmesartan</td></tr><tr><td>ATC code:</td><td>C09CA08</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Kodati D et al. 2017</td></tr><tr><td>population:</td><td>Indian patients with hypertension</td></tr><tr><td>measured compound:</td><td>olmesartan</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_olmesartan/Olmesartan_Kodati2017_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F</td><td>0.31565</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>V/F</td><td>44.5162</td><td>L</td><td><small>V/F</small></td></tr><tr><td>ka</td><td>2.0</td><td>h−1</td><td><small>kabs</small></td></tr></table><h4>About olmesartan</h4><p>Olmesartan is an angiotensin II receptor blocker used to treat high blood pressure (arterial hypertension) and congestive heart failure. It is an approved medicine, available alone and in combination products with diuretics or calcium channel blockers.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q421156\">Wikidata Q421156</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.OlmesartanMedoxomil\">OlmesartanMedoxomil</a>.</p><h4>References</h4><ol><li><p>Kodati D et al. (2017). Population Pharmacokinetic Modeling of Olmesartan, the Active Metabolite of Olmesartan Medoxomil, in Patients with Hypertension. <i>European journal of drug metabolism and pharmacokinetics 42(4):573–581</i>. DOI:<a href=\"https://doi.org/10.1007/s13318-016-0371-0\">10.1007/s13318-016-0371-0</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27535556\">27535556</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Kodati_2017: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 1814400, Tolerance = 1e-9, Interval = 1));
end Olmesartan_Kodati2017_reference;
