within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01C_PlantAlkaloidsAndOtherNaturalProducts.L01CA01_Vinblastine;
model Vinblastine_Zhou1990_estimated_parameters_vc_l_h_kg
  parameter Real Cl_ref = 3.88888888888889e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 4.9 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Vinblastine.M,
    adminMass = 7e-06
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>vinblastine</td></tr><tr><td>ATC code:</td><td>L01CA01</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Zhou XJ et al. 1990</td></tr><tr><td>population:</td><td>rats</td></tr><tr><td>measured compound:</td><td>vinblastine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_vinblastine/Vinblastine_Zhou1990_estimated_parameters_vc_l_h_kg\">pharmacolibrary-docs</a></td></tr></table><h4>About vinblastine</h4><p>Vinblastine, a Vinca alkaloid, is a cancer medicine used against tumours such as Hodgkin's lymphoma, breast, testicular and kidney cancer, Kaposi's sarcoma, and also certain blood and immune disorders. It remains an approved medicine and is included on the WHO list of essential medicines, so it is widely used in cancer treatment worldwide.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q282629\">Wikidata Q282629</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Vinblastine\">Vinblastine</a>.</p><h4>References</h4><ol><li><p>Zhou XJ et al. (1990). In vivo and in vitro pharmacokinetics and metabolism of vincaalkaloids in rat. II. Vinblastine and vincristine. <i>European journal of drug metabolism and pharmacokinetics 15(4):323–332</i>. DOI:<a href=\"https://doi.org/10.1007/BF03190222\">10.1007/BF03190222</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/2088769\">2088769</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Zhou_1990: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 4838400, Tolerance = 1e-9, Interval = 1));
end Vinblastine_Zhou1990_estimated_parameters_vc_l_h_kg;
