within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis.J04AB04_Rifabutin;
model Rifabutin_Chang2023_PD_cfu_lung
  "linear exposure-response sweep — Chang_2023 :: CFU/lung (M. tuberculosis lung burden)"
  extends Pharmacolibrary.Interfaces.PartialExposureResponseSweep(
    E0 = 4.46,      // [log10 CFU/lung]
    Emax = 0, EC50 = 1,      // unused by a line
    exposure_per_s = 0.001);
  parameter Real slope = -0.09   "[wk−1]";
equation
  response = E0 + slope*exposure;
  annotation(experiment(StartTime = 0, StopTime = 1000, Interval = 2),
    Documentation(info = "<html><body><h4>Rifabutin_Chang2023_PD_cfu_lung</h4><p>The steady-state exposure-response curve of Chang YS et al., <i>bioRxiv : the preprint server for biology</i> 2023 (<a href=\"https://doi.org/10.1101/2023.04.12.536604\">doi:10.1101/2023.04.12.536604</a>) — M. tuberculosis lung burden [log10 CFU/lung] against rifabutin µg/mL — obtained by sweeping the driver instead of simulating a dose. Model family: linear.</p><h4>The parameters, in the paper's terms</h4><pre>  E0    =       4.46 log10 CFU/lung drug-free response (baseline) (Initial log10 CFU/lung, Q324)
  slope =      -0.09 wk−1     change in response per unit of exposure (knet, Q335)</pre><p>The algebra is <code>response = E0 + slope*exposure</code>; this model only supplies the numbers. The x axis is one µg/mL of rifabutin per second of simulated time (exposure is in kg/m3): there is no state, no dose and no kinetics — plot <code>response</code> against <code>exposure</code> (or <code>time</code>).</p><h4>What it reproduces</h4><pre>  exposure = 0         response 4.46   (drug-free)</pre></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Chang_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"));
end Rifabutin_Chang2023_PD_cfu_lung;
