within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01X_OtherAntibacterials.J01XB01_Colistin;
model Colistin_Ma2026_reference
  parameter Real Cl_ref = 4.611111111111111e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0101 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Colistin.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>colistin</td></tr><tr><td>ATC code:</td><td>J01XB01</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Ma Y et al. 2026</td></tr><tr><td>population:</td><td>critically ill patients with CRO infections</td></tr><tr><td>measured compound:</td><td>colistin sulfate</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_colistin/Colistin_Ma2026_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Typical values of clearance (CL)</td><td>1.66</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>volume of distribution (V)</td><td>10.1</td><td>L</td><td><small>V</small></td></tr></table><h4>About colistin</h4><p>Colistin is a polymyxin antibiotic used to treat serious infections caused by resistant Gram-negative bacteria, and also as an intestinal antiinfective for gut decontamination. It remains in clinical use but is generally reserved for hospital treatment of multidrug-resistant infections when other antibiotics are not suitable.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q418946\">Wikidata Q418946</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Colistin\">Colistin</a>.</p><h4>References</h4><ol><li><p>Ma Y et al. (2026). Optimizing Colistin Sulfate Dosing in Severe Infections: A Population Pharmacokinetic Model-Guided Approach. <i>Drug design, development and therapy 20:600942</i>. DOI:<a href=\"https://doi.org/10.2147/DDDT.S600942\">10.2147/DDDT.S600942</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/42325914\">42325914</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Ma_2026: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Colistin_Ma2026_reference;
