within Pharmacolibrary.Drugs.N_NervousSystem.N02A_Opioids.N02AX06_Tapentadol;
model Tapentadol_Watson2019_reference
  parameter Real Cl_ref = 4.722222222222223e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.685 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Tapentadol.M,
    adminMass = 7e-05,
    ka = 0.0005638888888888888,
    Tlag = 889.2
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>tapentadol</td></tr><tr><td>ATC code:</td><td>N02AX06</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Watson E et al. 2019</td></tr><tr><td>population:</td><td>pediatric patients with acute pain</td></tr><tr><td>measured compound:</td><td>tapentadol</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_tapentadol/Tapentadol_Watson2019_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F (L/h)</td><td>170</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>V/F (L)</td><td>685</td><td>L</td><td><small>V/F</small></td></tr><tr><td>Ka (h−1)</td><td>2.03</td><td>h−1</td><td><small>kabs</small></td></tr><tr><td>TLAG (h)</td><td>0.247</td><td>h</td><td><small>tlag</small></td></tr><tr><td>theta_q319_wt_power</td><td>0.638</td><td></td><td><small>equation variable</small></td></tr><tr><td>theta_q319_wt_power</td><td>0.847</td><td></td><td><small>equation variable</small></td></tr></table><h4>About tapentadol</h4><p>Tapentadol is an opioid painkiller used to treat moderate to severe pain, including pain associated with fibromyalgia. It is an approved medicine and is widely used as an analgesic, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q414463\">Wikidata Q414463</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Tapentadol\">Tapentadol</a>.</p><h4>References</h4><ol><li><p>Watson E et al. (2019). Population pharmacokinetic modeling to facilitate dose selection of tapentadol in the pediatric population. <i>Journal of pain research 12:2835–2850</i>. DOI:<a href=\"https://doi.org/10.2147/JPR.S208454\">10.2147/JPR.S208454</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31686902\">31686902</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Watson_2019: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Tapentadol_Watson2019_reference;
