within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B02B_VitaminKAndOtherHemostatics.B02BX05_Eltrombopag;
model Eltrombopag_Farrell2014_reference
  parameter Real Cl_ref = 4.194444444444445e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.00914 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Eltrombopag.M,
    adminMass = 5e-06,
    ka = 0.005611111111111111,
    Tlag = 0.0,
    k21 = 0.00025288526816021723
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>eltrombopag</td></tr><tr><td>ATC code:</td><td>B02BX05</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Farrell C et al. 2014</td></tr><tr><td>population:</td><td>healthy volunteers and subjects with chronic liver disease</td></tr><tr><td>measured compound:</td><td>eltrombopag</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_eltrombopag/Eltrombopag_Farrell2014_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F (l h -1 )</td><td>15.1</td><td>l h -1</td><td><small>CL/F</small></td></tr><tr><td>Vc/F (l)</td><td>9.14</td><td>l</td><td><small>V1/F</small></td></tr><tr><td>Vp/F (l)</td><td>9.82</td><td>l</td><td><small>V2/F</small></td></tr><tr><td>Q/F (l h -1 )</td><td>8.94</td><td>l h -1</td><td><small>Q/F</small></td></tr><tr><td>Ka1 (h -1 )</td><td>20.2</td><td>h -1</td><td><small>kabs</small></td></tr><tr><td>Ka2 (h -1 )</td><td>21.9</td><td>h -1</td><td><small>k21</small></td></tr><tr><td>MTIME (h)</td><td>1.28</td><td>h</td><td><small>MTT</small></td></tr></table><h4>About eltrombopag</h4><p>Eltrombopag is a medicine used to raise low platelet counts in conditions such as immune thrombocytopenic purpura and aplastic anemia. It is an approved drug authorised in the European Union, where it is used for these platelet disorders.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q411588\">Wikidata Q411588</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Eltrombopag\">Eltrombopag</a>.</p><h4>References</h4><ol><li><p>Farrell C et al. (2014). Population pharmacokinetic/pharmacodynamic modelling of eltrombopag in healthy volunteers and subjects with chronic liver disease. <i>British journal of clinical pharmacology 77(3):532–544</i>. DOI:<a href=\"https://doi.org/10.1111/bcp.12244\">10.1111/bcp.12244</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/24117976\">24117976</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Farrell_2014: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Eltrombopag_Farrell2014_reference;
