within Pharmacolibrary.Drugs.N_NervousSystem.N02C_AntimigrainePreparations.N02CD03_Fremanezumab;
model Fremanezumab_FiedlerKelly2019_reference
  parameter Real Cl_ref = 1.0439814814814816e-09 "Cl [m3/s]";
  parameter Real Vd_ref = 0.00188 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 7.5e-06
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>fremanezumab</td></tr><tr><td>ATC code:</td><td>N02CD03</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Fiedler-Kelly JB et al. 2019</td></tr><tr><td>population:</td><td>healthy subjects and patients with migraine</td></tr><tr><td>measured compound:</td><td>fremanezumab</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_fremanezumab/Fremanezumab_FiedlerKelly2019_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>fremanezumab central clearance</td><td>0.0902</td><td>L/d</td><td><small>CL</small></td></tr><tr><td>central distribution volume</td><td>1.88</td><td>L</td><td><small>V</small></td></tr><tr><td>Absolute bioavailability</td><td>0.658</td><td></td><td><small>Fab</small></td></tr></table><h4>About fremanezumab</h4><p>Fremanezumab is a monoclonal antibody used to prevent migraine, including migraine with and without aura. It is an approved CGRP-antagonist medicine authorised in the European Union for migraine prevention.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q39048381\">Wikidata Q39048381</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Fremanezumab\">Fremanezumab</a>.</p><h4>References</h4><ol><li><p>Fiedler-Kelly JB et al. (2019). Population pharmacokinetic modelling and simulation of fremanezumab in healthy subjects and patients with migraine. <i>British journal of clinical pharmacology 85(12):2721–2733</i>. DOI:<a href=\"https://doi.org/10.1111/bcp.14096\">10.1111/bcp.14096</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31418911\">31418911</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Fiedler-Kelly_2019: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 6652800, Tolerance = 1e-9, Interval = 1));
end Fremanezumab_FiedlerKelly2019_reference;
