within Pharmacolibrary.Drugs.C_CardiovascularSystem.C04A_PeripheralVasodilators.C04AE04_Dihydroergocristine;
model Dihydroergocristine_Grognet1992_reference
  parameter Real Cl_ref = 7.361111111111111e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 3.64 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Dihydroergocristine.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>dihydroergocristine</td></tr><tr><td>ATC code:</td><td>C04AE04</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Grognet JM et al. 1992</td></tr><tr><td>population:</td><td>rats</td></tr><tr><td>measured compound:</td><td>dihydroergocristine</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>t1/2</td><td>13.6</td><td>h</td><td><small>t1/2z</small></td></tr><tr><td>systemic clearance</td><td>2.65</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>52</td><td>l.kg-1</td><td><small>V</small></td></tr></table><h4>About dihydroergocristine</h4><p>Dihydroergocristine is a vasodilator ergot alkaloid used in the treatment of dementia. It is an approved drug, classified as a peripheral vasodilator, but does not appear to have centralised European Union authorisation.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q5276428\">Wikidata Q5276428</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Dihydroergocristine\">Dihydroergocristine</a>.</p><h4>References</h4><ol><li><p>Grognet JM et al. (1992). [The pharmacokinetics of dihydroergocristine after intravenous and oral administration in rats]. <i>Arzneimittel-Forschung 42(11A):1394–1396</i>. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/1492859\">1492859</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Grognet_1992: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 259200, Tolerance = 1e-9, Interval = 1));
end Dihydroergocristine_Grognet1992_reference;
