within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02K_OtherAntihypertensives.C02KX02_Ambrisentan;
model Ambrisentan_Okour2023_reference
  parameter Real Cl_ref = 3.25e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0123 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Ambrisentan.M,
    adminMass = 2.5e-06,
    ka = 0.0006833333333333333,
    Tlag = 1890.0,
    k12 = 1.0320686540198736e-05,
    k21 = 1.5614322809894768e-06
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>ambrisentan</td></tr><tr><td>ATC code:</td><td>C02KX02</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Okour M et al. 2023</td></tr><tr><td>population:</td><td>pediatric patients with pulmonary arterial hypertension</td></tr><tr><td>measured compound:</td><td>ambrisentan</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_ambrisentan/Ambrisentan_Okour2023_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F [L/hr]</td><td>1.17</td><td>L/hr</td><td><small>CL/F</small></td></tr><tr><td>Vc/F [L]</td><td>12.3</td><td>L</td><td><small>V1/F</small></td></tr><tr><td>Q/F [L/hr]</td><td>0.457</td><td>L/hr</td><td><small>Q/F</small></td></tr><tr><td>Vp/F [L]</td><td>81.3</td><td>L</td><td><small>V2/F</small></td></tr><tr><td>Ka [hr -1 ]</td><td>2.46</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>tlag [hr]</td><td>0.525</td><td>hr</td><td><small>tlag</small></td></tr><tr><td>theta_q319_body_weight</td><td>1</td><td></td><td><small>equation variable</small></td></tr></table><h4>About ambrisentan</h4><p>Ambrisentan is an antihypertensive drug used to treat pulmonary arterial hypertension. It is authorised in the European Union and is also used for related conditions such as portal and chronic pulmonary hypertension.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q410789\">Wikidata Q410789</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Ambrisentan\">Ambrisentan</a>.</p><h4>References</h4><ol><li><p>Okour M et al. (2023). Pediatric Population Pharmacokinetic Modeling and Exposure-Response Analysis of Ambrisentan in Pulmonary Arterial Hypertension and Comparison With Adult Data. <i>Journal of clinical pharmacology 63(5):593–603</i>. DOI:<a href=\"https://doi.org/10.1002/jcph.2199\">10.1002/jcph.2199</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36579617\">36579617</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Okour_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 136800, Tolerance = 1e-9, Interval = 1));
end Ambrisentan_Okour2023_reference;
