within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02K_OtherAntihypertensives.C02KX02_Ambrisentan;
model Ambrisentan_Hill2020_reference
  parameter Real Cl_ref = 2.7777777777777776e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0137 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Ambrisentan.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>ambrisentan</td></tr><tr><td>ATC code:</td><td>C02KX02</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Hill KD et al. 2020</td></tr><tr><td>population:</td><td>children after Fontan surgery</td></tr><tr><td>measured compound:</td><td>ambrisentan</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_ambrisentan/Ambrisentan_Hill2020_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>clearance</td><td>1</td><td>L/hr/70 kg</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>13.7</td><td>L/70 kg</td><td><small>V</small></td></tr></table><h4>About ambrisentan</h4><p>Ambrisentan is an antihypertensive drug used to treat pulmonary arterial hypertension. It is authorised in the European Union and is also used for related conditions such as portal and chronic pulmonary hypertension.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q410789\">Wikidata Q410789</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Ambrisentan\">Ambrisentan</a>.</p><h4>References</h4><ol><li><p>Hill KD et al. (2020). A Randomized, Controlled Pharmacokinetic and Pharmacodynamics Trial of Ambrisentan After Fontan Surgery. <i>Pediatric critical care medicine : a journal of the Society of Critical Care Medicine and the World Federation of Pediatric Intensive and Critical Care Societies 21(9):e795–e803</i>. DOI:<a href=\"https://doi.org/10.1097/PCC.0000000000002410\">10.1097/PCC.0000000000002410</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32639468\">32639468</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Hill_2020: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 172800, Tolerance = 1e-9, Interval = 1));
end Ambrisentan_Hill2020_reference;
