within Pharmacolibrary.Drugs.S_SensoryOrgans.S01A_Antiinfectives.S01AA21_Amikacin;
model Amikacin "Amikacin — default model: Amikacin"
  extends Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01G_AminoglycosideAntibacterials.J01GB06_Amikacin.Amikacin;
  annotation (Documentation(info = "<html><body><p>amikacin under ATC S01AA21: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01G_AminoglycosideAntibacterials.J01GB06_Amikacin\">J01GB06_Amikacin</a> (ATC J01GB06); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Amikacin;
