within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A11H_OtherPlainVitaminPreparations.A11HA05_Biotin;
model Biotin_Wang2001_reference
  parameter Real Cl_ref = 4.666666666666667e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.10850000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Biotin.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>biotin</td></tr><tr><td>ATC code:</td><td>A11HA05</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Wang KS et al. 2001</td></tr><tr><td>population:</td><td>Landrace-Cambrough pigs</td></tr><tr><td>measured compound:</td><td>biotin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_biotin/Biotin_Wang2001_reference\">pharmacolibrary-docs</a></td></tr></table><h4>About biotin</h4><p>Biotin, a B vitamin, is used as a vitamin supplement and to treat inherited metabolic disorders. It is widely available as an approved supplement and is also being studied for other uses.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q181354\">Wikidata Q181354</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Biotin\">Biotin</a>.</p><h4>References</h4><ol><li><p>Wang KS et al. (2001). The clearance and metabolism of biotin administered intravenously to pigs in tracer and physiologic amounts is much more rapid than previously appreciated. <i>The Journal of nutrition 131(4):1271–1278</i>. DOI:<a href=\"https://doi.org/10.1093/jn/131.4.1271\">10.1093/jn/131.4.1271</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/11285337\">11285337</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Wang_2001: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Biotin_Wang2001_reference;
