within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09C_AngiotensinIiReceptorBlockersArbsPlain.C09CA04_Irbesartan;
model Irbesartan_Karatza2020_reference
  parameter Real Cl_ref = 3.75e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.013800000000000002 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Irbesartan.M,
    adminMass = 0.00015,
    ka = 8.444444444444444e-05,
    Tlag = 0.0,
    k12 = 0.00035628019323671493,
    k21 = 5.7303807303807304e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>irbesartan</td></tr><tr><td>ATC code:</td><td>C09CA04</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Karatza E et al. 2020</td></tr><tr><td>measured compound:</td><td>irbesartan</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_irbesartan/Irbesartan_Karatza2020_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>ka</td><td>0.304</td><td>h-1</td><td><small>kabs</small></td></tr><tr><td>T</td><td>1.68</td><td>h</td><td><small>equation variable</small></td></tr><tr><td>V1/F</td><td>13.8</td><td>L</td><td><small>V1/F</small></td></tr><tr><td>V2/F</td><td>85.8</td><td>L</td><td><small>V2/F</small></td></tr><tr><td>CL/F</td><td>13.5</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>Q/F</td><td>17.7</td><td>L/h</td><td><small>Q/F</small></td></tr></table><h4>About irbesartan</h4><p>Irbesartan is an angiotensin II receptor blocker used to treat high blood pressure (arterial hypertension). It is an approved medicine, authorised in the European Union, and is available both alone and in combination products with diuretics or calcium channel blockers.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q947266\">Wikidata Q947266</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Irbesartan\">Irbesartan</a>.</p><h4>References</h4><ol><li><p>Karatza E et al. (2020). Delay differential equations for the description of Irbesartan pharmacokinetics: A population approach to model absorption complexities leading to dual peaks. <i>European journal of pharmaceutical sciences : official journal of the European Federation for Pharmaceutical Sciences 153:105498</i>. DOI:<a href=\"https://doi.org/10.1016/j.ejps.2020.105498\">10.1016/j.ejps.2020.105498</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32736091\">32736091</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Karatza_2020: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Irbesartan_Karatza2020_reference;
