within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03X_OtherDiuretics.C03XA01_Tolvaptan;
model Tolvaptan_Lanke2019_reference
  parameter Real Cl_ref = 3.7222222222222225e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.12 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Tolvaptan.M,
    adminMass = 1.5e-05,
    ka = 0.00037222222222222225,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>tolvaptan</td></tr><tr><td>ATC code:</td><td>C03XA01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Lanke S et al. 2019</td></tr><tr><td>population:</td><td>adults with autosomal dominant polycystic kidney disease</td></tr><tr><td>measured compound:</td><td>tolvaptan</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_tolvaptan/Tolvaptan_Lanke2019_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F (L/h)</td><td>13.4</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>Vd/F (L)</td><td>120</td><td>L</td><td><small>V/F</small></td></tr><tr><td>D1 (h)</td><td>0.78</td><td>h</td><td><small>D1</small></td></tr><tr><td>theta_q319_egfr_power</td><td>0.54</td><td></td><td><small>equation variable</small></td></tr><tr><td>theta_q319_wt_power</td><td>-0.35</td><td></td><td><small>equation variable</small></td></tr><tr><td>theta_q319_wt_power</td><td>0.44</td><td></td><td><small>equation variable</small></td></tr><tr><td>k a (h -1 )</td><td>1.34</td><td>h -1</td><td><small>kabs</small></td></tr></table><h4>About tolvaptan</h4><p>Tolvaptan is a vasopressin receptor antagonist used to treat low blood sodium (hyponatremia) linked to heart failure, cirrhosis, or inappropriate antidiuretic hormone secretion, and is also authorised for autosomal dominant polycystic kidney disease. It remains in use, with authorised products in the European Union, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q426132\">Wikidata Q426132</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Tolvaptan\">Tolvaptan</a>.</p><h4>References</h4><ol><li><p>Lanke S et al. (2019). Population Pharmacokinetic Analyses and Model Validation of Tolvaptan in Subjects With Autosomal Dominant Polycystic Kidney Disease. <i>Journal of clinical pharmacology 59(5):763–770</i>. DOI:<a href=\"https://doi.org/10.1002/jcph.1370\">10.1002/jcph.1370</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30618157\">30618157</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Lanke_2019: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 122400, Tolerance = 1e-9, Interval = 1));
end Tolvaptan_Lanke2019_reference;
