within Pharmacolibrary.Drugs.S_SensoryOrgans.S01E_AntiglaucomaPreparationsAndMiotics.S01ED05_Carteolol;
model Carteolol "Carteolol — default model: Carteolol"
  extends Pharmacolibrary.Drugs.C_CardiovascularSystem.C07A_BetaBlockingAgents.C07AA15_Carteolol.Carteolol;
  annotation (Documentation(info = "<html><body><p>carteolol under ATC S01ED05: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.C_CardiovascularSystem.C07A_BetaBlockingAgents.C07AA15_Carteolol\">C07AA15_Carteolol</a> (ATC C07AA15); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Carteolol;
