within Pharmacolibrary.Drugs.N_NervousSystem.N02C_AntimigrainePreparations.N02CD06_Rimegepant;
model Rimegepant_Comisar2025v2_reference
  parameter Real Cl_ref = 6.6944444444444455e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.114 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Rimegepant.M,
    adminMass = 3.75e-05,
    ka = 0.0010722222222222222,
    Tlag = 0.0,
    k12 = 9.600389863547757e-06,
    k21 = 2.3792270531400967e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>rimegepant</td></tr><tr><td>ATC code:</td><td>N02CD06</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Comisar CM et al. 2025</td></tr><tr><td>population:</td><td>adults</td></tr><tr><td>measured compound:</td><td>rimegepant</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_rimegepant/Rimegepant_Comisar2025v2_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>apparent clearance (CL/F)</td><td>24.1</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>apparent central volume of distribution (Vc/F)</td><td>114.0</td><td>L</td><td><small>V1/F</small></td></tr><tr><td>apparent inter-compartmental clearance (Q/F)</td><td>3.94</td><td>L/h</td><td><small>Q/F</small></td></tr><tr><td>apparent peripheral volume of distribution (Vp/F)</td><td>46.0</td><td>L</td><td><small>V2/F</small></td></tr><tr><td>absorption rate constant (ka)</td><td>3.86</td><td>h-1</td><td><small>kabs</small></td></tr><tr><td>transit absorption rate constant (ktr)</td><td>8.23</td><td>h-1</td><td><small>ktr</small></td></tr></table><h4>About rimegepant</h4><p>Rimegepant is a calcitonin gene-related peptide receptor antagonist used to treat acute migraine attacks in adults. It is an approved medicine and is authorised in the European Union for migraine.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q27272184\">Wikidata Q27272184</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Rimegepant\">Rimegepant</a>.</p><h4>References</h4><ol><li><p>Comisar CM et al. (2025). Population Pharmacokinetic Modeling of the Oral Calcitonin Gene-Related Peptide Receptor Antagonist Rimegepant in Adults. <i>CPT: pharmacometrics &amp; systems pharmacology 14(8):1332–1345</i>. DOI:<a href=\"https://doi.org/10.1002/psp4.70051\">10.1002/psp4.70051</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/40614133\">40614133</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Comisar_2025_2: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Rimegepant_Comisar2025v2_reference;
