within Pharmacolibrary.Drugs.N_NervousSystem.N02C_AntimigrainePreparations.N02CD06_Rimegepant;
model Rimegepant_Comisar2025_reference
  parameter Real Cl_ref = 7e-06 "Cl [m3/s]";
  parameter Real cov_fed_0 = 0 "fed covariate";
  parameter Real cov_formulation_1 = 0 "formulation covariate";
  parameter Real cov_body_weight_2 = 0 "body weight covariate";
  parameter Real cov_body_weight_3 = 0 "body weight covariate";
  parameter Real cov_hepatic_4 = 0 "hepatic covariate";
  parameter Real cov_hepatic_5 = 0 "hepatic covariate";
  parameter Real Vd_ref = 0.113 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref*(1 + (-0.331)*cov_fed_0)*(1 + (2.19)*cov_formulation_1)*(1 + (0.575)*cov_body_weight_2)*(1 + (1.18)*cov_body_weight_3)*(1 + (-0.41)*cov_hepatic_4)*(1 + (-0.203)*cov_hepatic_5),
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Rimegepant.M,
    adminMass = 1e-05,
    ka = 0.0008472222222222222,
    Tlag = 0.0,
    k12 = 1.0226155358898721e-05,
    k21 = 2.4691358024691357e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>rimegepant</td></tr><tr><td>ATC code:</td><td>N02CD06</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Comisar CM et al. 2025</td></tr><tr><td>population:</td><td>pediatric and adult patients with migraine</td></tr><tr><td>measured compound:</td><td>rimegepant</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_rimegepant/Rimegepant_Comisar2025_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F, L/h</td><td>25.2</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>V1/F, L</td><td>113</td><td>L</td><td><small>V1/F</small></td></tr><tr><td>V2/F, L</td><td>46.8</td><td>L</td><td><small>V2/F</small></td></tr><tr><td>Q/F, L/h</td><td>4.16</td><td>L/h</td><td><small>Q/F</small></td></tr><tr><td>k tr, 1/h</td><td>8.42</td><td>1/h</td><td><small>ktr</small></td></tr><tr><td>k a, 1/h</td><td>3.05</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>fed_on_f1</td><td>-0.331</td><td></td><td><small>equation variable</small></td></tr><tr><td>capsule_formulation_on_k_tr</td><td>2.19</td><td></td><td><small>equation variable</small></td></tr><tr><td>body_weight_effect_on_cl_f_and_q_f</td><td>0.575</td><td></td><td><small>equation variable</small></td></tr><tr><td>body_weight_effect_on_v1_f_and_v2_f</td><td>1.18</td><td></td><td><small>equation variable</small></td></tr><tr><td>theta_cl_f_hepatic</td><td>-0.410</td><td></td><td><small>equation variable</small></td></tr><tr><td>theta_q338_fed</td><td>-0.698</td><td></td><td><small>equation variable</small></td></tr><tr><td>theta_cl_f_hepatic</td><td>-0.203</td><td></td><td><small>equation variable</small></td></tr></table><h4>About rimegepant</h4><p>Rimegepant is a calcitonin gene-related peptide receptor antagonist used to treat acute migraine attacks in adults. It is an approved medicine and is authorised in the European Union for migraine.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q27272184\">Wikidata Q27272184</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Rimegepant\">Rimegepant</a>.</p><h4>References</h4><ol><li><p>Comisar CM et al. (2025). Exposure Matching Using Population Pharmacokinetic Modeling and Simulation to Support Rimegepant Dose Selection for Pediatric Patients With Migraine. <i>Clinical and translational science 18(10):e70360</i>. DOI:<a href=\"https://doi.org/10.1111/cts.70360\">10.1111/cts.70360</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/41105969\">41105969</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Comisar_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Rimegepant_Comisar2025_reference;
