within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01M_QuinoloneAntibacterials.J01MA12_Levofloxacin;
model Levofloxacin_Setiawan2022_median
  parameter Real Cl_ref = 2.5000000000000004e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0264 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Levofloxacin.M,
    adminMass = 0.00025,
    k12 = 0.0003493265993265993,
    k21 = 0.0003305455993628037
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>levofloxacin</td></tr><tr><td>ATC code:</td><td>J01MA12</td></tr><tr><td>model:</td><td>two compartments, IV dosing <small>(PK_2C)</small></td></tr><tr><td>source:</td><td>Setiawan E et al. 2022</td></tr><tr><td>population:</td><td>hospitalized adult patients</td></tr><tr><td>measured compound:</td><td>levofloxacin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_levofloxacin/Levofloxacin_Setiawan2022_median\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Vc (L)</td><td>26.4</td><td>L</td><td><small>V1</small></td></tr><tr><td>CL (L/h)</td><td>0.90</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Q (L/h)</td><td>33.2</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>Vp (L)</td><td>27.9</td><td>L</td><td><small>V2</small></td></tr></table><h4>About levofloxacin</h4><p>Levofloxacin is a fluoroquinolone antibiotic used to treat a range of bacterial infections, including pneumonia, sinusitis, urinary tract infections, and tuberculosis, and it is also used to help eradicate Helicobacter pylori. It is widely used and appears on the WHO essential medicines list; in the European Union an authorised product exists mainly for respiratory tract infections and cystic fibrosis, and it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q424193\">Wikidata Q424193</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Levofloxacin\">Levofloxacin</a>.</p><h4>References</h4><ol><li><p>Setiawan E et al. (2022). Population pharmacokinetics and dose optimization of intravenous levofloxacin in hospitalized adult patients. <i>Scientific reports 12(1):8930</i>. DOI:<a href=\"https://doi.org/10.1038/s41598-022-12627-1\">10.1038/s41598-022-12627-1</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35624222\">35624222</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Setiawan_2022: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 432000, Tolerance = 1e-9, Interval = 1));
end Levofloxacin_Setiawan2022_median;
