within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins.A10BK02_Canagliflozin;
model Canagliflozin_Yao2023_reference
  parameter Real Cl_ref = 1.1805555555555556e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.030600000000000002 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Canagliflozin.M,
    adminMass = 1e-05,
    k12 = 1.2436456063907045e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>canagliflozin</td></tr><tr><td>ATC code:</td><td>A10BK02</td></tr><tr><td>model:</td><td>two compartments, IV dosing <small>(PK_2C)</small></td></tr><tr><td>source:</td><td>Yao X et al. 2023</td></tr><tr><td>population:</td><td>healthy subjects and patients with T2DM</td></tr><tr><td>measured compound:</td><td>canagliflozin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_canagliflozin/Canagliflozin_Yao2023_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL (L/h)</td><td>4.25</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Vc (L)</td><td>30.6</td><td>L</td><td><small>V1</small></td></tr><tr><td>CLD</td><td>1.37</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>VT (L)</td><td>28.3</td><td>L</td><td><small>V</small></td></tr><tr><td>K t (h−1)</td><td>4.13</td><td>h−1</td><td><small>kel</small></td></tr><tr><td>Fed</td><td>0.254</td><td></td><td><small>Fab</small></td></tr></table><h4>About canagliflozin</h4><p>Canagliflozin is an anti-diabetic medicine used to treat type 2 diabetes mellitus. It is an approved SGLT2 inhibitor and is authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q5030940\">Wikidata Q5030940</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Canagliflozin\">Canagliflozin</a>.</p><h4>References</h4><ol><li><p>Yao X et al. (2023). A model-based meta analysis study of sodium glucose co-transporter-2 inhibitors. <i>CPT: pharmacometrics &amp; systems pharmacology 12(4):487–499</i>. DOI:<a href=\"https://doi.org/10.1002/psp4.12934\">10.1002/psp4.12934</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36890732\">36890732</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Yao_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 90000, Tolerance = 1e-9, Interval = 1));
end Canagliflozin_Yao2023_reference;
