within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01G_AminoglycosideAntibacterials.J01GB03_Gentamicin;
model Gentamicin_Crcek2019_reference
  parameter Real Cl_ref = 6.805555555555556e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.037380000000000004 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Gentamicin.M,
    adminMass = 0.00024
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>gentamicin</td></tr><tr><td>ATC code:</td><td>J01GB03</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Crcek M et al. 2019</td></tr><tr><td>population:</td><td>paediatric patients</td></tr><tr><td>measured compound:</td><td>gentamicin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_gentamicin/Gentamicin_Crcek2019_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Cl (L/h/kg)</td><td>0.035</td><td>L/h/kg</td><td><small>CL</small></td></tr><tr><td>Vd (L/kg)</td><td>0.534</td><td>L/kg</td><td><small>V</small></td></tr></table><h4>About gentamicin</h4><p>Gentamicin is an aminoglycoside antibiotic used to treat serious bacterial infections such as sepsis, urinary tract infections, endocarditis, and gram-negative or staphylococcal infections. It is widely used in human medicine, given systemically as well as topically on skin, eyes, and ears, and is also approved for veterinary use.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q422482\">Wikidata Q422482</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Gentamicin\">Gentamicin</a>.</p><h4>References</h4><ol><li><p>Crcek M et al. (2019). A review of population pharmacokinetic models of gentamicin in paediatric patients. <i>Journal of clinical pharmacy and therapeutics 44(5):659–674</i>. DOI:<a href=\"https://doi.org/10.1111/jcpt.12850\">10.1111/jcpt.12850</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31102287\">31102287</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Crcek_2019: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 259200, Tolerance = 1e-9, Interval = 1));
end Gentamicin_Crcek2019_reference;
