within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07A_BetaBlockingAgents.C07AA07_Sotalol;
model Sotalol_Yellepeddi2025_reference
  parameter Real Cl_ref = 2.638888888888889e-06 "Cl [m3/s]";
  parameter Real cov_crcl_0 = 0 "crcl covariate";
  parameter Real Vd_ref = 0.038200000000000005 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 1.6,
    Cl = Cl_ref*(1 + (0.7)*cov_crcl_0),
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Sotalol.M,
    adminMass = 6e-05,
    ka = 5.555555555555556e-05,
    Tlag = 0.0,
    k12 = 0.0005184700407213496,
    k21 = 0.000222284574136426
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>sotalol</td></tr><tr><td>ATC code:</td><td>C07AA07</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Yellepeddi VK et al. 2025</td></tr><tr><td>population:</td><td>adults with atrial arrhythmias</td></tr><tr><td>measured compound:</td><td>sotalol</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_sotalol/Sotalol_Yellepeddi2025_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Clearance (CL), L/h</td><td>9.5</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Intercompartmental clearance (Q), L/h</td><td>71.3</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>Central Volume of distribution (Vc), L</td><td>38.2</td><td>L</td><td><small>V1</small></td></tr><tr><td>Peripheral volume of distribution (Vp), L</td><td>89.1</td><td>L</td><td><small>V2</small></td></tr><tr><td>Absorption rate constant (Ka), h−1</td><td>0.2</td><td>h−1</td><td><small>kabs</small></td></tr><tr><td>Oral bioavailability relative to IV (Foral)</td><td>1.6</td><td>Foral</td><td><small>Frel</small></td></tr><tr><td>theta_cl_crcl</td><td>0.7</td><td></td><td><small>equation variable</small></td></tr></table><h4>About sotalol</h4><p>Sotalol is a non-selective beta blocker with additional antiarrhythmic activity, used to treat heart rhythm problems such as atrial fibrillation, ventricular fibrillation, and supraventricular tachycardia. It is an approved medicine that remains in use, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q413591\">Wikidata Q413591</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Sotalol\">Sotalol</a>.</p><h4>References</h4><ol><li><p>Yellepeddi VK et al. (2025). Population Pharmacokinetics and Pharmacodynamics of Sotalol Following Expedited Intravenous Loading in Patients With Atrial Arrhythmias. <i>CPT: pharmacometrics &amp; systems pharmacology 14(4):658–667</i>. DOI:<a href=\"https://doi.org/10.1002/psp4.13302\">10.1002/psp4.13302</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39749676\">39749676</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Yellepeddi_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 104400, Tolerance = 1e-9, Interval = 1));
end Sotalol_Yellepeddi2025_reference;
