// GENERATED by pk_knowledge_scripts.export.modelica_pgx — DO NOT EDIT BY HAND.
// Source: CPIC API (api.cpicpgx.org), scoped to the 41 gene(s) with a ClinPGx prescribing guideline, generated 2026-09-02.
// Regenerate with: python -m pk_knowledge_scripts.export.modelica_pgx

within Pharmacolibrary.Pharmacogenomics;

package Diplotypes "a subject's alleles, one record per gene — set `allele`"
  extends Modelica.Icons.Package;
  record ABCG2 extends PGx.Diplotype(redeclare parameter Genes.ABCG2 gene); end ABCG2;
  record CYP2C19 extends PGx.Diplotype(redeclare parameter Genes.CYP2C19 gene); end CYP2C19;
  record CYP2C9 extends PGx.Diplotype(redeclare parameter Genes.CYP2C9 gene); end CYP2C9;
  record CYP2D6 extends PGx.Diplotype(redeclare parameter Genes.CYP2D6 gene); end CYP2D6;
  record CYP3A5 extends PGx.Diplotype(redeclare parameter Genes.CYP3A5 gene); end CYP3A5;
  record DPYD extends PGx.Diplotype(redeclare parameter Genes.DPYD gene); end DPYD;
  record NAT2 extends PGx.Diplotype(redeclare parameter Genes.NAT2 gene); end NAT2;
  record NUDT15 extends PGx.Diplotype(redeclare parameter Genes.NUDT15 gene); end NUDT15;
  record SLCO1B1 extends PGx.Diplotype(redeclare parameter Genes.SLCO1B1 gene); end SLCO1B1;
  record TPMT extends PGx.Diplotype(redeclare parameter Genes.TPMT gene); end TPMT;
  record UGT1A1 extends PGx.Diplotype(redeclare parameter Genes.UGT1A1 gene); end UGT1A1;
end Diplotypes;
