// GENERATED by pk_knowledge_scripts.export.modelica_pgx — DO NOT EDIT BY HAND.
// Source: CPIC API (api.cpicpgx.org), scoped to the 41 gene(s) with a ClinPGx prescribing guideline, generated 2026-09-02.
// Regenerate with: python -m pk_knowledge_scripts.export.modelica_pgx

within Pharmacolibrary.Pharmacogenomics;

package Genes "allele -> phenotype knowledge, one record per gene"
  extends Modelica.Icons.Package;

  record ABCG2
    // CPIC lookupmethod PHENOTYPE; the fitted bands reproduce 100.0% of
    // the 3 CPIC diplotypes that map onto MetabolizerStatus.
    extends PGx.Gene(
      symbol        = "ABCG2",
      allele        = {"rs2231142 reference (G)", "rs2231142 variant (T)"},
      activityScore = {1, 0.5},
      poorMax = 1, intermediateMax = 1.5, normalMax = 2, rapidMax = 2);
  end ABCG2;

  record CYP2C19
    // CPIC lookupmethod PHENOTYPE; the fitted bands reproduce 100.0% of
    // the 210 CPIC diplotypes that map onto MetabolizerStatus.
    // 23 allele(s) left out: CPIC gives them no scoreable function.
    extends PGx.Gene(
      symbol        = "CYP2C19",
      allele        = {"*1", "*10", "*11", "*13", "*15", "*16", "*17", "*18", "*19", "*2", "*22", "*24", "*25", "*26", "*28", "*3", "*35", "*36", "*37", "*38", "*4", "*5", "*6", "*7", "*8", "*9"},
      activityScore = {1, 0.5, 1, 1, 1, 0.5, 1.5, 1, 0.5, 0, 0, 0, 0.5, 0.5, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0.5},
      poorMax = 0, intermediateMax = 1.5, normalMax = 2, rapidMax = 2.5);
  end CYP2C19;

  record CYP2C9
    // CPIC lookupmethod ACTIVITY_SCORE; the fitted bands reproduce 100.0% of
    // the 666 CPIC diplotypes that map onto MetabolizerStatus.
    // 58 allele(s) left out: CPIC gives them no scoreable function.
    extends PGx.Gene(
      symbol        = "CYP2C9",
      allele        = {"*1", "*11", "*12", "*13", "*14", "*15", "*16", "*2", "*23", "*24", "*25", "*26", "*28", "*29", "*3", "*30", "*31", "*33", "*35", "*37", "*38", "*39", "*4", "*42", "*43", "*44", "*45", "*46", "*5", "*50", "*52", "*55", "*6", "*61", "*8", "*9"},
      activityScore = {1, 0.5, 0.5, 0, 0.5, 0, 0.5, 0.5, 0.5, 0, 0, 0.5, 0.5, 0.5, 0, 0.5, 0.5, 0, 0, 0.5, 0.5, 0, 0.5, 0, 0, 0.5, 0, 0.5, 0.5, 0.5, 0, 0.5, 0, 0.5, 0.5, 1},
      poorMax = 0.5, intermediateMax = 1.5, normalMax = 2, rapidMax = 2);
  end CYP2C9;

  record CYP2D6
    // CPIC lookupmethod ACTIVITY_SCORE; the fitted bands reproduce 96.9% of
    // the 4753 CPIC diplotypes that map onto MetabolizerStatus.
    // 111 allele(s) left out: CPIC gives them no scoreable function.
    extends PGx.Gene(
      symbol        = "CYP2D6",
      allele        = {"*1", "*10", "*100", "*101", "*109", "*10x2", "*11", "*114", "*119", "*12", "*120", "*124", "*129", "*13", "*13+*1", "*13+*1x2", "*13+*2", "*13+*68x2+*4", "*132", "*14", "*143", "*144", "*15", "*156", "*161", "*17", "*17x2", "*18", "*19", "*1x2", "*1x≥3", "*2", "*20", "*21", "*27", "*27x2", "*29", "*29x2", "*2x2", "*2x≥3", "*3", "*31", "*32", "*33", "*34", "*35", "*35x2", "*36", "*36+*10", "*36+*10x2", "*36x2", "*36x2+*10", "*36x2+*10x2", "*38", "*39", "*3x2", "*4", "*40", "*41", "*41x2", "*41x3", "*42", "*44", "*45", "*45x2", "*46", "*47", "*48", "*49", "*4x2", "*4x≥3", "*5", "*50", "*51", "*52", "*53", "*54", "*55", "*56", "*59", "*6", "*60", "*62", "*68", "*68+*2", "*68+*4", "*69", "*6x2", "*7", "*8", "*81", "*9", "*91", "*92", "*96", "*99", "*9x2"},
      activityScore = {1, 0.25, 0, 0, 0.25, 0.5, 0, 0, 0.25, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0.25, 0.5, 0, 0, 0, 0, 0, 0.5, 1, 0, 0, 2, 1.5, 1, 0, 0, 1, 2, 0.5, 1, 2, 1.5, 0, 0, 0.25, 1, 1, 1, 2, 0, 0.25, 0.5, 0, 0.25, 0.5, 0, 1, 0, 0, 0, 0.25, 0.5, 0.75, 0, 0, 1, 2, 1, 0, 1, 0.5, 0, 0, 0, 0.5, 0, 0.25, 1, 0.5, 0.5, 0, 0.5, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.25, 0.25, 0, 0, 0, 0.5},
      poorMax = 0, intermediateMax = 1, normalMax = 2.25, rapidMax = 2.25);
  end CYP2D6;

  record CYP3A5
    // CPIC lookupmethod PHENOTYPE; the fitted bands reproduce 100.0% of
    // the 10 CPIC diplotypes that map onto MetabolizerStatus.
    // 4 allele(s) left out: CPIC gives them no scoreable function.
    extends PGx.Gene(
      symbol        = "CYP3A5",
      allele        = {"*1", "*3", "*6", "*7"},
      activityScore = {1, 0, 0, 0},
      poorMax = 0, intermediateMax = 1, normalMax = 2, rapidMax = 2);
  end CYP3A5;

  record DPYD
    // CPIC lookupmethod ACTIVITY_SCORE; the fitted bands reproduce 100.0% of
    // the 3570 CPIC diplotypes that map onto MetabolizerStatus.
    extends PGx.Gene(
      symbol        = "DPYD",
      allele        = {"Reference", "c.1003G>T (*11)", "c.1024G>A", "c.1057C>T", "c.1108A>G", "c.1129-5923C>G", "c.1129-5923C>G, c.1236G>A (HapB3)", "c.1156G>T (*12)", "c.1180C>T", "c.1181G>T", "c.1218G>A", "c.1260T>A", "c.1278G>T", "c.1294G>A", "c.1314T>G", "c.1349C>T", "c.1358C>G", "c.1371C>T", "c.1403C>A", "c.1475C>T", "c.1484A>G", "c.1519G>A", "c.1543G>A", "c.1577C>G", "c.1601G>A (*4)", "c.1615G>A", "c.1627A>G (*5)", "c.1679T>G (*13)", "c.1682G>T", "c.1774C>T", "c.1775G>A", "c.1777G>A", "c.1796T>C", "c.1896T>C", "c.1898delC (*3)", "c.1905+1G>A (*2A)", "c.1905C>G", "c.1906A>C", "c.1990G>T", "c.2021G>A", "c.2161G>A", "c.2186C>T", "c.2194G>A (*6)", "c.2195T>G", "c.2279C>T", "c.2303C>A", "c.2336C>A", "c.2482G>A", "c.2582A>G", "c.2623A>C", "c.2639G>T", "c.2656C>T", "c.2657G>A (*9B)", "c.2846A>T", "c.2872A>G", "c.2915A>G", "c.2921A>T", "c.2933A>G", "c.295_298delTCAT (*7)", "c.2977C>T", "c.2978T>G", "c.2983G>T (*10)", "c.3049G>A", "c.3061G>C", "c.3067C>A", "c.313G>A", "c.343A>G", "c.451A>G", "c.46C>G", "c.496A>G", "c.498G>A", "c.525G>A", "c.557A>G", "c.601A>C", "c.61C>T", "c.62G>A", "c.632A>G", "c.703C>T (*8)", "c.775A>G", "c.85T>C (*9A)", "c.868A>G", "c.929T>C", "c.934C>T", "c.967G>A"},
      activityScore = {1, 1, 0, 0, 1, 0.5, 0.5, 0, 1, 1, 1, 1, 1, 1, 0.5, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0.5, 1, 1, 1, 1, 1, 0, 1, 1, 0.5, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0, 0, 1, 0, 0, 1, 1, 0.5, 1, 1, 1},
      poorMax = 0.5, intermediateMax = 1.5, normalMax = 2, rapidMax = 2);
  end DPYD;

  record NAT2
    // CPIC lookupmethod PHENOTYPE; the fitted bands reproduce 100.0% of
    // the 903 CPIC diplotypes that map onto MetabolizerStatus.
    // 17 allele(s) left out: CPIC gives them no scoreable function.
    extends PGx.Gene(
      symbol        = "NAT2",
      allele        = {"*1", "*14", "*15", "*16", "*19", "*29", "*30", "*31", "*32", "*33", "*34", "*35", "*36", "*37", "*38", "*39", "*4", "*40", "*46", "*47", "*48", "*49", "*5", "*50", "*52", "*53", "*56", "*58", "*59", "*6", "*62", "*63", "*64", "*66", "*67", "*68", "*69", "*7", "*70", "*72", "*73", "*75"},
      activityScore = {1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5},
      poorMax = 1, intermediateMax = 2, normalMax = 2, rapidMax = 3);
  end NAT2;

  record NUDT15
    // CPIC lookupmethod PHENOTYPE; the fitted bands reproduce 100.0% of
    // the 120 CPIC diplotypes that map onto MetabolizerStatus.
    // 8 allele(s) left out: CPIC gives them no scoreable function.
    extends PGx.Gene(
      symbol        = "NUDT15",
      allele        = {"*1", "*10", "*13", "*14", "*17", "*18", "*19", "*2", "*3", "*4", "*5", "*6", "*7", "*8", "*9"},
      activityScore = {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5, 0, 0, 0.5, 0},
      poorMax = 0.5, intermediateMax = 1, normalMax = 2, rapidMax = 2);
  end NUDT15;

  record SLCO1B1
    // CPIC lookupmethod PHENOTYPE; the fitted bands reproduce 100.0% of
    // the 120 CPIC diplotypes that map onto MetabolizerStatus.
    // 32 allele(s) left out: CPIC gives them no scoreable function.
    extends PGx.Gene(
      symbol        = "SLCO1B1",
      allele        = {"*1", "*14", "*15", "*20", "*23", "*31", "*37", "*39", "*41", "*45", "*47", "*48", "*49", "*5", "*9"},
      activityScore = {1, 1.5, 0, 1.5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0},
      poorMax = 0, intermediateMax = 1.5, normalMax = 2.5, rapidMax = 3);
  end SLCO1B1;

  record TPMT
    // CPIC lookupmethod PHENOTYPE; the fitted bands reproduce 100.0% of
    // the 820 CPIC diplotypes that map onto MetabolizerStatus.
    // 9 allele(s) left out: CPIC gives them no scoreable function.
    extends PGx.Gene(
      symbol        = "TPMT",
      allele        = {"*1", "*10", "*11", "*13", "*14", "*15", "*16", "*17", "*18", "*2", "*20", "*21", "*22", "*23", "*25", "*26", "*27", "*28", "*29", "*31", "*33", "*34", "*37", "*38", "*39", "*3A", "*3B", "*3C", "*4", "*41", "*42", "*43", "*44", "*45", "*46", "*47", "*5", "*6", "*7", "*8"},
      activityScore = {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5},
      poorMax = 0, intermediateMax = 1, normalMax = 2, rapidMax = 2);
  end TPMT;

  record UGT1A1
    // CPIC lookupmethod PHENOTYPE; the fitted bands reproduce 97.2% of
    // the 36 CPIC diplotypes that map onto MetabolizerStatus.
    // 1 allele(s) left out: CPIC gives them no scoreable function.
    extends PGx.Gene(
      symbol        = "UGT1A1",
      allele        = {"*1", "*27", "*28", "*36", "*37", "*6", "*80+*28", "*80+*37"},
      activityScore = {1, 0.5, 0.5, 1.5, 0.5, 0.5, 0.5, 0.5},
      poorMax = 1, intermediateMax = 2, normalMax = 3, rapidMax = 3);
  end UGT1A1;

end Genes;
