// GENERATED by pk_knowledge_scripts.export.modelica_pgx — DO NOT EDIT BY HAND.
// Source: CPIC API (api.cpicpgx.org), scoped to the 41 gene(s) with a ClinPGx prescribing guideline, generated 2026-09-02.
// Regenerate with: python -m pk_knowledge_scripts.export.modelica_pgx

within Pharmacolibrary.Pharmacogenomics;

package RiskGenes "carriage genes — CPIC assigns these by ALLELE STATUS"
  extends Modelica.Icons.Package;

  record HLA_A
    // Carriage, not activity: see PGx.RiskGene for why this is a Boolean
    // and not a factor on any PK or PD parameter.
    extends PGx.RiskGene(
      symbol     = "HLA-A",
      riskAllele = {"*31:01"},
      outcome    = "adverse reaction risk with carbamazepine, oxcarbazepine, tebentafusp");
  end HLA_A;

  record HLA_B
    // Carriage, not activity: see PGx.RiskGene for why this is a Boolean
    // and not a factor on any PK or PD parameter.
    extends PGx.RiskGene(
      symbol     = "HLA-B",
      riskAllele = {"*15:02", "*57:01", "*58:01"},
      outcome    = "adverse reaction risk with abacavir, allopurinol, carbamazepine, flucloxacillin, fosphenytoin, lamotrigine and 3 more");
  end HLA_B;

end RiskGenes;
