within Pharmacolibrary.Drugs.N_NervousSystem.N05C_HypnoticsAndSedatives.N05CM05_Scopolamine;
model Scopolamine_LiemMoolenaar2011_PD_vas_feeling_high
  "linear exposure-response sweep — Liem-Moolenaar_2011 :: VAS feeling high (VAS feeling high)"
  extends Pharmacolibrary.Interfaces.PartialExposureResponseSweep(
    E0 = 0.328,      // [log mm]
    Emax = 0, EC50 = 1,      // unused by a line
    exposure_per_s = 1e-09);
  parameter Real slope = 0.00313   "[log mm (pg ml-1)]";
equation
  response = E0 + slope*exposure;
  // family_inferred: the record's model family is effect_compartment; read from the parameters: a slope and no Emax — linear
  annotation(experiment(StartTime = 0, StopTime = 1000, Interval = 2),
    Documentation(info = "<html><body><h4>Scopolamine_LiemMoolenaar2011_PD_vas_feeling_high</h4><p>The steady-state exposure-response curve of Liem-Moolenaar M et al., <i>British journal of clinical pharmacology 71(6):886–898</i> 2011 (<a href=\"https://doi.org/10.1111/j.1365-2125.2011.03936.x\">doi:10.1111/j.1365-2125.2011.03936.x</a>) — VAS feeling high [log mm] against scopolamine pg ml-1 — obtained by sweeping the driver instead of simulating a dose. Model family: linear.</p><h4>The parameters, in the paper's terms</h4><pre>  E0    =      0.328 log mm   drug-free response (baseline) (Intercept, Q324)
  slope =    0.00313 log mm (pg ml-1) change in response per unit of exposure (Slope, Q335)</pre><p>The algebra is <code>response = E0 + slope*exposure</code>; this model only supplies the numbers. The x axis is one pg ml-1 of scopolamine per second of simulated time (exposure is in kg/m3): there is no state, no dose and no kinetics — plot <code>response</code> against <code>exposure</code> (or <code>time</code>).</p><h4>What it reproduces</h4><pre>  exposure = 0         response 0.328   (drug-free)</pre></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Liem-Moolenaar_2011: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"));
end Scopolamine_LiemMoolenaar2011_PD_vas_feeling_high;
