within Pharmacolibrary.Drugs.N_NervousSystem.N05C_HypnoticsAndSedatives.N05CM05_Scopolamine;
model Scopolamine_AlvarezJimenez2016_reference
  parameter Real Cl_ref = 1.8166666666666667e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.00266 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Scopolamine.M,
    adminMass = 9.000000000000001e-07
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>scopolamine</td></tr><tr><td>ATC code:</td><td>N05CM05</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Alvarez-Jimenez R et al. 2016</td></tr><tr><td>population:</td><td>healthy subjects</td></tr><tr><td>measured compound:</td><td>scopolamine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_scopolamine/Scopolamine_AlvarezJimenez2016_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>apparent central and peripheral volume of distribution</td><td>2.66</td><td>l</td><td><small>V</small></td></tr><tr><td>clearance</td><td>1.09</td><td>l min(-1)</td><td><small>CL</small></td></tr></table><h4>About scopolamine</h4><p>Scopolamine is an anticholinergic used for conditions such as motion sickness, iridocyclitis, and other disorders listed in its treatment records. It remains an approved medicine and is included on the WHO essential medicines list, used in ophthalmic, antiemetic, and sedative roles.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q337188\">Wikidata Q337188</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Scopolamine\">Scopolamine</a>.</p><h4>References</h4><ol><li><p>Alvarez-Jimenez R et al. (2016). Model-based exposure-response analysis to quantify age related differences in the response to scopolamine in healthy subjects. <i>British journal of clinical pharmacology 82(4):1011–1021</i>. DOI:<a href=\"https://doi.org/10.1111/bcp.13031\">10.1111/bcp.13031</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27273555\">27273555</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Alvarez-Jimenez_2016: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Scopolamine_AlvarezJimenez2016_reference;
