within Pharmacolibrary.Drugs.N_NervousSystem.N06A_Antidepressants.N06AX16_Venlafaxine;
model Venlafaxine_Wang2022_reference
  parameter Real Cl_ref = 6.138888888888889e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.23800000000000002 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Venlafaxine.M,
    adminMass = 5e-05,
    ka = 0.000175,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>venlafaxine</td></tr><tr><td>ATC code:</td><td>N06AX16</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Wang Z et al. 2022</td></tr><tr><td>population:</td><td>healthy volunteers and psychiatric patients</td></tr><tr><td>measured compound:</td><td>venlafaxine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_venlafaxine/Venlafaxine_Wang2022_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F, L/h</td><td>80.9</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>V/F, L</td><td>628</td><td>L</td><td><small>V/F</small></td></tr><tr><td>CLM/F, L/h</td><td>22.1</td><td>L/h</td><td><small>CLm/F</small></td></tr><tr><td>V M/F, L</td><td>238</td><td>L</td><td><small>Vm/F</small></td></tr><tr><td>Ka, 1/h</td><td>0.63</td><td>1/h</td><td><small>kabs</small></td></tr></table><h4>About venlafaxine</h4><p>Venlafaxine is an antidepressant (a serotonin–norepinephrine reuptake inhibitor) used for depression and anxiety-related conditions such as generalized anxiety disorder, social anxiety disorder, and panic-type anxiety disorders. It is an approved prescription medicine that is widely used, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q898407\">Wikidata Q898407</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Venlafaxine\">Venlafaxine</a>.</p><h4>References</h4><ol><li><p>Wang Z et al. (2022). Joint population pharmacokinetic modeling of venlafaxine and O-desmethyl venlafaxine in healthy volunteers and patients to evaluate the impact of morbidity and concomitant medication. <i>Frontiers in pharmacology 13:978202</i>. DOI:<a href=\"https://doi.org/10.3389/fphar.2022.978202\">10.3389/fphar.2022.978202</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36569310\">36569310</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Wang_2022: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 154800, Tolerance = 1e-9, Interval = 1));
end Venlafaxine_Wang2022_reference;
