within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis.A02BA03_Famotidine;
model Famotidine_Maish1998_reference
  parameter Real Cl_ref = 1.536111111111111e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0931 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Famotidine.M,
    adminMass = 4e-05,
    ka = 0.00026555555555555555,
    Tlag = 2682.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>famotidine</td></tr><tr><td>ATC code:</td><td>A02BA03</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Maish WA et al. 1998</td></tr><tr><td>population:</td><td>patients with cystic fibrosis</td></tr><tr><td>measured compound:</td><td>famotidine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_famotidine/Famotidine_Maish1998_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>elimination half-life (t1/2)</td><td>2.11</td><td>hours</td><td><small>t1/2z</small></td></tr><tr><td>total clearance (Cl)</td><td>0.79</td><td>L/kg/hr</td><td><small>CL</small></td></tr><tr><td>renal clearance</td><td>0.57</td><td>L/kg/hr</td><td><small>CLR</small></td></tr><tr><td>fraction eliminated unchanged in the urine</td><td>83</td><td>%</td><td><small>fe</small></td></tr><tr><td>apparent volume of distribution (Vdss)</td><td>1.33</td><td>L/kg</td><td><small>V/F</small></td></tr><tr><td>bioavailability</td><td>71</td><td>%</td><td><small>Fab</small></td></tr><tr><td>k a (1/h)</td><td>0.956</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>absorption lag time</td><td>0.745</td><td>h</td><td><small>tlag</small></td></tr></table><h4>About famotidine</h4><p>Famotidine is an H2-receptor antagonist used for acid-related conditions such as gastroesophageal reflux disease, heartburn, stomach and duodenal ulcers, Zollinger–Ellison syndrome, and urticaria. It is an approved medicine, widely available over the counter and on prescription for these common digestive complaints.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q411159\">Wikidata Q411159</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Famotidine\">Famotidine</a>.</p><h4>References</h4><ol><li><p>Maish WA et al. (1998). Pharmacokinetics of famotidine in patients with cystic fibrosis. <i>Journal of clinical pharmacology 38(11):1010–1016</i>. DOI:<a href=\"https://doi.org/10.1177/009127009803801104\">10.1177/009127009803801104</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/9824781\">9824781</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Maish_1998: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Famotidine_Maish1998_reference;
