within Pharmacolibrary.Drugs.N_NervousSystem.N06A_Antidepressants.N06AX05_Trazodone;
model Trazodone_Knych2017_reference
  parameter Real Cl_ref = 7.991666666666667e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.058800000000000005 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Trazodone.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>trazodone</td></tr><tr><td>ATC code:</td><td>N06AX05</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Knych HK et al. 2017</td></tr><tr><td>population:</td><td>healthy horses</td></tr><tr><td>measured compound:</td><td>trazodone</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_trazodone/Trazodone_Knych2017_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>total clearance of trazodone</td><td>6.85</td><td>mL/min/kg</td><td><small>CL</small></td></tr><tr><td>volume of distribution at steady state</td><td>1.06</td><td>L/kg</td><td><small>Vss</small></td></tr><tr><td>elimination half-life</td><td>8.58</td><td>hours</td><td><small>t1/2z</small></td></tr><tr><td>volume of distribution</td><td>0.84</td><td>L/kg</td><td><small>V</small></td></tr></table><h4>About trazodone</h4><p>Trazodone is an antidepressant used for depression, and also for conditions such as anxiety, insomnia, sleep-wake disorders, delirium and neurotic disorders. It is an approved medicine in widespread clinical use, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q411457\">Wikidata Q411457</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Trazodone\">Trazodone</a>.</p><h4>References</h4><ol><li><p>Knych HK et al. (2017). Pharmacokinetics and selected pharmacodynamics of trazodone following intravenous and oral administration to horses undergoing fitness training. <i>American journal of veterinary research 78(10):1182–1192</i>. DOI:<a href=\"https://doi.org/10.2460/ajvr.78.10.1182\">10.2460/ajvr.78.10.1182</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28945130\">28945130</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Knych_2017: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 154800, Tolerance = 1e-9, Interval = 1));
end Trazodone_Knych2017_reference;
