within Pharmacolibrary.Drugs.N_NervousSystem.N03A_Antiepileptics.N03AX18_Lacosamide;
model Lacosamide_Yu2026_reference
  parameter Real Cl_ref = 5.166666666666667e-07 "Cl [m3/s]";
  parameter Real cov_sex_0 = 0 "sex covariate";
  parameter Real cov_crcl_1 = 0 "crcl covariate";
  parameter Real Vd_ref = 0.041999999999999996 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref*(1 + (0.875)*cov_sex_0)*(1 + (0.311)*cov_crcl_1),
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Lacosamide.M,
    adminMass = 0.0003,
    ka = 0.0017972222222222222,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>lacosamide</td></tr><tr><td>ATC code:</td><td>N03AX18</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Yu L et al. 2026</td></tr><tr><td>population:</td><td>adult patients with epilepsy</td></tr><tr><td>measured compound:</td><td>lacosamide</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_lacosamide/Lacosamide_Yu2026_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F (L/h)</td><td>1.86</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>V (L/kg)</td><td>0.6</td><td>L/kg</td><td><small>V</small></td></tr><tr><td>Ka (h− 1)</td><td>6.47</td><td>h− 1</td><td><small>kabs</small></td></tr><tr><td>sex_on_cl_f</td><td>0.875</td><td></td><td><small>equation variable</small></td></tr><tr><td>crcl_on_cl_f</td><td>0.311</td><td></td><td><small>equation variable</small></td></tr></table><h4>About lacosamide</h4><p>Lacosamide is an anticonvulsant medicine used to treat epilepsy, including partial-onset seizures, and has also been studied for diabetic neuropathy. It is an approved drug with several products authorised in the European Union, where it is used for epilepsy.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q420077\">Wikidata Q420077</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Lacosamide\">Lacosamide</a>.</p><h4>References</h4><ol><li><p>Yu L et al. (2026). Development and validation of a population pharmacokinetic model for lacosamide in adult patients with epilepsy to inform precision dosing. <i>BMC pharmacology &amp; toxicology 27(1)</i>. DOI:<a href=\"https://doi.org/10.1186/s40360-026-01114-2\">10.1186/s40360-026-01114-2</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/41776608\">41776608</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Yu_2026: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 345600, Tolerance = 1e-9, Interval = 1));
end Lacosamide_Yu2026_reference;
