within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B03B_VitaminB12AndFolicAcid.B03BA03_Hydroxocobalamin;
model Hydroxocobalamin_de1994_reference
  parameter Real Cl_ref = 1.611111111111111e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0343 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Hydroxocobalamin.M,
    adminMass = 2e-08
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>hydroxocobalamin</td></tr><tr><td>ATC code:</td><td>B03BA03</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>de La Coussaye JE et al. 1994</td></tr><tr><td>population:</td><td>conscious dogs</td></tr><tr><td>measured compound:</td><td>hydroxocobalamin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_hydroxocobalamin/Hydroxocobalamin_de1994_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>elimination half-life</td><td>7.36</td><td>h</td><td><small>t1/2z</small></td></tr><tr><td>volume of distribution</td><td>0.49</td><td>L/kg</td><td><small>V</small></td></tr><tr><td>total clearance</td><td>0.58</td><td>L/h</td><td><small>CL</small></td></tr></table><h4>About hydroxocobalamin</h4><p>Hydroxocobalamin, a vitamin B12 preparation, is used to treat vitamin B12 deficiency such as pernicious anemia and certain neuropathies, and also serves as an antidote for poisoning. It is an approved medicine included on the WHO essential medicines list, and an EMA-authorised product is available in the European Union for treating poisoning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q73972\">Wikidata Q73972</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Hydroxocobalamin\">Hydroxocobalamin</a>.</p><h4>References</h4><ol><li><p>de La Coussaye JE et al. (1994). Pharmacokinetics of hydroxocobalamin in dogs. <i>Journal of neurosurgical anesthesiology 6(2):111–115</i>. DOI:<a href=\"https://doi.org/10.1097/00008506-199404000-00006\">10.1097/00008506-199404000-00006</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/8012169\">8012169</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from de_1994: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 133200, Tolerance = 1e-9, Interval = 1));
end Hydroxocobalamin_de1994_reference;
