within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M04A_AntigoutPreparations.M04AA01_Allopurinol;
model Allopurinol_Graham1996_PD_plasma_urate_concentration
  "sigmoid_emax exposure-response sweep — Graham_1996 :: plasma urate concentration (plasma urate concentration)"
  extends Pharmacolibrary.Pharmacodynamic.SigmoidEmaxSweep(
    E0 = 0.35,      // [m]
    Emax = -0.29,  // [m]
    EC50 = 0.00556,  // [kg/m3; mg l-1 × 0.001]
    gamma = 1.22,
    exposure_per_s = 0.001);   // 1 mg l-1 per second
  // imax_as_negative_emax: Imax (Q323) enters SigmoidEmaxSweep as −Emax
  annotation(experiment(StartTime = 0, StopTime = 56, Interval = 0.112),
    Documentation(info = "<html><body><h4>Allopurinol_Graham1996_PD_plasma_urate_concentration</h4><p>The steady-state exposure-response curve of Graham S et al., <i>British journal of clinical pharmacology 41(4):299–304</i> 1996 (<a href=\"https://doi.org/10.1046/j.1365-2125.1996.03116.x\">doi:10.1046/j.1365-2125.1996.03116.x</a>) — plasma urate concentration [m] against oxypurinol mg l-1 — obtained by sweeping the driver instead of simulating a dose. Model family: sigmoid_emax.</p><h4>The parameters, in the paper's terms</h4><pre>  E0    =       0.35 m       drug-free response (baseline) (Ro, Q324)
  Emax  =       0.29 m       maximal effect term (E max, Q323)
  EC50  =       5.56 mg l-1   exposure at half of the maximal effect term (C 50, Q322)
  gamma =       1.22          Hill coefficient (c, Q325)</pre><p>The algebra is <a href=\"modelica://Pharmacolibrary.Pharmacodynamic.SigmoidEmaxSweep\">SigmoidEmaxSweep</a>; this model only supplies the numbers. The x axis is one mg l-1 of oxypurinol per second of simulated time (exposure is in kg/m3): there is no state, no dose and no kinetics — plot <code>response</code> against <code>exposure</code> (or <code>time</code>).</p><h4>What it reproduces</h4><pre>  exposure = 0         response 0.35   (drug-free)
  exposure = EC50 (5.56 mg l-1)  response 0.205
  exposure -> infinity  response 0.06</pre></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Graham_1996: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"));
end Allopurinol_Graham1996_PD_plasma_urate_concentration;
