within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M04A_AntigoutPreparations.M04AA01_Allopurinol;
model Allopurinol_Wen2023_base
  parameter Real Cl_ref = 2.7777777777777776e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.047700000000000006 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Allopurinol.M,
    adminMass = 0.0001,
    ka = 0.0003055555555555556,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>allopurinol</td></tr><tr><td>ATC code:</td><td>M04AA01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Wen YF et al. 2023</td></tr><tr><td>population:</td><td>Hmong adults with gout and/or hyperuricemia</td></tr><tr><td>measured compound:</td><td>oxypurinol</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_allopurinol/Allopurinol_Wen2023_base\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/fm (L/h)</td><td>1</td><td>L/h</td><td><small>CLm/F</small></td></tr><tr><td>V/fm (L)</td><td>47.7</td><td>L</td><td><small>V/F</small></td></tr><tr><td>Kfm (/h)</td><td>1.1</td><td>/h</td><td><small>kfm</small></td></tr></table><h4>About allopurinol</h4><p>Allopurinol is a medicine used to lower high uric acid levels in the blood, mainly to treat gout and hyperuricemia. It is widely used and appears on the WHO list of essential medicines.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q412486\">Wikidata Q412486</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Allopurinol\">Allopurinol</a>.</p><h4>References</h4><ol><li><p>Wen YF et al. (2023). Population pharmacokinetics, pharmacodynamics and pharmacogenetics modelling of oxypurinol in Hmong adults with gout and/or hyperuricemia. <i>British journal of clinical pharmacology 89(10):2964–2976</i>. DOI:<a href=\"https://doi.org/10.1111/bcp.15792\">10.1111/bcp.15792</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37202871\">37202871</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Wen_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 604800, Tolerance = 1e-9, Interval = 1));
end Allopurinol_Wen2023_base;
