within Pharmacolibrary.Drugs.V_Various.V10X_OtherTherapeuticRadiopharmaceuticals.V10XX04_Lutetium177luOxodotreoti;
model Lutetium177luOxodotreotide_Barakat2023_base
  parameter Real Cl_ref = 7.444444444444444e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.07790000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 1e-05,
    k12 = 2.417629439452289e-05,
    k21 = 9.912280701754386e-06
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>lutetium_177lu_oxodotreotide</td></tr><tr><td>ATC code:</td><td>V10XX04</td></tr><tr><td>model:</td><td>two compartments, IV dosing <small>(PK_2C)</small></td></tr><tr><td>source:</td><td>Barakat A et al. 2023</td></tr><tr><td>population:</td><td>patients with gastroenteropancreatic neuroendocrine tumors</td></tr><tr><td>measured compound:</td><td>lutetium_177lu_oxodotreotide</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_lutetium_177lu_oxodotreotide/Lutetium177luOxodotreotide_Barakat2023_base\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL (L/h)</td><td>2.68</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>V1 (L)</td><td>77.9</td><td>L</td><td><small>V1</small></td></tr><tr><td>Q (L/h)</td><td>6.78</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>V2 (L)</td><td>190</td><td>L</td><td><small>V2</small></td></tr></table><h4>About lutetium_177lu_oxodotreotide</h4><p>Lutetium (177Lu) oxodotreotide is a therapeutic radiopharmaceutical used to treat neuroendocrine tumours. It is authorised in the European Union, where it is used in specialised settings for this indication.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q27273888\">Wikidata Q27273888</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Lutetium177LuOxodotreotide\">Lutetium177LuOxodotreotide</a>.</p><h4>References</h4><ol><li><p>Barakat A et al. (2023). Clinical Pharmacokinetics of Radiopharmaceuticals from SPECT/CT Image Acquisition by Contouring in Patients with Gastroenteropancreatic Neuroendocrine Tumors: Lu-177 DOTATATE (Lutathera. <i>European journal of drug metabolism and pharmacokinetics 48(4):329–339</i>. DOI:<a href=\"https://doi.org/10.1007/s13318-023-00829-5\">10.1007/s13318-023-00829-5</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37184824\">37184824</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Barakat_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 432000, Tolerance = 1e-9, Interval = 1));
end Lutetium177luOxodotreotide_Barakat2023_base;
