within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins.J01CA04_Amoxicillin;
model Amoxicillin_Wu2021_reference
  parameter Real Cl_ref = 5.972222222222222e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.00217 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Amoxicillin.M,
    adminMass = 0.00175,
    ka = 4.722222222222223e-05,
    Tlag = 0.0,
    k12 = 9.101382488479262e-05,
    k21 = 9.729064039408868e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>amoxicillin</td></tr><tr><td>ATC code:</td><td>J01CA04</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Wu YE et al. 2021</td></tr><tr><td>population:</td><td>Chinese infants</td></tr><tr><td>measured compound:</td><td>amoxicillin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_amoxicillin/Amoxicillin_Wu2021_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL(L/h)
CL = θ1 × Fweight
θ1</td><td>2.15</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>V₁ (L)
V₁ = θ2
θ2</td><td>2.17</td><td>L</td><td><small>V1</small></td></tr><tr><td>V₂ (L)
V₂ = θ3
θ3</td><td>2.03</td><td>L</td><td><small>V2</small></td></tr><tr><td>Q (L/h)
Q = θ4
θ4</td><td>0.711</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>Fweight = (CW/7)^0.5
θ5</td><td>0.946</td><td></td><td><small>equation variable</small></td></tr><tr><td>ka (h−1)</td><td>0.17</td><td>h−1</td><td><small>kabs</small></td></tr></table><h4>About amoxicillin</h4><p>Amoxicillin is a penicillin antibiotic used to treat many bacterial infections, including ear, sinus, respiratory and urinary tract infections, and it is also given in combination to eradicate Helicobacter pylori. It is widely used around the world, is included on the WHO list of essential medicines, and is also approved for veterinary use.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q201928\">Wikidata Q201928</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Amoxicillin\">Amoxicillin</a>.</p><h4>References</h4><ol><li><p>Wu YE et al. (2021). Population Pharmacokinetics and Dosing Optimization of Amoxicillin in Chinese Infants. <i>Journal of clinical pharmacology 61(4):538–546</i>. DOI:<a href=\"https://doi.org/10.1002/jcph.1752\">10.1002/jcph.1752</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32996155\">32996155</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Wu_2021: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Amoxicillin_Wu2021_reference;
