within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins.J01CA04_Amoxicillin;
model Amoxicillin_Dubbelboer2025_typical_value
  parameter Real Cl_ref = 3.5e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0084 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Amoxicillin.M,
    adminMass = 0.0007,
    ka = 8.61111111111111e-05,
    Tlag = 900.0,
    k12 = 0.000902777777777778,
    k21 = 0.001177536231884058
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>amoxicillin</td></tr><tr><td>ATC code:</td><td>J01CA04</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Dubbelboer IR et al. 2025</td></tr><tr><td>population:</td><td>healthy cats</td></tr><tr><td>measured compound:</td><td>amoxicillin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_amoxicillin/Amoxicillin_Dubbelboer2025_typical_value\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>V 1</td><td>0.12</td><td>L/kg</td><td><small>V1</small></td></tr><tr><td>V 2</td><td>0.092</td><td>L/kg</td><td><small>V2</small></td></tr><tr><td>V 3</td><td>0.021</td><td>L/kg</td><td><small>V3</small></td></tr><tr><td>Cl</td><td>0.18</td><td>L/h/kg</td><td><small>CL</small></td></tr><tr><td>Q 1</td><td>0.39</td><td>L/h/kg</td><td><small>Q</small></td></tr><tr><td>T lagpo</td><td>0.25</td><td>h</td><td><small>tlag</small></td></tr><tr><td>K asc</td><td>0.31</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>F oral</td><td>33</td><td></td><td><small>Fab</small></td></tr></table><h4>About amoxicillin</h4><p>Amoxicillin is a penicillin antibiotic used to treat many bacterial infections, including ear, sinus, respiratory and urinary tract infections, and it is also given in combination to eradicate Helicobacter pylori. It is widely used around the world, is included on the WHO list of essential medicines, and is also approved for veterinary use.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q201928\">Wikidata Q201928</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Amoxicillin\">Amoxicillin</a>.</p><h4>References</h4><ol><li><p>Dubbelboer IR et al. (2025). Pharmacokinetics of Amoxicillin in the Cat. <i>Journal of veterinary pharmacology and therapeutics 48(5):380–388</i>. DOI:<a href=\"https://doi.org/10.1111/jvp.70003\">10.1111/jvp.70003</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/40454567\">40454567</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Dubbelboer_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Amoxicillin_Dubbelboer2025_typical_value;
