within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins.J01CA04_Amoxicillin;
model Amoxicillin_Lacampagne2026_reference
  parameter Real Cl_ref = 1.536111111111111e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.019600000000000003 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 25.0,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Amoxicillin.M,
    adminMass = 0.0015,
    ka = 0.00011388888888888888,
    Tlag = 0.0,
    k12 = 0.0005952380952380951,
    k21 = 0.000980392156862745
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>amoxicillin</td></tr><tr><td>ATC code:</td><td>J01CA04</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Lacampagne M et al. 2026</td></tr><tr><td>population:</td><td>post-weaning piglets</td></tr><tr><td>measured compound:</td><td>amoxicillin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_amoxicillin/Amoxicillin_Lacampagne2026_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Cl</td><td>0.79</td><td>L/h/kg</td><td><small>CL</small></td></tr><tr><td>Q</td><td>0.60</td><td>L/h/kg</td><td><small>Q</small></td></tr><tr><td>V1</td><td>0.28</td><td>L/kg</td><td><small>V1</small></td></tr><tr><td>V2</td><td>0.17</td><td>L/kg</td><td><small>V2</small></td></tr><tr><td>Ka</td><td>0.41</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>F</td><td>25</td><td></td><td><small>Fab</small></td></tr></table><h4>About amoxicillin</h4><p>Amoxicillin is a penicillin antibiotic used to treat many bacterial infections, including ear, sinus, respiratory and urinary tract infections, and it is also given in combination to eradicate Helicobacter pylori. It is widely used around the world, is included on the WHO list of essential medicines, and is also approved for veterinary use.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q201928\">Wikidata Q201928</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Amoxicillin\">Amoxicillin</a>.</p><h4>References</h4><ol><li><p>Lacampagne M et al. (2026). Predicted PK/PD inadequacy of amoxicillin delivered in drinking water against respiratory pathogens in post-weaning piglets: can time-restricted dosing improve animals' exposure and potential treatment efficacy?. <i>Veterinary and animal science 33:100698</i>. DOI:<a href=\"https://doi.org/10.1016/j.vas.2026.100698\">10.1016/j.vas.2026.100698</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/42221906\">42221906</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Lacampagne_2026: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Amoxicillin_Lacampagne2026_reference;
