within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07A_BetaBlockingAgents.C07AB11_SAtenolol;
model SAtenolol_Buck1989_reference
  parameter Real Cl_ref = 2.9166666666666666e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0231 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.SAtenolol.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>s_atenolol</td></tr><tr><td>ATC code:</td><td>C07AB11</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Buck ML et al. 1989</td></tr><tr><td>population:</td><td>children</td></tr><tr><td>measured compound:</td><td>atenolol</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>total body clearance</td><td>0.15</td><td>L/hr/kg</td><td><small>CL</small></td></tr><tr><td>volume of the central compartment</td><td>0.33</td><td>L/kg</td><td><small>V</small></td></tr><tr><td>volume of distribution at steady state</td><td>0.83</td><td>L/kg</td><td><small>Vss</small></td></tr><tr><td>distributive elimination half-life</td><td>0.29</td><td>hour</td><td><small>t1/2α</small></td></tr><tr><td>terminal elimination half-life</td><td>4.56</td><td>hours</td><td><small>t1/2z</small></td></tr></table><h4>About s_atenolol</h4><p>Esatenolol, the S-enantiomer of atenolol, is a selective beta blocker studied for treating myocardial infarction and arterial hypertension. It remains an experimental compound and is not an established marketed medicine.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q24255323\">Wikidata Q24255323</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.SAtenolol\">SAtenolol</a>.</p><h4>References</h4><ol><li><p>Buck ML et al. (1989). Pharmacokinetics and pharmacodynamics of atenolol in children. <i>Clinical pharmacology and therapeutics 46(6):629–633</i>. DOI:<a href=\"https://doi.org/10.1038/clpt.1989.198\">10.1038/clpt.1989.198</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/2598566\">2598566</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Buck_1989: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end SAtenolol_Buck1989_reference;
