within Pharmacolibrary.Drugs.N_NervousSystem.N02A_Opioids.N02AC03_Piritramide;
model Piritramide_Kietzmann1996_reference
  parameter Real Cl_ref = 9.1e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.329 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Piritramide.M,
    adminMass = 4.5e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>piritramide</td></tr><tr><td>ATC code:</td><td>N02AC03</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Kietzmann D et al. 1996</td></tr><tr><td>population:</td><td>surgical patients</td></tr><tr><td>measured compound:</td><td>piritramide</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_piritramide/Piritramide_Kietzmann1996_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>volume of distribution at steady state</td><td>4.7</td><td>l/kg</td><td><small>Vss</small></td></tr><tr><td>systemic plasma clearance</td><td>7.8</td><td>ml/kg/min</td><td><small>CL</small></td></tr><tr><td>Renal clearance of unchanged piritramide</td><td>0.13</td><td>ml/kg/min</td><td><small>CLR</small></td></tr><tr><td>terminal elimination half-life</td><td>8.0</td><td>h</td><td><small>t1/2z</small></td></tr><tr><td>Verteilungsvolumens von</td><td>4.7</td><td>l/kg</td><td><small>V</small></td></tr></table><h4>About piritramide</h4><p>Piritramide is a strong opioid painkiller used to treat moderate to severe pain, such as pain after surgery. It is not approved everywhere and has been withdrawn in some countries, but it remains in clinical use in parts of Europe, mainly in hospital settings.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q416439\">Wikidata Q416439</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Piritramide\">Piritramide</a>.</p><h4>References</h4><ol><li><p>Kietzmann D et al. (1996). Pharmacokinetics of piritramide after an intravenous bolus in surgical patients. <i>Acta anaesthesiologica Scandinavica 40(8 Pt 1):898–903</i>. DOI:<a href=\"https://doi.org/10.1111/j.1399-6576.1996.tb04557.x\">10.1111/j.1399-6576.1996.tb04557.x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/8908225\">8908225</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Kietzmann_1996: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 144000, Tolerance = 1e-9, Interval = 1));
end Piritramide_Kietzmann1996_reference;
