within Pharmacolibrary.Drugs.N_NervousSystem.N02A_Opioids.N02AC03_Piritramide;
model Piritramide_Mller2006_reference
  parameter Real Cl_ref = 2.65e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.14 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Piritramide.M,
    adminMass = 4.5e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>piritramide</td></tr><tr><td>ATC code:</td><td>N02AC03</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Müller C et al. 2006</td></tr><tr><td>population:</td><td>newborns, infants and young children in intensive care units</td></tr><tr><td>measured compound:</td><td>piritramide</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_piritramide/Piritramide_Mller2006_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>t 1/2 beta</td><td>702</td><td>min</td><td><small>t1/2β</small></td></tr><tr><td>Cl(t)</td><td>15.9</td><td>ml/min</td><td><small>CL</small></td></tr><tr><td>elimination half-life</td><td>702</td><td>min</td><td><small>t1/2z</small></td></tr><tr><td>Vd(ss)</td><td>2.0</td><td>l/kg</td><td><small>V</small></td></tr></table><h4>About piritramide</h4><p>Piritramide is a strong opioid painkiller used to treat moderate to severe pain, such as pain after surgery. It is not approved everywhere and has been withdrawn in some countries, but it remains in clinical use in parts of Europe, mainly in hospital settings.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q416439\">Wikidata Q416439</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Piritramide\">Piritramide</a>.</p><h4>References</h4><ol><li><p>Müller C et al. (2006). Pharmacokinetics of piritramide in newborns, infants and young children in intensive care units. <i>European journal of pediatrics 165(4):229–239</i>. DOI:<a href=\"https://doi.org/10.1007/s00431-005-0021-z\">10.1007/s00431-005-0021-z</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16496200\">16496200</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Müller_2006: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 259200, Tolerance = 1e-9, Interval = 1));
end Piritramide_Mller2006_reference;
