within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B03X_OtherAntianemicPreparations.B03XA02_DarbepoetinAlfa;
model DarbepoetinAlfa_Kawakami2009_reference
  parameter Real Cl_ref = 4.388888888888889e-08 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0137 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 0.0001,
    ka = 1.0444444444444445e-05,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>darbepoetin_alfa</td></tr><tr><td>ATC code:</td><td>B03XA02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Kawakami K et al. 2009</td></tr><tr><td>population:</td><td>peritoneal dialysis and non-dialysis patients with chronic kidney disease</td></tr><tr><td>measured compound:</td><td>darbepoetin_alfa</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_darbepoetin_alfa/DarbepoetinAlfa_Kawakami2009_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>apparent clearance (CL/f)</td><td>0.158</td><td>l/h</td><td><small>CL/F</small></td></tr><tr><td>apparent volume of central compartment (V(1)/f)</td><td>13.7</td><td>l</td><td><small>V/F</small></td></tr><tr><td>absorption rate constant</td><td>0.0376</td><td>/h</td><td><small>kabs</small></td></tr></table><h4>About darbepoetin_alfa</h4><p>Darbepoetin alfa is an antianemic medicine used to treat anemia, including anemia linked to chronic kidney failure and cancer treatment. It is an approved medicine authorised in the European Union, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q2178381\">Wikidata Q2178381</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.DarbepoetinAlfa\">DarbepoetinAlfa</a>.</p><h4>References</h4><ol><li><p>Kawakami K et al. (2009). Population pharmacokinetics of darbepoetin alpha in peritoneal dialysis and non-dialysis patients with chronic kidney disease after single subcutaneous administration. <i>European journal of clinical pharmacology 65(2):169–178</i>. DOI:<a href=\"https://doi.org/10.1007/s00228-008-0561-z\">10.1007/s00228-008-0561-z</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18807251\">18807251</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Kawakami_2009: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end DarbepoetinAlfa_Kawakami2009_reference;
