within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B03X_OtherAntianemicPreparations.B03XA02_DarbepoetinAlfa;
model DarbepoetinAlfa_Roberts2015_reference
  parameter Real Cl_ref = 1.2916666666666667e-08 "Cl [m3/s]";
  parameter Real Vd_ref = 0.00158 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 4.500000000000001e-09
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>darbepoetin_alfa</td></tr><tr><td>ATC code:</td><td>B03XA02</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Roberts JK et al. 2015</td></tr><tr><td>population:</td><td>hypothermic neonates with hypoxic-ischemic encephalopathy</td></tr><tr><td>measured compound:</td><td>darbepoetin_alfa</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_darbepoetin_alfa/DarbepoetinAlfa_Roberts2015_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>clearance</td><td>0.0465</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>1.58</td><td>L</td><td><small>V</small></td></tr></table><h4>About darbepoetin_alfa</h4><p>Darbepoetin alfa is an antianemic medicine used to treat anemia, including anemia linked to chronic kidney failure and cancer treatment. It is an approved medicine authorised in the European Union, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q2178381\">Wikidata Q2178381</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.DarbepoetinAlfa\">DarbepoetinAlfa</a>.</p><h4>References</h4><ol><li><p>Roberts JK et al. (2015). Population Pharmacokinetics of Darbepoetin Alfa in Conjunction with Hypothermia for the Treatment of Neonatal Hypoxic-Ischemic Encephalopathy. <i>Clinical pharmacokinetics 54(12):1237–1244</i>. DOI:<a href=\"https://doi.org/10.1007/s40262-015-0286-y\">10.1007/s40262-015-0286-y</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25989868\">25989868</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Roberts_2015: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 432000, Tolerance = 1e-9, Interval = 1));
end DarbepoetinAlfa_Roberts2015_reference;
