within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07A_IntestinalAntiinfectives.A07AA10_Colistin;
model Colistin "Colistin — default model: Colistin"
  extends Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01X_OtherAntibacterials.J01XB01_Colistin.Colistin;
  annotation (Documentation(info = "<html><body><p>colistin under ATC A07AA10: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01X_OtherAntibacterials.J01XB01_Colistin\">J01XB01_Colistin</a> (ATC J01XB01); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Colistin;
