within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01G_AminoglycosideAntibacterials.J01GB06_Amikacin;
model Amikacin_Marsot2017_reference
  parameter Real Cl_ref = 1.111111111111111e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.018600000000000002 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Amikacin.M,
    adminMass = 0.001
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>amikacin</td></tr><tr><td>ATC code:</td><td>J01GB06</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Marsot A et al. 2017</td></tr><tr><td>population:</td><td>critically ill patients</td></tr><tr><td>measured compound:</td><td>amikacin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_amikacin/Amikacin_Marsot2017_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>clearance</td><td>4.0</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>18.6</td><td>L</td><td><small>V</small></td></tr></table><h4>About amikacin</h4><p>Amikacin is an aminoglycoside antibiotic used to treat serious bacterial infections, including gram-negative and Pseudomonas infections, sepsis, meningitis, endocarditis, and mycobacterial infections. It is widely used and appears on the WHO essential medicines list, with authorised products in the European Union; it is also approved for veterinary use.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q408529\">Wikidata Q408529</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Amikacin\">Amikacin</a>.</p><h4>References</h4><ol><li><p>Marsot A et al. (2017). Amikacin in Critically Ill Patients: A Review of Population Pharmacokinetic Studies. <i>Clinical pharmacokinetics 56(2):127–138</i>. DOI:<a href=\"https://doi.org/10.1007/s40262-016-0428-x\">10.1007/s40262-016-0428-x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27324191\">27324191</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Marsot_2017: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Amikacin_Marsot2017_reference;
