within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis.A02BA02_Ranitidine;
model Ranitidine_Hawwa2013_reference
  parameter Real Cl_ref = 8.916666666666667e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.28500000000000003 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 27.5,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Ranitidine.M,
    adminMass = 0.0003,
    ka = 0.0003638888888888889,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>ranitidine</td></tr><tr><td>ATC code:</td><td>A02BA02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Hawwa AF et al. 2013</td></tr><tr><td>population:</td><td>critically ill children</td></tr><tr><td>measured compound:</td><td>ranitidine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_ranitidine/Ranitidine_Hawwa2013_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>total clearance</td><td>32.1</td><td>l h(-1)</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>285</td><td>l</td><td><small>V</small></td></tr><tr><td>absorption rate constant</td><td>1.31</td><td>h(-1)</td><td><small>kabs</small></td></tr><tr><td>bioavailability</td><td>27.5</td><td>%</td><td><small>Fab</small></td></tr></table><h4>About ranitidine</h4><p>Ranitidine is an H2-receptor antagonist that was used to treat acid-related stomach problems such as peptic ulcers, gastritis, heartburn and reflux disease. It has been withdrawn from many markets after the drug was found to contain an impurity that may cause cancer, so it is no longer generally available.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q423037\">Wikidata Q423037</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Ranitidine\">Ranitidine</a>.</p><h4>References</h4><ol><li><p>Hawwa AF et al. (2013). Prophylactic ranitidine treatment in critically ill children--a population pharmacokinetic study. <i>British journal of clinical pharmacology 75(5):1265–1276</i>. DOI:<a href=\"https://doi.org/10.1111/j.1365-2125.2012.04473.x\">10.1111/j.1365-2125.2012.04473.x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/23016949\">23016949</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Hawwa_2013: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 122400, Tolerance = 1e-9, Interval = 1));
end Ranitidine_Hawwa2013_reference;
