within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B01A_AntithromboticAgents.B01AF01_Rivaroxaban;
model Rivaroxaban_Liu2022_sequential_modeling
  parameter Real Cl_ref = 1.4000000000000001e-06 "Cl [m3/s]";
  parameter Real cov_egfr_0 = 0 "egfr covariate";
  parameter Real cov_egfr_1 = 0 "egfr covariate";
  parameter Real Vd_ref = 0.0404 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref*(1 + (0.54)*cov_egfr_0)*(1 + (-0.0868)*cov_egfr_1),
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Rivaroxaban.M,
    adminMass = 1e-05,
    ka = 0.0001713888888888889,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>rivaroxaban</td></tr><tr><td>ATC code:</td><td>B01AF01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Liu XQ et al. 2022</td></tr><tr><td>population:</td><td>Chinese patients with non-valvular atrial fibrillation</td></tr><tr><td>measured compound:</td><td>rivaroxaban</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_rivaroxaban/Rivaroxaban_Liu2022_sequential_modeling\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>k a (h -1 )</td><td>0.617</td><td>h -1</td><td><small>kabs</small></td></tr><tr><td>CL/F (L/h)</td><td>5.04</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>egfr_on_cl_f</td><td>0.54</td><td></td><td><small>equation variable</small></td></tr><tr><td>V/F (L)</td><td>40.4</td><td>L</td><td><small>V/F</small></td></tr><tr><td>ω CL</td><td>35.4</td><td></td><td><small>CL</small></td></tr><tr><td>egfr_on_pt_base</td><td>-0.0868</td><td></td><td><small>equation variable</small></td></tr></table><h4>About rivaroxaban</h4><p>Rivaroxaban is an anticoagulant that directly inhibits factor Xa and is used to prevent and treat blood clots, including venous thromboembolism, pulmonary embolism, and stroke prevention in atrial fibrillation. It is widely used and authorised in the European Union, with several approved products on the market.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q420262\">Wikidata Q420262</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Rivaroxaban\">Rivaroxaban</a>.</p><h4>References</h4><ol><li><p>Liu XQ et al. (2022). Population pharmacokinetic and pharmacodynamic analysis of rivaroxaban in Chinese patients with non-valvular atrial fibrillation. <i>Acta pharmacologica Sinica 43(10):2723–2734</i>. DOI:<a href=\"https://doi.org/10.1038/s41401-022-00892-9\">10.1038/s41401-022-00892-9</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35354961\">35354961</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Liu_2022: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 118800, Tolerance = 1e-9, Interval = 1));
end Rivaroxaban_Liu2022_sequential_modeling;
