within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins.A10BB01_Glibenclamide;
model Glibenclamide_Rambiritch2016_PD_full_glucose_profile
  "emax exposure-response sweep — Rambiritch_2016 :: full glucose profile (full glucose profile)"
  extends Pharmacolibrary.Pharmacodynamic.SigmoidEmaxSweep(
    E0 = 15.9,      // [mol/m3; mmol/L × 1]
    Emax = -0.34,  // [mol/m3; mmol/L × 1]
    EC50 = 2.21e-06,  // [kg; mg × 1e-06]
    gamma = 1,
    exposure_per_s = 1e-06);   // 1 mg per second
  // imax_as_negative_emax: Imax (Q323) enters SigmoidEmaxSweep as −Emax
  // defaulted: gamma
  annotation(experiment(StartTime = 0, StopTime = 23, Interval = 0.046),
    Documentation(info = "<html><body><h4>Glibenclamide_Rambiritch2016_PD_full_glucose_profile</h4><p>The steady-state exposure-response curve of Rambiritch V et al., <i>Clinical pharmacology : advances and applications 8:141–153</i> 2016 (<a href=\"https://doi.org/10.2147/CPAA.S102674\">doi:10.2147/CPAA.S102674</a>) — full glucose profile [mmol/L] against glibenclamide mg — obtained by sweeping the driver instead of simulating a dose. Model family: emax.</p><h4>The parameters, in the paper's terms</h4><pre>  E0    =       15.9 mmol/L   drug-free response (baseline) (A0, Q324)
  Emax  =       0.34 mmol/L   maximal effect term (Emax, Q323)
  EC50  =       2.21 mg       exposure at half of the maximal effect term (ED50, Q322)
  gamma = (library default) Hill coefficient</pre><p>The algebra is <a href=\"modelica://Pharmacolibrary.Pharmacodynamic.SigmoidEmaxSweep\">SigmoidEmaxSweep</a>; this model only supplies the numbers. The x axis is one mg of glibenclamide per second of simulated time (exposure is in kg): there is no state, no dose and no kinetics — plot <code>response</code> against <code>exposure</code> (or <code>time</code>).</p><h4>What it reproduces</h4><pre>  exposure = 0         response 15.9   (drug-free)
  exposure = EC50 (2.21 mg)  response 15.73
  exposure -> infinity  response 15.56</pre></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Rambiritch_2016: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"));
end Glibenclamide_Rambiritch2016_PD_full_glucose_profile;
