within Pharmacolibrary.Drugs.V_Various.V03A_AllOtherTherapeuticProducts.V03AB33_Hydroxocobalamin;
model Hydroxocobalamin "Hydroxocobalamin — default model: Hydroxocobalamin"
  extends Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B03B_VitaminB12AndFolicAcid.B03BA03_Hydroxocobalamin.Hydroxocobalamin;
  annotation (Documentation(info = "<html><body><p>hydroxocobalamin under ATC V03AB33: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B03B_VitaminB12AndFolicAcid.B03BA03_Hydroxocobalamin\">B03BA03_Hydroxocobalamin</a> (ATC B03BA03); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Hydroxocobalamin;
