within Pharmacolibrary.Drugs.S_SensoryOrgans.S03A_Antiinfectives.S03AA07_Ciprofloxacin;
model Ciprofloxacin "Ciprofloxacin — default model: Ciprofloxacin"
  extends Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01M_QuinoloneAntibacterials.J01MA02_Ciprofloxacin.Ciprofloxacin;
  annotation (Documentation(info = "<html><body><p>ciprofloxacin under ATC S03AA07: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01M_QuinoloneAntibacterials.J01MA02_Ciprofloxacin\">J01MA02_Ciprofloxacin</a> (ATC J01MA02); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Ciprofloxacin;
