within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01A_Tetracyclines.J01AA02_Doxycycline;
model Doxycycline_Thompson2019_reference
  parameter Real Cl_ref = 9.222222222222222e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0968 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Doxycycline.M,
    adminMass = 0.0001
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>doxycycline</td></tr><tr><td>ATC code:</td><td>J01AA02</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Thompson EJ et al. 2019</td></tr><tr><td>population:</td><td>children 0-18 years of age</td></tr><tr><td>measured compound:</td><td>doxycycline</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_doxycycline/Doxycycline_Thompson2019_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>doxycycline clearance</td><td>3.32</td><td>L/h/70 kg</td><td><small>CL</small></td></tr><tr><td>volume</td><td>96.8</td><td>L/70kg</td><td><small>V</small></td></tr><tr><td>bioavailability</td><td>89.6</td><td>%</td><td><small>Fab</small></td></tr></table><h4>About doxycycline</h4><p>Doxycycline is a tetracycline antibiotic used to treat many bacterial infections, including pneumonia, acne, Lyme disease, and chlamydia, and to prevent malaria. It is widely used in human medicine and is also approved for veterinary use, and it appears on the WHO list of essential medicines.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q422442\">Wikidata Q422442</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Doxycycline\">Doxycycline</a>.</p><h4>References</h4><ol><li><p>Thompson EJ et al. (2019). Population Pharmacokinetics of Doxycycline in Children. <i>Antimicrobial agents and chemotherapy 63(12)</i>. DOI:<a href=\"https://doi.org/10.1128/AAC.01508-19\">10.1128/AAC.01508-19</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31548185\">31548185</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Thompson_2019: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 432000, Tolerance = 1e-9, Interval = 1));
end Doxycycline_Thompson2019_reference;
