within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01B_AntiarrhythmicsClassIAndIii.C01BA02_Procainamide;
model Procainamide_Grasela1984_reference
  parameter Real Cl_ref = 3.333333333333333e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.136 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Procainamide.M,
    adminMass = 0.003
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>procainamide</td></tr><tr><td>ATC code:</td><td>C01BA02</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Grasela TH et al. 1984</td></tr><tr><td>population:</td><td>patients receiving procainamide</td></tr><tr><td>measured compound:</td><td>procainamide</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_procainamide/Procainamide_Grasela1984_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CLR</td><td>14.4</td><td>L/h</td><td><small>CLR</small></td></tr><tr><td>CLO</td><td>1.2</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Vd</td><td>136.0</td><td>L</td><td><small>V</small></td></tr></table><h4>About procainamide</h4><p>Procainamide is a class Ia antiarrhythmic used to treat heart rhythm problems such as atrial fibrillation and supraventricular tachycardia. It is an approved medicine, though it is not authorised in the European Union and is used mainly in other regions.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q417597\">Wikidata Q417597</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Procainamide\">Procainamide</a>.</p><h4>References</h4><ol><li><p>Grasela TH et al. (1984). Population pharmacokinetics of procainamide from routine clinical data. <i>Clinical pharmacokinetics 9(6):545–554</i>. DOI:<a href=\"https://doi.org/10.2165/00003088-198409060-00004\">10.2165/00003088-198409060-00004</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/6509861\">6509861</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Grasela_1984: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 1468800, Tolerance = 1e-9, Interval = 1));
end Procainamide_Grasela1984_reference;
