within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A04A_AntiemeticsAndAntinauseants.A04AA01_Ondansetron;
model Ondansetron_Chiang2021v2_reference
  parameter Real Cl_ref = 6.833333333333334e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0633 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Ondansetron.M,
    adminMass = 1.6e-05,
    k12 = 0.000925925925925926,
    k21 = 0.0005426954732510288
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>ondansetron</td></tr><tr><td>ATC code:</td><td>A04AA01</td></tr><tr><td>model:</td><td>two compartments, IV dosing <small>(PK_2C)</small></td></tr><tr><td>source:</td><td>Chiang MD et al. 2021</td></tr><tr><td>population:</td><td>patients</td></tr><tr><td>measured compound:</td><td>ondansetron</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_ondansetron/Ondansetron_Chiang2021v2_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL (L/h)</td><td>24.6</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>VC (L)</td><td>63.3</td><td>L</td><td><small>V1</small></td></tr><tr><td>Q (L/h)</td><td>211</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>VT (L)</td><td>107</td><td>L</td><td><small>V</small></td></tr><tr><td>KP</td><td>0.145</td><td></td><td><small>Kp</small></td></tr><tr><td>V 2 (l)</td><td>108.0</td><td>l</td><td><small>V2</small></td></tr></table><h4>About ondansetron</h4><p>Ondansetron is an antiemetic used to prevent and treat nausea and vomiting, including in gastroenteritis. It is widely used and is included on the WHO list of essential medicines.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q410011\">Wikidata Q410011</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Ondansetron\">Ondansetron</a>.</p><h4>References</h4><ol><li><p>Chiang MD et al. (2021). Plasma and cerebrospinal fluid pharmacokinetics of ondansetron in humans. <i>British journal of clinical pharmacology 87(2):516–526</i>. DOI:<a href=\"https://doi.org/10.1111/bcp.14412\">10.1111/bcp.14412</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32495990\">32495990</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Chiang_2021_2: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Ondansetron_Chiang2021v2_reference;
