within Pharmacolibrary.Drugs.N_NervousSystem.N06A_Antidepressants.N06AB06_Sertraline;
model Sertraline_Castillo2024_reference
  parameter Real Cl_ref = 1.8333333333333333e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 1.414 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Sertraline.M,
    adminMass = 5e-05,
    ka = 0.0002375,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>sertraline</td></tr><tr><td>ATC code:</td><td>N06AB06</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Castillo CEC et al. 2024</td></tr><tr><td>population:</td><td>patients with psychiatric and substance use disorders</td></tr><tr><td>measured compound:</td><td>sertraline</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_sertraline/Sertraline_Castillo2024_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>sertraline clearance</td><td>66</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>absorption constant</td><td>0.855</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>volume of distribution</td><td>20.2</td><td>L/kg</td><td><small>V</small></td></tr></table><h4>About sertraline</h4><p>Sertraline is an antidepressant used for depression and several anxiety-related conditions, including obsessive-compulsive disorder, panic disorder, and post-traumatic stress disorder. It is an approved, widely used selective serotonin reuptake inhibitor.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q407617\">Wikidata Q407617</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Sertraline\">Sertraline</a>.</p><h4>References</h4><ol><li><p>Castillo CEC et al. (2024). Population Pharmacokinetics of Sertraline in Psychiatric and Substance Use Disorders. <i>Journal of clinical pharmacology 64(10):1267–1277</i>. DOI:<a href=\"https://doi.org/10.1002/jcph.2457\">10.1002/jcph.2457</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38720595\">38720595</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Castillo_2024: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 345600, Tolerance = 1e-9, Interval = 1));
end Sertraline_Castillo2024_reference;
