within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07A_BetaBlockingAgents.C07AB07_Bisoprolol;
model Bisoprolol_Cvan2016_reference
  parameter Real Cl_ref = 9.722222222222222e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0036000000000000003 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Bisoprolol.M,
    adminMass = 1.25e-06,
    ka = 0.0033888888888888888,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>bisoprolol</td></tr><tr><td>ATC code:</td><td>C07AB07</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Cvan_2016</td></tr><tr><td>population:</td><td>patients with chronic heart failure</td></tr><tr><td>measured compound:</td><td>bisoprolol</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_bisoprolol/Bisoprolol_Cvan2016_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Ka (h -1 )</td><td>12.2</td><td>h -1</td><td><small>kabs</small></td></tr><tr><td>CL (L/h)</td><td>3.5</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>V (L)</td><td>3.6</td><td>L</td><td><small>V</small></td></tr><tr><td>Additive (ng/mL)</td><td>49.9</td><td>ng/mL</td><td><small>add_error</small></td></tr></table><h4>About bisoprolol</h4><p>Bisoprolol is a selective beta blocker used for conditions such as high blood pressure, angina, heart failure, and after a heart attack. It is widely used and appears on the WHO list of essential medicines.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q412515\">Wikidata Q412515</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Bisoprolol\">Bisoprolol</a>.</p><h4>References</h4><ol><li><p>Cvan_2016 (). . <i></i>.</p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Cvan_2016: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Bisoprolol_Cvan2016_reference;
