within Pharmacolibrary.Drugs.S_SensoryOrgans.S01A_Antiinfectives.S01AA24_Kanamycin;
model Kanamycin "Kanamycin — default model: Kanamycin"
  extends Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07A_IntestinalAntiinfectives.A07AA08_Kanamycin.Kanamycin;
  annotation (Documentation(info = "<html><body><p>kanamycin under ATC S01AA24: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07A_IntestinalAntiinfectives.A07AA08_Kanamycin\">A07AA08_Kanamycin</a> (ATC A07AA08); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Kanamycin;
