within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins.A10BA02_Metformin;
model Metformin_Hong2008_reference
  parameter Real Cl_ref = 2.1944444444444445e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.648 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Metformin.M,
    adminMass = 0.002,
    ka = 0.00011388888888888888,
    Tlag = 1224.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>metformin</td></tr><tr><td>ATC code:</td><td>A10BA02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Hong Y et al. 2008</td></tr><tr><td>population:</td><td>patients with type 2 diabetes mellitus</td></tr><tr><td>measured compound:</td><td>metformin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_metformin/Metformin_Hong2008_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>clearance (CL/F)</td><td>79.0</td><td>L.h(-1)</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>648</td><td>L</td><td><small>V</small></td></tr><tr><td>Ka (h -1 ) Absorption rate constant</td><td>0.41</td><td>h -1</td><td><small>kabs</small></td></tr><tr><td>tlag (h)</td><td>0.34</td><td>h</td><td><small>tlag</small></td></tr></table><h4>About metformin</h4><p>Metformin is an anti-diabetic medicine used to treat diabetes and high blood sugar, including maturity-onset diabetes of the young type 2. It is widely used and appears on the WHO list of essential medicines, and is also available in many combination products with other oral glucose-lowering drugs.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q19484\">Wikidata Q19484</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Metformin\">Metformin</a>.</p><h4>References</h4><ol><li><p>Hong Y et al. (2008). Population exposure-response modeling of metformin in patients with type 2 diabetes mellitus. <i>Journal of clinical pharmacology 48(6):696–707</i>. DOI:<a href=\"https://doi.org/10.1177/0091270008316884\">10.1177/0091270008316884</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18372428\">18372428</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Hong_2008: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 129600, Tolerance = 1e-9, Interval = 1));
end Metformin_Hong2008_reference;
