within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins.A10BA02_Metformin;
model Metformin_Mak2023_saem_estimates
  parameter Real Cl_ref = 1.525e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.26 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Metformin.M,
    adminMass = 0.00025,
    ka = 0.00037222222222222225,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>metformin</td></tr><tr><td>ATC code:</td><td>A10BA02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Mak WY et al. 2023</td></tr><tr><td>population:</td><td>healthy adults</td></tr><tr><td>measured compound:</td><td>metformin</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_metformin/Metformin_Mak2023_saem_estimates\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>ka,fasted (h-1)</td><td>1.34</td><td>h-1</td><td><small>kabs</small></td></tr><tr><td>CL (L h-1)</td><td>54.9</td><td>L h-1</td><td><small>CL</small></td></tr><tr><td>V (L)</td><td>260</td><td>L</td><td><small>V</small></td></tr><tr><td>theta_q87_fed</td><td>0.670</td><td></td><td><small>equation variable</small></td></tr></table><h4>About metformin</h4><p>Metformin is an anti-diabetic medicine used to treat diabetes and high blood sugar, including maturity-onset diabetes of the young type 2. It is widely used and appears on the WHO list of essential medicines, and is also available in many combination products with other oral glucose-lowering drugs.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q19484\">Wikidata Q19484</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Metformin\">Metformin</a>.</p><h4>References</h4><ol><li><p>Mak WY et al. (2023). Assessment of the nlmixr R package for population pharmacokinetic modeling: A metformin case study. <i>British journal of clinical pharmacology 89(1):330–339</i>. DOI:<a href=\"https://doi.org/10.1111/bcp.15496\">10.1111/bcp.15496</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35976674\">35976674</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Mak_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Metformin_Mak2023_saem_estimates;
