within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins.A10BA02_Metformin;
model Metformin_Chae2012_reference
  parameter Real Cl_ref = 1.4611111111111112e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.113 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Metformin.M,
    adminMass = 0.0005,
    ka = 0.00011388888888888888,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>metformin</td></tr><tr><td>ATC code:</td><td>A10BA02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Chae JW et al. 2012</td></tr><tr><td>population:</td><td>healthy humans</td></tr><tr><td>measured compound:</td><td>metformin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_metformin/Metformin_Chae2012_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL (l h -1 )</td><td>52.6</td><td>l h -1</td><td><small>CL</small></td></tr><tr><td>V (l)</td><td>113</td><td>l</td><td><small>V</small></td></tr><tr><td>Ka (h -1 )</td><td>0.41</td><td>h -1</td><td><small>kabs</small></td></tr></table><h4>About metformin</h4><p>Metformin is an anti-diabetic medicine used to treat diabetes and high blood sugar, including maturity-onset diabetes of the young type 2. It is widely used and appears on the WHO list of essential medicines, and is also available in many combination products with other oral glucose-lowering drugs.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q19484\">Wikidata Q19484</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Metformin\">Metformin</a>.</p><h4>References</h4><ol><li><p>Chae JW et al. (2012). Population PK/PD analysis of metformin using the signal transduction model. <i>British journal of clinical pharmacology 74(5):815–823</i>. DOI:<a href=\"https://doi.org/10.1111/j.1365-2125.2012.04260.x\">10.1111/j.1365-2125.2012.04260.x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/22380769\">22380769</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Chae_2012: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Metformin_Chae2012_reference;
