within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins.A10BA02_Metformin;
model Metformin_Cantor2026_reference
  parameter Real Cl_ref = 2.4080555555555555e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.17025 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Metformin.M,
    adminMass = 0.002,
    ka = 5.277777777777778e-05,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>metformin</td></tr><tr><td>ATC code:</td><td>A10BA02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Cantor SL et al. 2026</td></tr><tr><td>population:</td><td>youth-onset type 2 diabetes</td></tr><tr><td>measured compound:</td><td>metformin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_metformin/Metformin_Cantor2026_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Ka: Absorption rate constant (hr-1)</td><td>0.19</td><td>hr-1</td><td><small>kabs</small></td></tr><tr><td>CL/F: Apparent oral clearance (L/hr)</td><td>86.69</td><td>L/hr</td><td><small>CL/F</small></td></tr><tr><td>Vd/F: Apparent oral volume of distribution (L)</td><td>170.25</td><td>L</td><td><small>V/F</small></td></tr></table><h4>About metformin</h4><p>Metformin is an anti-diabetic medicine used to treat diabetes and high blood sugar, including maturity-onset diabetes of the young type 2. It is widely used and appears on the WHO list of essential medicines, and is also available in many combination products with other oral glucose-lowering drugs.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q19484\">Wikidata Q19484</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Metformin\">Metformin</a>.</p><h4>References</h4><ol><li><p>Cantor SL et al. (2026). OCT1 Variants Are Associated with Metformin Clearance and Gluconeogenesis: Mechanistic Insights for Youth-Onset Type 2 Diabetes in the MIGHTY Study. <i>medRxiv : the preprint server for health sciences</i>. DOI:<a href=\"https://doi.org/10.64898/2026.05.27.26354152\">10.64898/2026.05.27.26354152</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/42245022\">42245022</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Cantor_2026: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Metformin_Cantor2026_reference;
