within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07A_BetaBlockingAgents.C07AA15_Carteolol;
model Carteolol_Ishizaki1983_reference
  parameter Real Cl_ref = 1.1818333333333333e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0518 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Carteolol.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>carteolol</td></tr><tr><td>ATC code:</td><td>C07AA15</td></tr><tr><td>model:</td><td>two compartments, IV dosing <small>(PK_2C)</small></td></tr><tr><td>source:</td><td>Ishizaki T et al. 1983</td></tr><tr><td>population:</td><td>normal volunteers</td></tr><tr><td>measured compound:</td><td>carteolol</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_carteolol/Carteolol_Ishizaki1983_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>elimination or beta-phase t1/2</td><td>4.7</td><td>h</td><td><small>t1/2β</small></td></tr><tr><td>Vc</td><td>0.74</td><td>l/kg</td><td><small>V1</small></td></tr><tr><td>Vd</td><td>4.05</td><td>l/kg</td><td><small>V</small></td></tr><tr><td>Cl</td><td>10.13</td><td>ml/min/kg</td><td><small>CL</small></td></tr><tr><td>ClR</td><td>6.56</td><td>ml/min/kg</td><td><small>CLR</small></td></tr><tr><td>ClNR</td><td>3.57</td><td>ml/min/kg</td><td><small>CLNR</small></td></tr><tr><td>absolute bioavailability obtained from plasma data</td><td>83.7</td><td>%</td><td><small>Fab</small></td></tr></table><h4>About carteolol</h4><p>Carteolol is a non-selective beta blocker used to treat arterial hypertension and to lower pressure in the eye in open-angle glaucoma and ocular hypertension. It is an approved medicine, available both as a cardiovascular beta blocker and as an eye drop for glaucoma.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q546434\">Wikidata Q546434</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Carteolol\">Carteolol</a>.</p><h4>References</h4><ol><li><p>Ishizaki T et al. (1983). Pharmacokinetics and absolute bioavailability of carteolol, a new beta-adrenergic receptor blocking agent. <i>European journal of clinical pharmacology 25(1):95–101</i>. DOI:<a href=\"https://doi.org/10.1007/BF00544023\">10.1007/BF00544023</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/6137389\">6137389</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Ishizaki_1983: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Carteolol_Ishizaki1983_reference;
