within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B03X_OtherAntianemicPreparations.B03XA06_Luspatercept;
model Luspatercept_Chen2020_reference
  parameter Real Cl_ref = 5.42824074074074e-09 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0092 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 8.75e-06,
    ka = 5.277777777777778e-06,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>luspatercept</td></tr><tr><td>ATC code:</td><td>B03XA06</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Chen N et al. 2020</td></tr><tr><td>population:</td><td>anemic patients with myelodysplastic syndromes</td></tr><tr><td>measured compound:</td><td>luspatercept</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_luspatercept/Luspatercept_Chen2020_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F, L/day</td><td>0.469</td><td>L/day</td><td><small>CL/F</small></td></tr><tr><td>V1/F, L</td><td>9.20</td><td>L</td><td><small>V/F</small></td></tr><tr><td>K a, 1/day</td><td>0.456</td><td>1/day</td><td><small>kabs</small></td></tr></table><h4>About luspatercept</h4><p>Luspatercept is an antianemic medicine used to treat anemia in people with myelodysplastic syndromes or beta-thalassemia. It is authorised in the European Union and is also being studied for further uses.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q30314143\">Wikidata Q30314143</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Luspatercept\">Luspatercept</a>.</p><h4>References</h4><ol><li><p>Chen N et al. (2020). Population Pharmacokinetics and Exposure-Response of Luspatercept, an Erythroid Maturation Agent, in Anemic Patients With Myelodysplastic Syndromes. <i>CPT: pharmacometrics &amp; systems pharmacology 9(7):395–404</i>. DOI:<a href=\"https://doi.org/10.1002/psp4.12521\">10.1002/psp4.12521</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32602651\">32602651</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Chen_2020: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 6652800, Tolerance = 1e-9, Interval = 1));
end Luspatercept_Chen2020_reference;
