within Pharmacolibrary.Drugs.N_NervousSystem.N06A_Antidepressants.N06AX03_Mianserin;
model Mianserin_Timmer1985_reference
  parameter Real Cl_ref = 5.277777777777778e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.444 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Mianserin.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>mianserin</td></tr><tr><td>ATC code:</td><td>N06AX03</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Timmer CJ et al. 1985</td></tr><tr><td>population:</td><td>healthy males</td></tr><tr><td>measured compound:</td><td>mianserin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_mianserin/Mianserin_Timmer1985_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>mean plasma clearance of mianserin</td><td>19</td><td>l h-1</td><td><small>CL</small></td></tr><tr><td>kinetic volume of distribution</td><td>444</td><td>l</td><td><small>V</small></td></tr><tr><td>steady-state volume of distribution</td><td>242</td><td>l</td><td><small>Vss</small></td></tr><tr><td>elimination half-life</td><td>33</td><td>h</td><td><small>t1/2z</small></td></tr><tr><td>absolute bioavailability in terms of extent of absorption</td><td>22</td><td>%</td><td><small>Fab</small></td></tr><tr><td>mean absorption half-life</td><td>0.43</td><td>h</td><td><small>t1/2ka </small></td></tr></table><h4>About mianserin</h4><p>Mianserin is an antidepressant used to treat depression. It has been withdrawn in some markets but remains approved and used in others.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q416701\">Wikidata Q416701</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Mianserin\">Mianserin</a>.</p><h4>References</h4><ol><li><p>Timmer CJ et al. (1985). Absolute bioavailability of mianserin tablets and solution in healthy humans. <i>European journal of drug metabolism and pharmacokinetics 10(4):315–323</i>. DOI:<a href=\"https://doi.org/10.1007/BF03189759\">10.1007/BF03189759</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/3830718\">3830718</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Timmer_1985: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 604800, Tolerance = 1e-9, Interval = 1));
end Mianserin_Timmer1985_reference;
