within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01A_CardiacGlycosides.C01AA05_Digoxin;
model Digoxin_Lin2023_reference
  parameter Real Cl_ref = 7.416666666666667e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0369 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Digoxin.M,
    adminMass = 2.5e-07,
    ka = 0.0006361111111111112,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>digoxin</td></tr><tr><td>ATC code:</td><td>C01AA05</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Lin ZQ et al. 2023</td></tr><tr><td>population:</td><td>older patients with heart failure and chronic kidney disease</td></tr><tr><td>measured compound:</td><td>digoxin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_digoxin/Digoxin_Lin2023_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>clearance</td><td>2.67</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>36.9</td><td>L</td><td><small>V</small></td></tr><tr><td>apparent Ka</td><td>2.29</td><td>h−1</td><td><small>kabs</small></td></tr></table><h4>About digoxin</h4><p>Digoxin is a plant-derived cardiac glycoside used for heart conditions such as atrial fibrillation, other arrhythmias, and congestive heart failure. It remains an approved medicine, is listed among WHO essential medicines, and is widely used for these heart conditions.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q422222\">Wikidata Q422222</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Digoxin\">Digoxin</a>.</p><h4>References</h4><ol><li><p>Lin ZQ et al. (2023). Dosage Optimization of Digoxin in Older Patients with Heart Failure and Chronic Kidney Disease: A Population Pharmacokinetic Analysis. <i>Drugs &amp; aging 40(6):539–549</i>. DOI:<a href=\"https://doi.org/10.1007/s40266-023-01026-4\">10.1007/s40266-023-01026-4</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37157010\">37157010</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Lin_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 259200, Tolerance = 1e-9, Interval = 1));
end Digoxin_Lin2023_reference;
