within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics.N02BG06_Nefopam;
model Nefopam_Djerada2014_reference
  parameter Real Cl_ref = 4.805555555555555e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.114 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Nefopam.M,
    adminMass = 1e-05,
    k12 = 0.0001966374269005848,
    k21 = 0.0001077724358974359
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>nefopam</td></tr><tr><td>ATC code:</td><td>N02BG06</td></tr><tr><td>model:</td><td>two compartments, IV dosing <small>(PK_2C)</small></td></tr><tr><td>source:</td><td>Djerada Z et al. 2014</td></tr><tr><td>population:</td><td>elderly patients with or without renal impairment</td></tr><tr><td>measured compound:</td><td>nefopam</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_nefopam/Nefopam_Djerada2014_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>clearance</td><td>17.3</td><td>l h(-1)</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>114</td><td>l</td><td><small>V</small></td></tr><tr><td>intercompartmental clearance</td><td>80.7</td><td>l h(-1)</td><td><small>Q</small></td></tr><tr><td>peripheral volume</td><td>208</td><td>l</td><td><small>V2</small></td></tr></table><h4>About nefopam</h4><p>Nefopam is a non-opioid painkiller used to relieve pain. It is approved in some countries and used mainly in Europe and parts of Asia, but is not available everywhere.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q599052\">Wikidata Q599052</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Nefopam\">Nefopam</a>.</p><h4>References</h4><ol><li><p>Djerada Z et al. (2014). Population pharmacokinetics of nefopam in elderly, with or without renal impairment, and its link to treatment response. <i>British journal of clinical pharmacology 77(6):1027–1038</i>. DOI:<a href=\"https://doi.org/10.1111/bcp.12291\">10.1111/bcp.12291</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/24252055\">24252055</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Djerada_2014: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Nefopam_Djerada2014_reference;
