within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A12C_OtherMineralSupplements.A12CC30_MagnesiumDifferentSaltsInCombina;
model MagnesiumDifferentSaltsInCombination_Deng2024_reference
  parameter Real Cl_ref = 8.277777777777777e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.025070000000000002 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 0.005
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>magnesium_different_salts_in_combination</td></tr><tr><td>ATC code:</td><td>A12CC30</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Deng J et al. 2024</td></tr><tr><td>population:</td><td>Chinese preeclampsia population</td></tr><tr><td>measured compound:</td><td>magnesium</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_magnesium_different_salts_in_combination/MagnesiumDifferentSaltsInCombination_Deng2024_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>tvV(L)</td><td>25.07</td><td>L</td><td><small>V</small></td></tr><tr><td>tvCL (L/h)</td><td>2.98</td><td>L/h</td><td><small>CL</small></td></tr></table><h4>About magnesium_different_salts_in_combination</h4><p>Magnesium salts in combination are used as mineral supplements to correct or prevent magnesium deficiency. They are classified under mineral supplements in the ATC system and are generally available as supplements.</p><p><small><b>Unverified</b> — written by glm-5.3-flash from general knowledge (no Wikidata entry found) and the WHO ATC classification; not checked by a person.</small></p><h4>References</h4><ol><li><p>Deng J et al. (2024). Population pharmacokinetics and dose optimization of magnesium sulfate in Chinese preeclampsia population. <i>BMC pregnancy and childbirth 24(1):424</i>. DOI:<a href=\"https://doi.org/10.1186/s12884-024-06620-x\">10.1186/s12884-024-06620-x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38872116\">38872116</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Deng_2024: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 108000, Tolerance = 1e-9, Interval = 1));
end MagnesiumDifferentSaltsInCombination_Deng2024_reference;
