within Pharmacolibrary.Drugs.C_CardiovascularSystem.C04A_PeripheralVasodilators.C04AD04_EtofyllineNicotinate;
model EtofyllineNicotinate_Zuidema1981_reference
  parameter Real Cl_ref = 2.061111111111111e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.041999999999999996 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.EtofyllineNicotinate.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>etofylline_nicotinate</td></tr><tr><td>ATC code:</td><td>C04AD04</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Zuidema J et al. 1981</td></tr><tr><td>population:</td><td>healthy volunteers</td></tr><tr><td>measured compound:</td><td>etofylline</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>beta</td><td>0.175</td><td>h(-1)</td><td><small>kel</small></td></tr><tr><td>beta-phase half-life</td><td>4.1</td><td>h</td><td><small>t1/2β</small></td></tr><tr><td>mean volume of distribution</td><td>0.6</td><td>liter/kg</td><td><small>V</small></td></tr><tr><td>total body clearance</td><td>0.106</td><td>l.kg(-1).h(-1)</td><td><small>CL</small></td></tr><tr><td>renal clearance</td><td>0.017</td><td>l.kg(-1).h(-1)</td><td><small>CLR</small></td></tr><tr><td>bioavailability</td><td>80</td><td>%</td><td><small>Fab</small></td></tr></table><h4>About etofylline_nicotinate</h4><p>Etofylline nicotinate is a purine-derivative compound classified as a peripheral vasodilator, indicating use for circulatory problems in the limbs. It appears only as an experimental drug and is not an approved medicine in the European Union, so its current use is unclear.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q15408405\">Wikidata Q15408405</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.EtofyllineNicotinate\">EtofyllineNicotinate</a>.</p><h4>References</h4><ol><li><p>Zuidema J et al. (1981). Pharmacokinetics of etofylline after intravenous and oral administration to humans. <i>International journal of clinical pharmacology, therapy, and toxicology 19(7):310–313</i>. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/7263108\">7263108</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Zuidema_1981: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end EtofyllineNicotinate_Zuidema1981_reference;
