within Pharmacolibrary.Drugs.N_NervousSystem.N02A_Opioids.N02AF01_Butorphanol;
model Butorphanol_Pypendop2021_reference
  parameter Real Cl_ref = 2.1466666666666662e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.016169999999999997 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Butorphanol.M,
    adminMass = 7e-05,
    k12 = 0.01228715728715729,
    k21 = 0.0025944546008531385
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>butorphanol</td></tr><tr><td>ATC code:</td><td>N02AF01</td></tr><tr><td>model:</td><td>two compartments, IV dosing <small>(PK_2C)</small></td></tr><tr><td>source:</td><td>Pypendop BH et al. 2021</td></tr><tr><td>population:</td><td>male neutered cats anesthetized with isoflurane</td></tr><tr><td>measured compound:</td><td>butorphanol</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_butorphanol/Butorphanol_Pypendop2021_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>V1 (ml/kg)</td><td>231</td><td>ml/kg</td><td><small>V1</small></td></tr><tr><td>V2 (ml/kg)</td><td>1094</td><td>ml/kg</td><td><small>V2</small></td></tr><tr><td>V3 (ml/kg)</td><td>2596</td><td>ml/kg</td><td><small>V3</small></td></tr><tr><td>Vss (ml/kg)</td><td>3921</td><td>ml/kg</td><td><small>Vss</small></td></tr><tr><td>CL (ml/min/kg)</td><td>18.4</td><td>ml/min/kg</td><td><small>CL</small></td></tr><tr><td>CL2 (ml/min/kg)</td><td>170.3</td><td>ml/min/kg</td><td><small>Q</small></td></tr><tr><td>CL3 (ml/min/kg)</td><td>55.0</td><td>ml/min/kg</td><td><small>CLnorm</small></td></tr><tr><td>T1/2α (min)</td><td>0.6</td><td>min</td><td><small>t1/2α</small></td></tr><tr><td>T1/2β (min)</td><td>12.4</td><td>min</td><td><small>t1/2β</small></td></tr><tr><td>T1/2γ (min)</td><td>172</td><td>min</td><td><small>t1/2γ</small></td></tr></table><h4>About butorphanol</h4><p>Butorphanol is an opioid painkiller used to treat pain, including migraine, and can also act as a cough suppressant. It is an approved medicine in human and veterinary use, though not authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q1185089\">Wikidata Q1185089</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Butorphanol\">Butorphanol</a>.</p><h4>References</h4><ol><li><p>Pypendop BH et al. (2021). Pharmacokinetics of butorphanol in male neutered cats anesthetized with isoflurane. <i>Journal of veterinary pharmacology and therapeutics 44(6):883–887</i>. DOI:<a href=\"https://doi.org/10.1111/jvp.13014\">10.1111/jvp.13014</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34558086\">34558086</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Pypendop_2021: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Butorphanol_Pypendop2021_reference;
