within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B05X_IVSolutionAdditives.B05XA07_CalciumChloride;
model CalciumChloride "CalciumChloride — default model: CalciumChloride"
  extends Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A12A_Calcium.A12AA07_CalciumChloride.CalciumChloride;
  annotation (Documentation(info = "<html><body><p>calcium chloride under ATC B05XA07: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A12A_Calcium.A12AA07_CalciumChloride\">A12AA07_CalciumChloride</a> (ATC A12AA07); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end CalciumChloride;
