within Pharmacolibrary.Drugs.S_SensoryOrgans.S01A_Antiinfectives.S01AE05_Levofloxacin;
model Levofloxacin "Levofloxacin — default model: Levofloxacin"
  extends Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01M_QuinoloneAntibacterials.J01MA12_Levofloxacin.Levofloxacin;
  annotation (Documentation(info = "<html><body><p>levofloxacin under ATC S01AE05: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01M_QuinoloneAntibacterials.J01MA12_Levofloxacin\">J01MA12_Levofloxacin</a> (ATC J01MA12); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Levofloxacin;
