within Pharmacolibrary.Drugs.N_NervousSystem.N03A_Antiepileptics.N03AE01_Clonazepam;
model Clonazepam_Kruizinga2022_reference
  parameter Real Cl_ref = 4.444444444444445e-08 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0115 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Clonazepam.M,
    adminMass = 5e-07,
    k12 = 0.00027053140096618356,
    k21 = 0.00024117140396210163
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>clonazepam</td></tr><tr><td>ATC code:</td><td>N03AE01</td></tr><tr><td>model:</td><td>two compartments, IV dosing <small>(PK_2C)</small></td></tr><tr><td>source:</td><td>Kruizinga MD et al. 2022</td></tr><tr><td>population:</td><td>healthy adults</td></tr><tr><td>measured compound:</td><td>clonazepam</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_clonazepam/Clonazepam_Kruizinga2022_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>θ V D central (L)</td><td>11.5</td><td>L</td><td><small>V1</small></td></tr><tr><td>θ clearance (L h−1)</td><td>0.16</td><td>L h−1</td><td><small>CL</small></td></tr><tr><td>θ V D peripheral (L)</td><td>12.9</td><td>L</td><td><small>V2</small></td></tr><tr><td>θ Q (L h−1)</td><td>11.2</td><td>L h−1</td><td><small>Q</small></td></tr><tr><td>θ K el saliva (h−1)</td><td>0.12</td><td>h−1</td><td><small>kel</small></td></tr><tr><td>θ RatioKM (μg/L)</td><td>0.74</td><td>μg/L</td><td><small>Km</small></td></tr></table><h4>About clonazepam</h4><p>Clonazepam is a benzodiazepine anticonvulsant used to treat epilepsy, including myoclonic and childhood absence epilepsy, as well as panic disorder, anxiety, insomnia, and restless legs syndrome. It is an approved medicine used widely in clinical practice, though it carries a boxed warning and also has investigational and illicit uses.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q407988\">Wikidata Q407988</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Clonazepam\">Clonazepam</a>.</p><h4>References</h4><ol><li><p>Kruizinga MD et al. (2022). Population pharmacokinetics of clonazepam in saliva and plasma: Steps towards noninvasive pharmacokinetic studies in vulnerable populations. <i>British journal of clinical pharmacology 88(5):2236–2245</i>. DOI:<a href=\"https://doi.org/10.1111/bcp.15152\">10.1111/bcp.15152</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34811788\">34811788</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Kruizinga_2022: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 950400, Tolerance = 1e-9, Interval = 1));
end Clonazepam_Kruizinga2022_reference;
