within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B01A_AntithromboticAgents.B01AA07_Acenocoumarol;
model Acenocoumarol_Delavenne2009_reference
  parameter Real Cl_ref = 1.1333333333333334e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.329 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Acenocoumarol.M,
    adminMass = 8e-06,
    ka = 0.0011222222222222222,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>acenocoumarol</td></tr><tr><td>ATC code:</td><td>B01AA07</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Delavenne X et al. 2009</td></tr><tr><td>population:</td><td>healthy volunteers</td></tr><tr><td>measured compound:</td><td>acenocoumarol</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_acenocoumarol/Acenocoumarol_Delavenne2009_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Cl (L/h)</td><td>4.08</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>V 2 (L)</td><td>24.5</td><td>L</td><td><small>V2</small></td></tr><tr><td>Q (L/h)</td><td>1.8</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>Ka (/h)</td><td>4.04</td><td>/h</td><td><small>kabs</small></td></tr><tr><td>volume of distribution</td><td>4.7</td><td>L/kg</td><td><small>V</small></td></tr></table><h4>About acenocoumarol</h4><p>Acenocoumarol is an anticoagulant, a vitamin K antagonist used to prevent and treat blood clots. It is an approved medicine and is used mainly in Europe, where it is often preferred over warfarin in some countries.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q304088\">Wikidata Q304088</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Acenocoumarol\">Acenocoumarol</a>.</p><h4>References</h4><ol><li><p>Delavenne X et al. (2009). Investigation of PK-PD drug-drug interaction between acenocoumarol and amoxicillin plus clavulanic acid. <i>Fundamental &amp; clinical pharmacology 23(1):127–135</i>. DOI:<a href=\"https://doi.org/10.1111/j.1472-8206.2008.00642.x\">10.1111/j.1472-8206.2008.00642.x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/19267776\">19267776</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Delavenne_2009: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 1036800, Tolerance = 1e-9, Interval = 1));
end Acenocoumarol_Delavenne2009_reference;
