within Pharmacolibrary.Drugs.C_CardiovascularSystem.C08C_SelectiveCalciumChannelBlockersWithMainlyVascula.C08CA06_Nimodipine;
model Nimodipine_Foucher2025_reference
  parameter Real Cl_ref = 1.5222222222222223e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.314 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Nimodipine.M,
    adminMass = 5e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>nimodipine</td></tr><tr><td>ATC code:</td><td>C08CA06</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Foucher A et al. 2025</td></tr><tr><td>population:</td><td>adults with subarachnoid hemorrhage</td></tr><tr><td>measured compound:</td><td>nimodipine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_nimodipine/Nimodipine_Foucher2025_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Volume of distribution (L)</td><td>314.0</td><td>L</td><td><small>V</small></td></tr><tr><td>Nimodipine clearance (L/h)</td><td>54.8</td><td>L/h</td><td><small>CL</small></td></tr></table><h4>About nimodipine</h4><p>Nimodipine is a calcium channel blocker used to treat subarachnoid hemorrhage. It is an approved drug that remains in use, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q421429\">Wikidata Q421429</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Nimodipine\">Nimodipine</a>.</p><h4>References</h4><ol><li><p>Foucher A et al. (2025). Impact of cerebral vasospasm therapy on nimodipine exposure in subarachnoid hemorrhage: A population pharmacokinetic study. <i>Journal of the neurological sciences 479:125666</i>. DOI:<a href=\"https://doi.org/10.1016/j.jns.2025.125666\">10.1016/j.jns.2025.125666</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/41289763\">41289763</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Foucher_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Nimodipine_Foucher2025_reference;
