within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain.H02AB06_Prednisolone;
model Prednisolone_Bouazza2025_reference
  parameter Real Cl_ref = 0.0010558333333333333 "Cl [m3/s]";
  parameter Real Vd_ref = 16.45 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Prednisolone.M,
    adminMass = 1e-05,
    ka = 0.00033055555555555556,
    Tlag = 612.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>prednisolone</td></tr><tr><td>ATC code:</td><td>H02AB06</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Bouazza N et al. 2025</td></tr><tr><td>population:</td><td>systemic lupus erythematosus patients</td></tr><tr><td>measured compound:</td><td>prednisolone</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_prednisolone/Prednisolone_Bouazza2025_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Tlag (h)</td><td>0.17</td><td>h</td><td><small>tlag</small></td></tr><tr><td>ka (h−1)</td><td>1.19</td><td>h−1</td><td><small>kabs</small></td></tr><tr><td>CLU/F (L.h−1.70 kg−1)</td><td>54.3</td><td>L.h−1.70 kg−1</td><td><small>CLm/F</small></td></tr><tr><td>VU/F (L.70 kg−1)</td><td>235</td><td>L.70 kg−1</td><td><small>V/F</small></td></tr></table><h4>About prednisolone</h4><p>Prednisolone is a glucocorticoid steroid used to treat inflammatory and autoimmune conditions such as ulcerative colitis, myasthenia gravis, nephrotic syndrome, and various eye, skin, and blood disorders. It is widely used in human medicine, appears on the WHO essential medicines list, and is also approved for veterinary use.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q11426176\">Wikidata Q11426176</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Prednisolone\">Prednisolone</a>.</p><h4>References</h4><ol><li><p>Bouazza N et al. (2025). Population pharmacokinetic modelling of prednisolone in systemic lupus erythematosus patients: Analysis of exposure and disease activity. <i>British journal of clinical pharmacology 91(10):2854–2864</i>. DOI:<a href=\"https://doi.org/10.1002/bcp.70103\">10.1002/bcp.70103</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/40411119\">40411119</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Bouazza_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Prednisolone_Bouazza2025_reference;
