within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07A_BetaBlockingAgents.C07AA05_Propranolol;
model Propranolol_Takechi2018_reference
  parameter Real Cl_ref = 2.594444444444444e-06 "Cl [m3/s]";
  parameter Real cov_age_0 = 0 "age covariate";
  parameter Real cov_age = 1.0 "age covariate (reference 1.0)";
  parameter Real Vd_ref = 0.146 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref*(1 + (0.0583)*cov_age_0)*(cov_age/1.0)^(1.0),
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Propranolol.M,
    adminMass = 7e-05,
    ka = 0.0002861111111111111,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>propranolol</td></tr><tr><td>ATC code:</td><td>C07AA05</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Takechi T et al. 2018</td></tr><tr><td>population:</td><td>infants with infantile hemangioma</td></tr><tr><td>measured compound:</td><td>propranolol</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_propranolol/Propranolol_Takechi2018_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F (L/h)</td><td>9.34</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>V/F (L)</td><td>146</td><td>L</td><td><small>V/F</small></td></tr><tr><td>k a (h -1 )</td><td>1.03</td><td>h -1</td><td><small>kabs</small></td></tr><tr><td>gestational_age_days_on</td><td>0.0583</td><td></td><td><small>equation variable</small></td></tr><tr><td>theta_cl_f_age_power</td><td>1</td><td></td><td><small>equation variable</small></td></tr></table><h4>About propranolol</h4><p>Propranolol is a non-selective beta blocker used for conditions such as high blood pressure, angina, heart rhythm problems, migraine, anxiety, essential tremor, and infantile hemangioma. It remains widely used, is listed among WHO essential medicines, and is authorised in the European Union, where an approved product is indicated for hemangioma.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q423364\">Wikidata Q423364</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Propranolol\">Propranolol</a>.</p><h4>References</h4><ol><li><p>Takechi T et al. (2018). Population Pharmacokinetics and Pharmacodynamics of Oral Propranolol in Pediatric Patients With Infantile Hemangioma. <i>Journal of clinical pharmacology 58(10):1361–1370</i>. DOI:<a href=\"https://doi.org/10.1002/jcph.1149\">10.1002/jcph.1149</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29746707\">29746707</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Takechi_2018: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 259200, Tolerance = 1e-9, Interval = 1));
end Propranolol_Takechi2018_reference;
