within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07A_BetaBlockingAgents.C07AA05_Propranolol;
model Propranolol_Salehifar2017_this_study
  parameter Real Cl_ref = 3.830555555555556e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.3577000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Propranolol.M,
    adminMass = 4e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>propranolol</td></tr><tr><td>ATC code:</td><td>C07AA05</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Salehifar E et al. 2017</td></tr><tr><td>population:</td><td>healthy adults</td></tr><tr><td>measured compound:</td><td>propranolol</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_propranolol/Propranolol_Salehifar2017_this_study\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Cl (Lit/kg/hr)</td><td>1.97</td><td>L/kg/h</td><td><small>CL</small></td></tr><tr><td>Vd (Lit/kg)</td><td>5.11</td><td>L/kg</td><td><small>V</small></td></tr><tr><td>t 1/2 (hr)</td><td>1.98</td><td>hr</td><td><small>t1/2z</small></td></tr></table><h4>About propranolol</h4><p>Propranolol is a non-selective beta blocker used for conditions such as high blood pressure, angina, heart rhythm problems, migraine, anxiety, essential tremor, and infantile hemangioma. It remains widely used, is listed among WHO essential medicines, and is authorised in the European Union, where an approved product is indicated for hemangioma.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q423364\">Wikidata Q423364</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Propranolol\">Propranolol</a>.</p><h4>References</h4><ol><li><p>Salehifar E et al. (2017). Pharmacokinetic Parameters and Over-Responsiveness of Iranian Population to Propranolol. <i>Advanced pharmaceutical bulletin 7(2):195–202</i>. DOI:<a href=\"https://doi.org/10.15171/apb.2017.024\">10.15171/apb.2017.024</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28761821\">28761821</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Salehifar_2017: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Propranolol_Salehifar2017_this_study;
