within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L04A_Immunosuppressants.L04AX03_Methotrexate;
model Methotrexate_Bremnes1989_reference
  parameter Real Cl_ref = 2.1194444444444444e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.35000000000000003 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Methotrexate.M,
    adminMass = 2.5e-06,
    ka = 3.101851851851852e-06,
    Tlag = 1296.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>methotrexate</td></tr><tr><td>ATC code:</td><td>L04AX03</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Bremnes RM et al. 1989</td></tr><tr><td>population:</td><td>rats</td></tr><tr><td>measured compound:</td><td>methotrexate</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_methotrexate/Methotrexate_Bremnes1989_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>7-OH-MTX concentrations in bile declined monophasically with a half-life of</td><td>29.4</td><td>min</td><td><small>t1/2z</small></td></tr><tr><td>Serum concentration curves were analyzed according to a three-compartment open model with an initial elimination half-life of</td><td>1.7</td><td>min</td><td><small>t1/2α</small></td></tr><tr><td>CL</td><td>7.63</td><td>L/hour</td><td><small>CL</small></td></tr><tr><td>Vd threshold</td><td>5.0</td><td>L/kg</td><td><small>V</small></td></tr><tr><td>absorption rate constant</td><td>0.268</td><td>day−1</td><td><small>kabs</small></td></tr><tr><td>t lag,oral</td><td>0.36</td><td>hour</td><td><small>tlag</small></td></tr></table><h4>About methotrexate</h4><p>Methotrexate is a folic acid antagonist used as an anticancer drug for various cancers such as leukemia and lymphoma, and as an immunosuppressive disease-modifying antirheumatic drug for conditions like rheumatoid arthritis, psoriasis, and other inflammatory diseases. It is widely used and is included on the WHO essential medicines list; in the European Union several products are authorised for psoriasis and various forms of arthritis.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q422232\">Wikidata Q422232</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Methotrexate\">Methotrexate</a>.</p><h4>References</h4><ol><li><p>Bremnes RM et al. (1989). Formation and elimination of 7-hydroxymethotrexate in the rat in vivo after methotrexate administration. <i>Cancer research 49(9):2460–2464</i>. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/2706634\">2706634</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Bremnes_1989: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 1036800, Tolerance = 1e-9, Interval = 1));
end Methotrexate_Bremnes1989_reference;
