within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L04A_Immunosuppressants.L04AX03_Methotrexate;
model Methotrexate_Blackman2026_reference
  parameter Real Cl_ref = 2.1194444444444444e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.35000000000000003 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Methotrexate.M,
    adminMass = 2.5e-06,
    ka = 3.101851851851852e-06,
    Tlag = 1296.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>methotrexate</td></tr><tr><td>ATC code:</td><td>L04AX03</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Blackman MH et al. 2026</td></tr><tr><td>population:</td><td>adults with acute lymphoblastic leukemia, osteosarcoma, and lymphoma</td></tr><tr><td>measured compound:</td><td>methotrexate</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_methotrexate/Methotrexate_Blackman2026_reference\">pharmacolibrary-docs</a></td></tr></table><h4>About methotrexate</h4><p>Methotrexate is a folic acid antagonist used as an anticancer drug for various cancers such as leukemia and lymphoma, and as an immunosuppressive disease-modifying antirheumatic drug for conditions like rheumatoid arthritis, psoriasis, and other inflammatory diseases. It is widely used and is included on the WHO essential medicines list; in the European Union several products are authorised for psoriasis and various forms of arthritis.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q422232\">Wikidata Q422232</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Methotrexate\">Methotrexate</a>.</p><h4>References</h4><ol><li><p>Blackman MH et al. (2026). Development and validation of high-dose methotrexate population pharmacokinetic models to inform clinical decisions on dosing. <i>European journal of clinical pharmacology 82(6):156</i>. DOI:<a href=\"https://doi.org/10.1007/s00228-026-04080-0\">10.1007/s00228-026-04080-0</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/42174327\">42174327</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Blackman_2026: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 1555200, Tolerance = 1e-9, Interval = 1));
end Methotrexate_Blackman2026_reference;
