within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L04A_Immunosuppressants.L04AX03_Methotrexate;
model Methotrexate_Yu2025_reference
  parameter Real Cl_ref = 1.175e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.01384 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Methotrexate.M,
    adminMass = 2.5e-06,
    ka = 3.101851851851852e-06,
    Tlag = 1296.0,
    k12 = 2.4887604367373153e-06,
    k21 = 7.043853669620541e-06
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>methotrexate</td></tr><tr><td>ATC code:</td><td>L04AX03</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Yu B et al. 2025</td></tr><tr><td>population:</td><td>pediatric patients with acute lymphoblastic leukemia</td></tr><tr><td>measured compound:</td><td>methotrexate</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_methotrexate/Methotrexate_Yu2025_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>θCL age&gt;1 (L/h)</td><td>4.23</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>θQ (L/h)</td><td>0.124</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>θV1 (L)</td><td>13.84</td><td>L</td><td><small>V1</small></td></tr><tr><td>θV2 (L)</td><td>4.89</td><td>L</td><td><small>V2</small></td></tr><tr><td>θGFR</td><td>0.354</td><td></td><td><small>equation variable</small></td></tr><tr><td>θBSA</td><td>0.76</td><td></td><td><small>equation variable</small></td></tr><tr><td>θWT</td><td>0.35</td><td></td><td><small>equation variable</small></td></tr><tr><td>θBUN</td><td>-0.1553</td><td></td><td><small>equation variable</small></td></tr><tr><td>absorption rate constant</td><td>0.268</td><td>day−1</td><td><small>kabs</small></td></tr><tr><td>t lag,oral</td><td>0.36</td><td>hour</td><td><small>tlag</small></td></tr></table><h4>About methotrexate</h4><p>Methotrexate is a folic acid antagonist used as an anticancer drug for various cancers such as leukemia and lymphoma, and as an immunosuppressive disease-modifying antirheumatic drug for conditions like rheumatoid arthritis, psoriasis, and other inflammatory diseases. It is widely used and is included on the WHO essential medicines list; in the European Union several products are authorised for psoriasis and various forms of arthritis.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q422232\">Wikidata Q422232</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Methotrexate\">Methotrexate</a>.</p><h4>References</h4><ol><li><p>Yu B et al. (2025). Population Pharmacokinetics and Covariate Analysis of Methotrexate in Pediatric Acute Lymphoblastic Leukemia. <i>Drug design, development and therapy 19:8475–8488</i>. DOI:<a href=\"https://doi.org/10.2147/DDDT.S545368\">10.2147/DDDT.S545368</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/40989247\">40989247</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Yu_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 1036800, Tolerance = 1e-9, Interval = 1));
end Methotrexate_Yu2025_reference;
