within Pharmacolibrary.Drugs.S_SensoryOrgans.S03A_Antiinfectives.S03AA03_PolymyxinB;
model PolymyxinB "PolymyxinB — default model: PolymyxinB"
  extends Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07A_IntestinalAntiinfectives.A07AA05_PolymyxinB.PolymyxinB;
  annotation (Documentation(info = "<html><body><p>polymyxin B under ATC S03AA03: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07A_IntestinalAntiinfectives.A07AA05_PolymyxinB\">A07AA05_PolymyxinB</a> (ATC A07AA05); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end PolymyxinB;
