within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01F_MacrolidesLincosamidesAndStreptogramins.J01FA09_Clarithromycin;
model Clarithromycin_Shah2025_reference
  parameter Real Cl_ref = 2.2694444444444446e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0257 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Clarithromycin.M,
    adminMass = 0.0005
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>clarithromycin</td></tr><tr><td>ATC code:</td><td>J01FA09</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Shah RV et al. 2025</td></tr><tr><td>population:</td><td>critically ill adults</td></tr><tr><td>measured compound:</td><td>clarithromycin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_clarithromycin/Clarithromycin_Shah2025_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>θCL (L/h/70 kg)</td><td>8.17</td><td>L/h/70 kg</td><td><small>CL</small></td></tr><tr><td>θV1 (L/70 kg)</td><td>25.7</td><td>L/70 kg</td><td><small>V</small></td></tr><tr><td>θQ (L/h/70 kg)</td><td>62.0</td><td>L/h/70 kg</td><td><small>Q</small></td></tr></table><h4>About clarithromycin</h4><p>Clarithromycin is a macrolide antibiotic used to treat many bacterial infections, including respiratory, skin, ear, and throat infections, and to help eradicate Helicobacter pylori in peptic ulcer disease. It is widely used in human medicine and appears on the WHO list of essential medicines, though it carries a boxed warning.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q118551\">Wikidata Q118551</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Clarithromycin\">Clarithromycin</a>.</p><h4>References</h4><ol><li><p>Shah RV et al. (2025). Intravenous Clarithromycin in Critically Ill Adults: A Population Pharmacokinetic Study. <i>Antibiotics (Basel, Switzerland) 14(6)</i>. DOI:<a href=\"https://doi.org/10.3390/antibiotics14060559\">10.3390/antibiotics14060559</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/40558149\">40558149</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Shah_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Clarithromycin_Shah2025_reference;
