within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01X_OtherAntibacterials.J01XA01_Vancomycin;
model Vancomycin "Vancomycin — default model: Vancomycin"
  extends Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07A_IntestinalAntiinfectives.A07AA09_Vancomycin.Vancomycin;
  annotation (Documentation(info = "<html><body><p>vancomycin under ATC J01XA01: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07A_IntestinalAntiinfectives.A07AA09_Vancomycin\">A07AA09_Vancomycin</a> (ATC A07AA09); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Vancomycin;
