within Pharmacolibrary.Drugs.N_NervousSystem.N06A_Antidepressants.N06AX21_Duloxetine;
model Duloxetine_Skinner2004_reference
  parameter Real Cl_ref = 1.4611111111111112e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.9540000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Duloxetine.M,
    adminMass = 2e-05,
    ka = 7.138888888888889e-05,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>duloxetine</td></tr><tr><td>ATC code:</td><td>N06AX21</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Skinner MH et al. 2004</td></tr><tr><td>population:</td><td>women with urinary incontinence and healthy women</td></tr><tr><td>measured compound:</td><td>duloxetine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_duloxetine/Duloxetine_Skinner2004_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F (l h -1 )</td><td>52.6</td><td>l h -1</td><td><small>CL/F</small></td></tr><tr><td>V/F (l)</td><td>954</td><td>l</td><td><small>V/F</small></td></tr><tr><td>Ka (h -1 )</td><td>0.257</td><td>h -1</td><td><small>kabs</small></td></tr></table><h4>About duloxetine</h4><p>Duloxetine is an antidepressant (a serotonin–norepinephrine reuptake inhibitor) used for major depressive disorder, anxiety disorders, and nerve-related pain conditions such as diabetic neuropathy and fibromyalgia. It is approved and widely used, with several products authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q411932\">Wikidata Q411932</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Duloxetine\">Duloxetine</a>.</p><h4>References</h4><ol><li><p>Skinner MH et al. (2004). Effect of age on the pharmacokinetics of duloxetine in women. <i>British journal of clinical pharmacology 57(1):54–61</i>. DOI:<a href=\"https://doi.org/10.1046/j.1365-2125.2003.01963.x\">10.1046/j.1365-2125.2003.01963.x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/14678340\">14678340</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Skinner_2004: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 345600, Tolerance = 1e-9, Interval = 1));
end Duloxetine_Skinner2004_reference;
