within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10A_LipidModifyingAgentsPlain.C10AA07_Rosuvastatin;
model Rosuvastatin_Macpherson2016_final_final_model
  parameter Real Cl_ref = 3.5833333333333335e-05 "Cl [m3/s]";
  parameter Real cov_weight = 42.0 "weight covariate (reference 42.0)";
  parameter Real Vd_ref = 0.303 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref*(cov_weight/42.0)^(0.352),
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Rosuvastatin.M,
    adminMass = 5e-06,
    ka = 5.0833333333333333e-05,
    Tlag = 0.0,
    k12 = 8.241657499083243e-05,
    k21 = 4.846152187506739e-06
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>rosuvastatin</td></tr><tr><td>ATC code:</td><td>C10AA07</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Macpherson M et al. 2016</td></tr><tr><td>population:</td><td>pediatric patients with heterozygous familial hypercholesterolemia</td></tr><tr><td>measured compound:</td><td>rosuvastatin</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Ka (h-1)</td><td>0.183</td><td>h-1</td><td><small>kabs</small></td></tr><tr><td>CL/F (L/h)</td><td>129</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>Vc/F (L)</td><td>303</td><td>L</td><td><small>V1/F</small></td></tr><tr><td>Q/F (L/h)</td><td>89.9</td><td>L/h</td><td><small>Q/F</small></td></tr><tr><td>Vp/F (L)</td><td>5153</td><td>L</td><td><small>V2/F</small></td></tr><tr><td>theta_cl_f_weight_power</td><td>0.352</td><td></td><td><small>equation variable</small></td></tr></table><h4>About rosuvastatin</h4><p>Rosuvastatin is a statin used to treat lipid metabolism disorders such as hypercholesterolemia, atherosclerosis, and related heart disease. It is an approved medicine, widely used, and also available in fixed combinations with other lipid-modifying agents.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q415159\">Wikidata Q415159</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Rosuvastatin\">Rosuvastatin</a>.</p><h4>References</h4><ol><li><p>Macpherson M et al. (2016). Population pharmacokinetics of rosuvastatin in pediatric patients with heterozygous familial hypercholesterolemia. <i>European journal of clinical pharmacology 72(1):19–27</i>. DOI:<a href=\"https://doi.org/10.1007/s00228-015-1946-4\">10.1007/s00228-015-1946-4</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26387811\">26387811</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Macpherson_2016: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 90000, Tolerance = 1e-9, Interval = 1));
end Rosuvastatin_Macpherson2016_final_final_model;
