within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02A_AntiadrenergicAgentsCentrallyActing.C02AC05_Moxonidine;
model Moxonidine_Hempel1998_reference
  parameter Real Cl_ref = 9.722222222222223e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.132 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Moxonidine.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>moxonidine</td></tr><tr><td>ATC code:</td><td>C02AC05</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Hempel G et al. 1998</td></tr><tr><td>population:</td><td>patients with hypertension</td></tr><tr><td>measured compound:</td><td>moxonidine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_moxonidine/Moxonidine_Hempel1998_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>mean moxonidine clearance</td><td>35</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>132</td><td>L</td><td><small>V</small></td></tr></table><h4>About moxonidine</h4><p>Moxonidine is an antihypertensive drug used to treat high blood pressure. It is an approved medicine, used mainly in Europe, and is also available in combination with a diuretic.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q419944\">Wikidata Q419944</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Moxonidine\">Moxonidine</a>.</p><h4>References</h4><ol><li><p>Hempel G et al. (1998). Population pharmacokinetic-pharmacodynamic modeling of moxonidine using 24-hour ambulatory blood pressure measurements. <i>Clinical pharmacology and therapeutics 64(6):622–635</i>. DOI:<a href=\"https://doi.org/10.1016/S0009-9236(98)90053-4\">10.1016/S0009-9236(98)90053-4</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/9871427\">9871427</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Hempel_1998: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Moxonidine_Hempel1998_reference;
