within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07A_IntestinalAntiinfectives.A07AA08_Kanamycin;
model Kanamycin_Strydom2019v2_reference
  parameter Real Cl_ref = 1.2805555555555557e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.030600000000000002 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Kanamycin.M,
    adminMass = 0.003,
    ka = 0.0004583333333333333,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>kanamycin</td></tr><tr><td>ATC code:</td><td>A07AA08</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Strydom N et al. 2019</td></tr><tr><td>population:</td><td>adults with tuberculosis</td></tr><tr><td>measured compound:</td><td>kanamycin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_kanamycin/Kanamycin_Strydom2019v2_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Rate of absorption (h−1)</td><td>1.65</td><td>h−1</td><td><small>kabs</small></td></tr><tr><td>Clearance (L/h)</td><td>4.61</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Central volume (L)</td><td>30.6</td><td>L</td><td><small>V</small></td></tr></table><h4>About kanamycin</h4><p>Kanamycin is an antibiotic used to treat bacterial infections, including gram-negative infections, upper respiratory tract infections, hepatic coma, and tuberculosis. It remains in use, with approved and veterinary-approved status, and is also being investigated for additional uses.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q421951\">Wikidata Q421951</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Kanamycin\">Kanamycin</a>.</p><h4>References</h4><ol><li><p>Strydom N et al. (2019). Tuberculosis drugs' distribution and emergence of resistance in patient's lung lesions: A mechanistic model and tool for regimen and dose optimization. <i>PLoS medicine 16(4):e1002773</i>. DOI:<a href=\"https://doi.org/10.1371/journal.pmed.1002773\">10.1371/journal.pmed.1002773</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30939136\">30939136</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Strydom_2019_2: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Kanamycin_Strydom2019v2_reference;
