within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07A_IntestinalAntiinfectives.A07AA08_Kanamycin;
model Kanamycin_Chang2017v2_reference
  parameter Real Cl_ref = 2.602777777777778e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.05670000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Kanamycin.M,
    adminMass = 0.003,
    ka = 8.472222222222222e-05,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>kanamycin</td></tr><tr><td>ATC code:</td><td>A07AA08</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Chang MJ et al. 2017</td></tr><tr><td>population:</td><td>patients with multi-drug-resistant tuberculosis</td></tr><tr><td>measured compound:</td><td>kanamycin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_kanamycin/Kanamycin_Chang2017v2_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>absorption rate constant</td><td>0.305</td><td>/h</td><td><small>kabs</small></td></tr><tr><td>apparent clearance</td><td>9.37</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>apparent volume of distribution</td><td>56.7</td><td>L</td><td><small>V/F</small></td></tr></table><h4>About kanamycin</h4><p>Kanamycin is an antibiotic used to treat bacterial infections, including gram-negative infections, upper respiratory tract infections, hepatic coma, and tuberculosis. It remains in use, with approved and veterinary-approved status, and is also being investigated for additional uses.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q421951\">Wikidata Q421951</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Kanamycin\">Kanamycin</a>.</p><h4>References</h4><ol><li><p>Chang MJ et al. (2017). Population pharmacokinetics of moxifloxacin, cycloserine, p-aminosalicylic acid and kanamycin for the treatment of multi-drug-resistant tuberculosis. <i>International journal of antimicrobial agents 49(6):677–687</i>. DOI:<a href=\"https://doi.org/10.1016/j.ijantimicag.2017.01.024\">10.1016/j.ijantimicag.2017.01.024</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28408267\">28408267</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Chang_2017_2: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 111600, Tolerance = 1e-9, Interval = 1));
end Kanamycin_Chang2017v2_reference;
