within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins.A10BJ02_Liraglutide;
model Liraglutide_Carlsson2021_reference
  parameter Real Cl_ref = 2.9722222222222224e-07 "Cl [m3/s]";
  parameter Real cov_sex_0 = 0 "sex covariate";
  parameter Real cov_age_1 = 0 "age covariate";
  parameter Real cov_age_2 = 0 "age covariate";
  parameter Real Vd_ref = 0.0131 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref*(1 + (1.12)*cov_sex_0)*(1 + (1.11)*cov_age_1)*(1 + (1.06)*cov_age_2),
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Liraglutide.M,
    adminMass = 3e-06,
    ka = 2.2333333333333332e-05,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>liraglutide</td></tr><tr><td>ATC code:</td><td>A10BJ02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Carlsson Petri KC et al. 2021</td></tr><tr><td>population:</td><td>children, adolescents and adults with obesity</td></tr><tr><td>measured compound:</td><td>liraglutide</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Absorption rate constant</td><td>0.0804</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>Apparent clearance</td><td>1.07</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>Apparent volume of distribution</td><td>13.1</td><td>L</td><td><small>V/F</small></td></tr><tr><td>sex_contrast_male_female_on_cl_f</td><td>1.12</td><td></td><td><small>equation variable</small></td></tr><tr><td>age_contrast_child_adult_on_cl_f</td><td>1.11</td><td></td><td><small>equation variable</small></td></tr><tr><td>age_contrast_adolescent_adult_on_cl_f</td><td>1.06</td><td></td><td><small>equation variable</small></td></tr><tr><td>theta_q319_body_weight_power</td><td>0.762</td><td></td><td><small>equation variable</small></td></tr><tr><td>theta_q319_body_weight_power</td><td>0.587</td><td></td><td><small>equation variable</small></td></tr></table><h4>About liraglutide</h4><p>Liraglutide is a GLP-1 analogue used as an anti-diabetic medicine to treat type 2 diabetes and glucose intolerance, and is also authorised for obesity and overweight. It is approved and authorised in the European Union, and is widely used for diabetes care.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q2526479\">Wikidata Q2526479</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Liraglutide\">Liraglutide</a>.</p><h4>References</h4><ol><li><p>Carlsson Petri KC et al. (2021). Liraglutide pharmacokinetics and exposure-response in adolescents with obesity. <i>Pediatric obesity 16(10):e12799</i>. DOI:<a href=\"https://doi.org/10.1111/ijpo.12799\">10.1111/ijpo.12799</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33963681\">33963681</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Carlsson_2021: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 345600, Tolerance = 1e-9, Interval = 1));
end Liraglutide_Carlsson2021_reference;
