within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02K_OtherAntihypertensives.C02KD01_Ketanserin;
model Ketanserin_Michiels1988_reference
  parameter Real Cl_ref = 4.433333333333333e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.046900000000000004 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Ketanserin.M,
    adminMass = 4e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>ketanserin</td></tr><tr><td>ATC code:</td><td>C02KD01</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Michiels M et al. 1988</td></tr><tr><td>population:</td><td>rats, rabbits and dogs</td></tr><tr><td>measured compound:</td><td>ketanserin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_ketanserin/Ketanserin_Michiels1988_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>plasma clearance (C1)</td><td>3.8</td><td>ml/min/kg</td><td><small>CL</small></td></tr><tr><td>volume of distribution (Vdss)</td><td>0.67</td><td>l/kg</td><td><small>V</small></td></tr><tr><td>absolute bioavailability of oral ketanserin</td><td>80</td><td>%</td><td><small>Fab</small></td></tr><tr><td>apparent elimination half-life of ketanserin</td><td>1.5</td><td>h</td><td><small>t1/2z</small></td></tr></table><h4>About ketanserin</h4><p>Ketanserin is a serotonin antagonist that has been used as an antihypertensive drug and to treat chronic skin ulcers. It is currently considered investigational and is not an approved medicine in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q415997\">Wikidata Q415997</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Ketanserin\">Ketanserin</a>.</p><h4>References</h4><ol><li><p>Michiels M et al. (1988). Pharmacokinetics and tissue distribution of ketanserin in rat, rabbit and dog. <i>Arzneimittel-Forschung 38(6):775–784</i>. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/3178917\">3178917</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Michiels_1988: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Ketanserin_Michiels1988_reference;
