within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02K_OtherAntihypertensives.C02KD01_Ketanserin;
model Ketanserin_Trenk1983_reference
  parameter Real Cl_ref = 7.583333333333334e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.231 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Ketanserin.M,
    adminMass = 4e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>ketanserin</td></tr><tr><td>ATC code:</td><td>C02KD01</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Trenk D et al. 1983</td></tr><tr><td>population:</td><td>healthy volunteers</td></tr><tr><td>measured compound:</td><td>ketanserin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_ketanserin/Ketanserin_Trenk1983_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>mean terminal half-life</td><td>15.6</td><td>h</td><td><small>t1/2z</small></td></tr><tr><td>Total clearance</td><td>0.39</td><td>L/kg/h</td><td><small>CL</small></td></tr><tr><td>volume of distribution at steady state</td><td>3.3</td><td>L/kg</td><td><small>Vss</small></td></tr><tr><td>bioavailability</td><td>0.51</td><td></td><td><small>Fab</small></td></tr></table><h4>About ketanserin</h4><p>Ketanserin is a serotonin antagonist that has been used as an antihypertensive drug and to treat chronic skin ulcers. It is currently considered investigational and is not an approved medicine in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q415997\">Wikidata Q415997</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Ketanserin\">Ketanserin</a>.</p><h4>References</h4><ol><li><p>Trenk D et al. (1983). Pharmacokinetics and pharmacodynamics of the 5-HT2 receptor antagonist ketanserin in man. <i>Journal of cardiovascular pharmacology 5(6):1034–1039</i>. DOI:<a href=\"https://doi.org/10.1097/00005344-198311000-00018\">10.1097/00005344-198311000-00018</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/6196551\">6196551</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Trenk_1983: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 345600, Tolerance = 1e-9, Interval = 1));
end Ketanserin_Trenk1983_reference;
