within Pharmacolibrary.Drugs.N_NervousSystem.N05C_HypnoticsAndSedatives.N05CD08_Midazolam;
model Midazolam_Maitre1991_reference
  parameter Real Cl_ref = 7.777777777777777e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0858 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Midazolam.M,
    adminMass = 1.5e-05,
    ka = 3.888888888888889e-05,
    Tlag = 4428.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>midazolam</td></tr><tr><td>ATC code:</td><td>N05CD08</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Maitre PO et al. 1991</td></tr><tr><td>population:</td><td>adults</td></tr><tr><td>measured compound:</td><td>midazolam</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_midazolam/Midazolam_Maitre1991_reference\">pharmacolibrary-docs</a></td></tr></table><h4>About midazolam</h4><p>Midazolam is a benzodiazepine sedative used for conscious sedation, anesthesia, and to treat severe seizures such as status epilepticus. It is an authorised medicine in the European Union and is included on the WHO essential medicines list, so it is widely used.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q423071\">Wikidata Q423071</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Midazolam\">Midazolam</a>.</p><h4>References</h4><ol><li><p>Maitre PO et al. (1991). A three-step approach combining Bayesian regression and NONMEM population analysis: application to midazolam. <i>Journal of pharmacokinetics and biopharmaceutics 19(4):377–384</i>. DOI:<a href=\"https://doi.org/10.1007/BF01061662\">10.1007/BF01061662</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/1920085\">1920085</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Maitre_1991: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 118800, Tolerance = 1e-9, Interval = 1));
end Midazolam_Maitre1991_reference;
