within Pharmacolibrary.Drugs.N_NervousSystem.N05C_HypnoticsAndSedatives.N05CD08_Midazolam;
model Midazolam_Burtin1994_mean_estimate_se_index_data_set
  parameter Real Cl_ref = 2.566666666666667e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.034929999999999996 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Midazolam.M,
    adminMass = 1.5e-05,
    ka = 3.888888888888889e-05,
    Tlag = 4428.0,
    k12 = 8.827178165855523e-06,
    k21 = 0.0005079626578802857
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>midazolam</td></tr><tr><td>ATC code:</td><td>N05CD08</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Burtin P et al. 1994</td></tr><tr><td>population:</td><td>critically ill neonates</td></tr><tr><td>measured compound:</td><td>midazolam</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_midazolam/Midazolam_Burtin1994_mean_estimate_se_index_data_set\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL (L/hr/kg)</td><td>0.132</td><td>L/hr/kg</td><td><small>CL</small></td></tr><tr><td>Vc (L/kg)</td><td>0.499</td><td>L/kg</td><td><small>V1</small></td></tr><tr><td>Vp (L)</td><td>0.607</td><td>L</td><td><small>V2</small></td></tr><tr><td>Q (L/hr)</td><td>1.11</td><td>L/hr</td><td><small>Q</small></td></tr><tr><td>Ka (1/h)</td><td>0.14</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>Lag time (h)</td><td>0.08</td><td>h</td><td><small>tlag</small></td></tr></table><h4>About midazolam</h4><p>Midazolam is a benzodiazepine sedative used for conscious sedation, anesthesia, and to treat severe seizures such as status epilepticus. It is an authorised medicine in the European Union and is included on the WHO essential medicines list, so it is widely used.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q423071\">Wikidata Q423071</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Midazolam\">Midazolam</a>.</p><h4>References</h4><ol><li><p>Burtin P et al. (1994). Population pharmacokinetics of midazolam in neonates. <i>Clinical pharmacology and therapeutics 56(6 Pt 1):615–625</i>. DOI:<a href=\"https://doi.org/10.1038/clpt.1994.186\">10.1038/clpt.1994.186</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/7995003\">7995003</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Burtin_1994: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 126000, Tolerance = 1e-9, Interval = 1));
end Midazolam_Burtin1994_mean_estimate_se_index_data_set;
