within Pharmacolibrary.Drugs.N_NervousSystem.N05C_HypnoticsAndSedatives.N05CD08_Midazolam;
model Midazolam_McCann2025_reference
  parameter Real Cl_ref = 4.077777777777778e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.00709 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Midazolam.M,
    adminMass = 2e-06,
    ka = 3.888888888888889e-05,
    Tlag = 4428.0,
    k12 = 0.001751684688920232,
    k21 = 0.00036452728043570424
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>midazolam</td></tr><tr><td>ATC code:</td><td>N05CD08</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>McCann S et al. 2025</td></tr><tr><td>population:</td><td>children with and without obesity</td></tr><tr><td>measured compound:</td><td>midazolam</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_midazolam/Midazolam_McCann2025_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL (L/h/70 kg)</td><td>14.68</td><td>L/h/70 kg</td><td><small>CL</small></td></tr><tr><td>V1 (L/70 kg)</td><td>7.09</td><td>L/70 kg</td><td><small>V1</small></td></tr><tr><td>Q (L/h/70 kg)</td><td>44.71</td><td>L/h/70 kg</td><td><small>Q</small></td></tr><tr><td>V2 (L/70 kg)</td><td>34.07</td><td>L/70 kg</td><td><small>V2</small></td></tr><tr><td>Ka (1/h)</td><td>0.14</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>Lag time (h)</td><td>0.08</td><td>h</td><td><small>tlag</small></td></tr></table><h4>About midazolam</h4><p>Midazolam is a benzodiazepine sedative used for conscious sedation, anesthesia, and to treat severe seizures such as status epilepticus. It is an authorised medicine in the European Union and is included on the WHO essential medicines list, so it is widely used.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q423071\">Wikidata Q423071</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Midazolam\">Midazolam</a>.</p><h4>References</h4><ol><li><p>McCann S et al. (2025). Physiologically Based and Population Pharmacokinetic Modeling of Midazolam in Children With Obesity Using Real-World Data. <i>Clinical and translational science 18(5):e70247</i>. DOI:<a href=\"https://doi.org/10.1111/cts.70247\">10.1111/cts.70247</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/40364501\">40364501</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from McCann_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Midazolam_McCann2025_reference;
