within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07A_IntestinalAntiinfectives.A07AA09_Vancomycin;
model Vancomycin_Goyal2022_population_typical_value
  parameter Real Cl_ref = 2.7777777777777776e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.005 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Vancomycin.M,
    adminMass = 0.003,
    k12 = 0.0001111111111111111,
    k21 = 0.0001111111111111111
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>vancomycin</td></tr><tr><td>ATC code:</td><td>A07AA09</td></tr><tr><td>model:</td><td>two compartments, IV dosing <small>(PK_2C)</small></td></tr><tr><td>source:</td><td>Goyal RK et al. 2022</td></tr><tr><td>population:</td><td>pregnant women</td></tr><tr><td>measured compound:</td><td>vancomycin</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_vancomycin/Vancomycin_Goyal2022_population_typical_value\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL (L/h)</td><td>1.0</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Vc (L)</td><td>5.0</td><td>L</td><td><small>V1</small></td></tr><tr><td>Q (L/h)</td><td>2.0</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>Vp (L)</td><td>5.0</td><td>L</td><td><small>V2</small></td></tr></table><h4>About vancomycin</h4><p>Vancomycin is a glycopeptide antibiotic used to treat serious bacterial infections, including staphylococcal infections, pneumonia, infective endocarditis, and pseudomembranous colitis. It is an approved medicine and appears on the WHO list of essential medicines, so it is widely used, typically in hospital settings for severe infections.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q424027\">Wikidata Q424027</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Vancomycin\">Vancomycin</a>.</p><h4>References</h4><ol><li><p>Goyal RK et al. (2022). Population Pharmacokinetics of Vancomycin in Pregnant Women. <i>Frontiers in pharmacology 13:873439</i>. DOI:<a href=\"https://doi.org/10.3389/fphar.2022.873439\">10.3389/fphar.2022.873439</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35734401\">35734401</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Goyal_2022: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Vancomycin_Goyal2022_population_typical_value;
