within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07A_IntestinalAntiinfectives.A07AA05_PolymyxinB;
model PolymyxinB_Manchandani2018_reference
  parameter Real Cl_ref = 6.944444444444445e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0343 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 0.00015
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>polymyxin_b</td></tr><tr><td>ATC code:</td><td>A07AA05</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Manchandani P et al. 2018</td></tr><tr><td>population:</td><td>adult patients</td></tr><tr><td>measured compound:</td><td>polymyxin_b</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_polymyxin_b/PolymyxinB_Manchandani2018_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>clearance</td><td>2.5</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Vd</td><td>34.3</td><td>L</td><td><small>V</small></td></tr></table><h4>About polymyxin_b</h4><p>Polymyxin B is an antibiotic used to treat infections caused by susceptible bacteria such as Escherichia coli and Bacteroides, and is also applied as an intestinal antiinfective and in eye and ear preparations. It remains in use, with approved and veterinary-approved status, though it is not an EU-authorised product according to the available data.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q1088175\">Wikidata Q1088175</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.PolymyxinB\">PolymyxinB</a>.</p><h4>References</h4><ol><li><p>Manchandani P et al. (2018). Population Pharmacokinetics of Polymyxin B. <i>Clinical pharmacology and therapeutics 104(3):534–538</i>. DOI:<a href=\"https://doi.org/10.1002/cpt.981\">10.1002/cpt.981</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29238962\">29238962</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Manchandani_2018: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 172800, Tolerance = 1e-9, Interval = 1));
end PolymyxinB_Manchandani2018_reference;
