within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07A_IntestinalAntiinfectives.A07AA05_PolymyxinB;
model PolymyxinB_Li2023_reference
  parameter Real Cl_ref = 6.750000000000001e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.02311 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 0.00015
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>polymyxin_b</td></tr><tr><td>ATC code:</td><td>A07AA05</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Li X et al. 2023</td></tr><tr><td>population:</td><td>adults with liver dysfunction</td></tr><tr><td>measured compound:</td><td>polymyxin_b</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_polymyxin_b/PolymyxinB_Li2023_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>PMB clearance</td><td>2.43</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>23.11</td><td>L</td><td><small>V</small></td></tr></table><h4>About polymyxin_b</h4><p>Polymyxin B is an antibiotic used to treat infections caused by susceptible bacteria such as Escherichia coli and Bacteroides, and is also applied as an intestinal antiinfective and in eye and ear preparations. It remains in use, with approved and veterinary-approved status, though it is not an EU-authorised product according to the available data.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q1088175\">Wikidata Q1088175</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.PolymyxinB\">PolymyxinB</a>.</p><h4>References</h4><ol><li><p>Li X et al. (2023). Population pharmacokinetics of polymyxin B in patients with liver dysfunction. <i>British journal of clinical pharmacology 89(12):3561–3572</i>. DOI:<a href=\"https://doi.org/10.1111/bcp.15855\">10.1111/bcp.15855</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37461291\">37461291</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Li_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 118800, Tolerance = 1e-9, Interval = 1));
end PolymyxinB_Li2023_reference;
