within Pharmacolibrary.Drugs.R_RespiratorySystem.R03A_AdrenergicsInhalants.R03AC02_Salbutamol;
model Salbutamol_Walsh2023_reference
  parameter Real Cl_ref = 1.45e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0017900000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 0.0925,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Salbutamol.M,
    adminMass = 7e-08,
    ka = 0.004638888888888889,
    Tlag = 0.0,
    k12 = 0.0013314711359404096,
    k21 = 0.0003695090439276486
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>salbutamol</td></tr><tr><td>ATC code:</td><td>R03AC02</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Walsh S et al. 2023</td></tr><tr><td>population:</td><td>children with acute asthma</td></tr><tr><td>measured compound:</td><td>salbutamol</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_salbutamol/Salbutamol_Walsh2023_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Bioavailability [0-1]</td><td>0.0925</td><td></td><td><small>Fab</small></td></tr><tr><td>ka (h-1)</td><td>16.7</td><td>h-1</td><td><small>kabs</small></td></tr><tr><td>CL (l/h)</td><td>0.522</td><td>l/h</td><td><small>CL</small></td></tr><tr><td>Vc (l)</td><td>1.79</td><td>l</td><td><small>V1</small></td></tr><tr><td>Q (l/h)</td><td>8.58</td><td>l/h</td><td><small>Q</small></td></tr><tr><td>Vp (l)</td><td>6.45</td><td>l</td><td><small>V2</small></td></tr></table><h4>About salbutamol</h4><p>Salbutamol is a bronchodilator used to treat asthma, bronchospasm and other obstructive lung diseases. It is widely used worldwide, appears on the WHO list of essential medicines, and is available on prescription.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q410358\">Wikidata Q410358</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Salbutamol\">Salbutamol</a>.</p><h4>References</h4><ol><li><p>Walsh S et al. (2023). Optimising intravenous salbutamol in children: a phase 2 study. <i>Archives of disease in childhood 108(4):316–322</i>. DOI:<a href=\"https://doi.org/10.1136/archdischild-2022-324008\">10.1136/archdischild-2022-324008</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36581395\">36581395</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Walsh_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Salbutamol_Walsh2023_reference;
