within Pharmacolibrary.Drugs.R_RespiratorySystem.R03A_AdrenergicsInhalants.R03AC02_Salbutamol;
model Salbutamol_Marques2024v2_reference
  parameter Real Cl_ref = 9.702777777777779e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.16293000000000002 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Salbutamol.M,
    adminMass = 6e-07,
    ka = 0.003763888888888889,
    Tlag = 0.0,
    k12 = 1.8054788354917243e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>salbutamol</td></tr><tr><td>ATC code:</td><td>R03AC02</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Marques L et al. 2024</td></tr><tr><td>population:</td><td>virtual patients and asthma patients</td></tr><tr><td>measured compound:</td><td>salbutamol</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_salbutamol/Salbutamol_Marques2024v2_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>ka (h−1)</td><td>13.55</td><td>h−1</td><td><small>kabs</small></td></tr><tr><td>Cl (L/h)</td><td>34.93</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Q (L/h)</td><td>10.59</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>V2 (L)</td><td>0</td><td>L</td><td><small>V2</small></td></tr><tr><td>V1 (L)</td><td>162.93</td><td>L</td><td><small>V1</small></td></tr></table><h4>About salbutamol</h4><p>Salbutamol is a bronchodilator used to treat asthma, bronchospasm and other obstructive lung diseases. It is widely used worldwide, appears on the WHO list of essential medicines, and is available on prescription.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q410358\">Wikidata Q410358</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Salbutamol\">Salbutamol</a>.</p><h4>References</h4><ol><li><p>Marques L et al. (2024). Toward Personalized Salbutamol Therapy: Validating Virtual Patient-Derived Population Pharmacokinetic Model with Real-World Data. <i>Pharmaceutics 16(7)</i>. DOI:<a href=\"https://doi.org/10.3390/pharmaceutics16070881\">10.3390/pharmaceutics16070881</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39065578\">39065578</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Marques_2024_2: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Salbutamol_Marques2024v2_reference;
