within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins.A10BH07_Evogliptin;
model Evogliptin_Kim2025_reference
  parameter Real Cl_ref = 6.138888888888889e-06 "Cl [m3/s]";
  parameter Real cov_wt = 1.0 "wt covariate (reference 1.0)";
  parameter Real Vd_ref = 0.8290000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref*(cov_wt/1.0)^(0.75),
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Evogliptin.M,
    adminMass = 5e-06,
    ka = 0.00035,
    Tlag = 0.0,
    k12 = 1.551400616539338e-05,
    k21 = 2.7658303464755076e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>evogliptin</td></tr><tr><td>ATC code:</td><td>A10BH07</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Kim B et al. 2025</td></tr><tr><td>population:</td><td>patients with varying degrees of renal disease and healthy subjects</td></tr><tr><td>measured compound:</td><td>evogliptin</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>CL/F (L/h)</td><td>22.1</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>Vc/F (L)</td><td>829.0</td><td>L</td><td><small>V1/F</small></td></tr><tr><td>Ka (/h)</td><td>1.26</td><td>/h</td><td><small>kabs</small></td></tr><tr><td>Q/F (L/h)</td><td>46.3</td><td>L/h</td><td><small>Q/F</small></td></tr><tr><td>Vp/F (L)</td><td>465.0</td><td>L</td><td><small>V2/F</small></td></tr><tr><td>F1c</td><td>1</td><td></td><td><small>Frel</small></td></tr><tr><td>theta_cl_f_wt_power</td><td>0.75</td><td></td><td><small>equation variable</small></td></tr><tr><td>theta_q76_wt_power</td><td>1</td><td></td><td><small>equation variable</small></td></tr><tr><td>theta_q_f_wt_power</td><td>0.75</td><td></td><td><small>equation variable</small></td></tr><tr><td>theta_q76_wt_power</td><td>1</td><td></td><td><small>equation variable</small></td></tr></table><h4>About evogliptin</h4><p>Evogliptin is a DPP-4 inhibitor studied for lowering blood glucose in diabetes. It is considered investigational and is not authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q25103700\">Wikidata Q25103700</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Evogliptin\">Evogliptin</a>.</p><h4>References</h4><ol><li><p>Kim B et al. (2025). Population pharmacokinetic and pharmacodynamic model of evogliptin: Severe uremia increases the bioavailability of evogliptin. <i>CPT: pharmacometrics &amp; systems pharmacology 14(2):246–256</i>. DOI:<a href=\"https://doi.org/10.1002/psp4.13263\">10.1002/psp4.13263</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39465597\">39465597</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Kim_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 518400, Tolerance = 1e-9, Interval = 1));
end Evogliptin_Kim2025_reference;
