within Pharmacolibrary.Drugs.C_CardiovascularSystem.C08C_SelectiveCalciumChannelBlockersWithMainlyVascula.C08CA16_Clevidipine;
model Clevidipine_Vuylsteke2000_reference
  parameter Real Cl_ref = 1.916666666666667e-08 "Cl [m3/s]";
  parameter Real Vd_ref = 0.013300000000000001 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Clevidipine.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>clevidipine</td></tr><tr><td>ATC code:</td><td>C08CA16</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Vuylsteke A et al. 2000</td></tr><tr><td>population:</td><td>patients undergoing cardiac surgery</td></tr><tr><td>measured compound:</td><td>clevidipine</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>clearance</td><td>0.069</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>volume of distribution at steady state</td><td>0.19</td><td>litres kg-1</td><td><small>Vss</small></td></tr><tr><td>total blood clearance of clevidipine</td><td>0.055</td><td>L/h</td><td><small>CLb</small></td></tr></table><h4>About clevidipine</h4><p>Clevidipine is a dihydropyridine calcium channel blocker used to treat arterial hypertension. It is an approved drug, though it does not appear to be authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q5132338\">Wikidata Q5132338</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Clevidipine\">Clevidipine</a>.</p><h4>References</h4><ol><li><p>Vuylsteke A et al. (2000). Pharmacokinetics and pulmonary extraction of clevidipine, a new vasodilating ultrashort-acting dihydropyridine, during cardiopulmonary bypass. <i>British journal of anaesthesia 85(5):683–689</i>. DOI:<a href=\"https://doi.org/10.1093/bja/85.5.683\">10.1093/bja/85.5.683</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/11094580\">11094580</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Vuylsteke_2000: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 2419200, Tolerance = 1e-9, Interval = 1));
end Clevidipine_Vuylsteke2000_reference;
