within Pharmacolibrary.Drugs.C_CardiovascularSystem.C08C_SelectiveCalciumChannelBlockersWithMainlyVascula.C08CA16_Clevidipine;
model Clevidipine_Ericsson2001_reference
  parameter Real Cl_ref = 0.00012016666666666667 "Cl [m3/s]";
  parameter Real Vd_ref = 0.027300000000000005 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>clevidipine</td></tr><tr><td>ATC code:</td><td>C08CA16</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Ericsson H et al. 2001</td></tr><tr><td>population:</td><td>essential hypertensive patients</td></tr><tr><td>measured compound:</td><td>clevidipine enantiomers</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>mean blood clearance values of (-)-R-clevidipine</td><td>0.103</td><td>l/min/kg</td><td><small>CLb</small></td></tr><tr><td>volumes of distribution at steady state of (-)-R-clevidipine</td><td>0.39</td><td>l/kg</td><td><small>Vss</small></td></tr></table><h4>About clevidipine</h4><p>Clevidipine is a dihydropyridine calcium channel blocker used to treat arterial hypertension. It is an approved drug, though it does not appear to be authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q5132338\">Wikidata Q5132338</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Clevidipine\">Clevidipine</a>.</p><h4>References</h4><ol><li><p>Ericsson H et al. (2001). Enantioselective pharmacokinetics of the enantiomers of clevidipine following intravenous infusion of the racemate in essential hypertensive patients. <i>Chirality 13(3):130–134</i>. DOI:<a href=\"https://doi.org/10.1002/1520-636X(2001)13:3<130::AID-CHIR1009>3.0.CO;2-2\">10.1002/1520-636X(2001)13:3&lt;130::AID-CHIR1009&gt;3.0.CO;2-2</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/11270321\">11270321</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Ericsson_2001: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Clevidipine_Ericsson2001_reference;
