within Pharmacolibrary.Drugs.C_CardiovascularSystem.C08C_SelectiveCalciumChannelBlockersWithMainlyVascula.C08CA16_Clevidipine;
model Clevidipine_Bailey2002_reference
  parameter Real Cl_ref = 7.166666666666667e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0324 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Clevidipine.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>clevidipine</td></tr><tr><td>ATC code:</td><td>C08CA16</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Bailey JM et al. 2002</td></tr><tr><td>population:</td><td>adult cardiac surgical patients</td></tr><tr><td>measured compound:</td><td>clevidipine</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>volume of distribution</td><td>32.4</td><td>l</td><td><small>V</small></td></tr><tr><td>clearance</td><td>4.3</td><td>l/min</td><td><small>CL</small></td></tr><tr><td>half-life</td><td>0.6</td><td>min</td><td><small>t1/2z</small></td></tr></table><h4>About clevidipine</h4><p>Clevidipine is a dihydropyridine calcium channel blocker used to treat arterial hypertension. It is an approved drug, though it does not appear to be authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q5132338\">Wikidata Q5132338</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Clevidipine\">Clevidipine</a>.</p><h4>References</h4><ol><li><p>Bailey JM et al. (2002). Clevidipine in adult cardiac surgical patients: a dose-finding study. <i>Anesthesiology 96(5):1086–1094</i>. DOI:<a href=\"https://doi.org/10.1097/00000542-200205000-00010\">10.1097/00000542-200205000-00010</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/11981147\">11981147</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Bailey_2002: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Clevidipine_Bailey2002_reference;
