within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B05A_BloodAndRelatedProducts.B05AA07_Hydroxyethylstarch;
model Hydroxyethylstarch_Yamakage2012_reference
  parameter Real Cl_ref = 3.1666666666666667e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0047599999999999995 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>hydroxyethylstarch</td></tr><tr><td>ATC code:</td><td>B05AA07</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Yamakage M et al. 2012</td></tr><tr><td>population:</td><td>healthy male Japanese volunteers</td></tr><tr><td>measured compound:</td><td>hydroxyethyl starch 130/0.4</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_hydroxyethylstarch/Hydroxyethylstarch_Yamakage2012_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Total plasma clearance</td><td>1.14</td><td>l/h</td><td><small>CL</small></td></tr><tr><td>rapid and slow elimination half-lives</td><td>1.12</td><td>h</td><td><small>t1/2z</small></td></tr><tr><td>volume of distribution</td><td>4.76</td><td>l</td><td><small>V</small></td></tr></table><h4>About hydroxyethylstarch</h4><p>Hydroxyethyl starch is a modified starch used as a blood substitute and plasma volume expander. It remains approved but carries a boxed warning, so its use is restricted to carefully selected patients.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q415775\">Wikidata Q415775</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Hydroxyethylstarch\">Hydroxyethylstarch</a>.</p><h4>References</h4><ol><li><p>Yamakage M et al. (2012). Pharmacokinetics and safety of 6 % hydroxyethyl starch 130/0.4 in healthy male volunteers of Japanese ethnicity after single infusion of 500 ml solution. <i>Journal of anesthesia 26(6):851–857</i>. DOI:<a href=\"https://doi.org/10.1007/s00540-012-1430-6\">10.1007/s00540-012-1430-6</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/22729229\">22729229</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Yamakage_2012: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Hydroxyethylstarch_Yamakage2012_reference;
