within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B05A_BloodAndRelatedProducts.B05AA07_Hydroxyethylstarch;
model Hydroxyethylstarch_Asskali1999_reference
  parameter Real Cl_ref = 8.1e-08 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0217 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Hydroxyethylstarch.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>hydroxyethylstarch</td></tr><tr><td>ATC code:</td><td>B05AA07</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Asskali F et al. 1999</td></tr><tr><td>population:</td><td>healthy volunteers</td></tr><tr><td>measured compound:</td><td>hydroxyethylstarch</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_hydroxyethylstarch/Hydroxyethylstarch_Asskali1999_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>T1/2</td><td>20</td><td>h</td><td><small>t1/2z</small></td></tr><tr><td>Plasma clearance</td><td>4.86</td><td>ml/min</td><td><small>CL</small></td></tr><tr><td>V</td><td>21.7</td><td>L</td><td><small>V</small></td></tr></table><h4>About hydroxyethylstarch</h4><p>Hydroxyethyl starch is a modified starch used as a blood substitute and plasma volume expander. It remains approved but carries a boxed warning, so its use is restricted to carefully selected patients.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q415775\">Wikidata Q415775</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Hydroxyethylstarch\">Hydroxyethylstarch</a>.</p><h4>References</h4><ol><li><p>Asskali F et al. (1999). [The accumulation of different substituted hydroxyethyl starches (HES) following repeated infusions in healthy volunteers]. <i>Anasthesiologie, Intensivmedizin, Notfallmedizin, Schmerztherapie : AINS 34(9):537–541</i>. DOI:<a href=\"https://doi.org/10.1055/s-1999-208\">10.1055/s-1999-208</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/10542895\">10542895</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Asskali_1999: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 432000, Tolerance = 1e-9, Interval = 1));
end Hydroxyethylstarch_Asskali1999_reference;
