within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombina.S01CB02_Prednisolone;
model Prednisolone "Prednisolone — default model: Prednisolone"
  extends Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain.H02AB06_Prednisolone.Prednisolone;
  annotation (Documentation(info = "<html><body><p>prednisolone under ATC S01CB02: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain.H02AB06_Prednisolone\">H02AB06_Prednisolone</a> (ATC H02AB06); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Prednisolone;
