within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis.A02BC01_Omeprazole;
model Omeprazole_Marier2004_reference
  parameter Real Cl_ref = 1.2055555555555555e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.053200000000000004 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Omeprazole.M,
    adminMass = 2e-05,
    ka = 0.00026388888888888886,
    Tlag = 9000.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>omeprazole</td></tr><tr><td>ATC code:</td><td>A02BC01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Marier JF et al. 2004</td></tr><tr><td>population:</td><td>healthy adults and children with gastroesophageal reflux disease</td></tr><tr><td>measured compound:</td><td>omeprazole</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_omeprazole/Omeprazole_Marier2004_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Oral clearance (CL/F) in healthy adults</td><td>0.62</td><td>L/h/kg</td><td><small>CL/F</small></td></tr><tr><td>apparent volume of distribution (V(ss)/F) in healthy adults</td><td>0.76</td><td>L/kg</td><td><small>V/F</small></td></tr><tr><td>K A</td><td>0.95</td><td>h−1</td><td><small>kabs</small></td></tr><tr><td>lag time for the DRT formulation</td><td>2.5</td><td>h</td><td><small>tlag</small></td></tr></table><h4>About omeprazole</h4><p>Omeprazole is a proton-pump inhibitor used for acid-related stomach problems such as reflux disease, ulcers, gastritis, and Zollinger–Ellison syndrome. It is widely used, appears on the WHO essential medicines list, and is approved for both human and veterinary use.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q422210\">Wikidata Q422210</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Omeprazole\">Omeprazole</a>.</p><h4>References</h4><ol><li><p>Marier JF et al. (2004). Pharmacokinetics of omeprazole in healthy adults and in children with gastroesophageal reflux disease. <i>Therapeutic drug monitoring 26(1):3–8</i>. DOI:<a href=\"https://doi.org/10.1097/00007691-200402000-00003\">10.1097/00007691-200402000-00003</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/14749542\">14749542</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Marier_2004: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Omeprazole_Marier2004_reference;
