within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis.A02BC01_Omeprazole;
model Omeprazole_Zhao2018_reference
  parameter Real Q370_5_hydroxy_omeprazole_ref = 1.827777777777778e-07 "θ2 [SI]";
  parameter Real cov_cyp2c19_0 = 0 "cyp2c19 covariate";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_3M_9C(
    Vd1 = 0.000513,
    q1_m11 = Q370_5_hydroxy_omeprazole_ref*(1 + (1.0)*cov_cyp2c19_0),
    q1_m21 = 3.888888888888889e-08,
    CL1 = max(((Q370_5_hydroxy_omeprazole_ref*(1 + (1.0)*cov_cyp2c19_0)) + 3.888888888888889e-08) - ((Q370_5_hydroxy_omeprazole_ref*(1 + (1.0)*cov_cyp2c19_0)) + 3.888888888888889e-08), 0),
    Vd1m1 = 0.001,
    CLm1 = 2.35e-07,
    Vd1m2 = 0.001,
    CLm2 = 3.611111111111111e-08,
    MW = Pharmacolibrary.Drugs.Substances.Omeprazole.M,
    MW_m1 = Pharmacolibrary.Drugs.Substances.Omeprazole.HydroxyOmeprazole5.M,
    MW_m2 = Pharmacolibrary.Drugs.Substances.Omeprazole.OmeprazoleSulfone.M,
    F = 1,
    ka = 0.00026388888888888886,
    Tlag = 9000.0,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 7e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>omeprazole</td></tr><tr><td>ATC code:</td><td>A02BC01</td></tr><tr><td>model:</td><td>parent and metabolites, formed from the central compartment <small>(PK_3M_9C)</small></td></tr><tr><td>source:</td><td>Zhao W et al. 2018</td></tr><tr><td>population:</td><td>neonates and young infants</td></tr><tr><td>measured compound:</td><td>omeprazole</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>V 1 /F (l)</td><td>0.513</td><td>l</td><td><small>V1/F</small></td></tr><tr><td>V 2 /F (l) <small>(5-hydroxy-omeprazole)</small></td><td>1</td><td>l</td><td><small>V1/F</small></td></tr><tr><td>V 3 /F (l) <small>(omeprazole sulfone)</small></td><td>1</td><td>l</td><td><small>V1/F</small></td></tr><tr><td>θ2 <small>(5-hydroxy-omeprazole)</small></td><td>0.658</td><td>L/h</td><td><small>CLfm</small></td></tr><tr><td>f_cyp2c19_em_um <small>(5-hydroxy-omeprazole)</small></td><td>1</td><td></td><td><small>equation variable</small></td></tr><tr><td>CL OMZ-M2 (l h <small>(omeprazole sulfone)</small></td><td>0.140</td><td>L/h</td><td><small>CLfm</small></td></tr><tr><td>CL M1 /F (l h <small>(5-hydroxy-omeprazole)</small></td><td>0.846</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>CL M2 /F (l h <small>(omeprazole sulfone)</small></td><td>0.130</td><td>L/h</td><td><small>CL/F</small></td></tr><tr><td>theta_q49_abcb1</td><td>0.0497</td><td></td><td><small>equation variable</small></td></tr><tr><td>K A</td><td>0.95</td><td>h−1</td><td><small>kabs</small></td></tr><tr><td>lag time for the DRT formulation</td><td>2.5</td><td>h</td><td><small>tlag</small></td></tr></table><h4>About omeprazole</h4><p>Omeprazole is a proton-pump inhibitor used for acid-related stomach problems such as reflux disease, ulcers, gastritis, and Zollinger–Ellison syndrome. It is widely used, appears on the WHO essential medicines list, and is approved for both human and veterinary use.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q422210\">Wikidata Q422210</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Omeprazole\">Omeprazole</a>.</p><h4>References</h4><ol><li><p>Zhao W et al. (2018). Developmental pharmacogenetics of CYP2C19 in neonates and young infants: omeprazole as a probe drug. <i>British journal of clinical pharmacology 84(5):997–1005</i>. DOI:<a href=\"https://doi.org/10.1111/bcp.13526\">10.1111/bcp.13526</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29377228\">29377228</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Zhao_2018: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Omeprazole_Zhao2018_reference;
