within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis.J04AA01_D_4AminosalicylicAcid;
model D_4AminosalicylicAcid_de2014_reference
  parameter Real Cl_ref = 2.6166666666666665e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0518 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 0.004,
    ka = 4.5138888888888894e-05,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>4_aminosalicylic_acid</td></tr><tr><td>ATC code:</td><td>J04AA01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>de_2014</td></tr><tr><td>population:</td><td>tuberculosis patients with and without HIV coinfection receiving antiretroviral therapy</td></tr><tr><td>measured compound:</td><td>para-aminosalicylic acid</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_4_aminosalicylic_acid/D_4AminosalicylicAcid_de2014_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Apparent oral clearance (CL/F, liters/h)</td><td>9.42</td><td>liters/h</td><td><small>CL/F</small></td></tr><tr><td>Apparent volume of distribution (V/F, liters)</td><td>51.8</td><td>liters</td><td><small>V/F</small></td></tr><tr><td>Transit rate constant (K tr , h Ϫ1 )</td><td>0.65</td><td>h Ϫ1</td><td><small>ktr</small></td></tr><tr><td>Number of transit compartments</td><td>3</td><td></td><td><small>n_transit</small></td></tr></table><h4>About 4_aminosalicylic_acid</h4><p>4-Aminosalicylic acid is an antibiotic used to treat tuberculosis and has also been used for Crohn's colitis. It remains in clinical use and is included on the WHO list of essential medicines.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q229924\">Wikidata Q229924</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.AminosalicylicAcid4\">AminosalicylicAcid4</a>.</p><h4>References</h4><ol><li><p>de_2014 (). . <i></i>.</p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from de_2014: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end D_4AminosalicylicAcid_de2014_reference;
