within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01B_Antimetabolites.L01BA01_Methotrexate;
model Methotrexate "Methotrexate — default model: Methotrexate"
  extends Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L04A_Immunosuppressants.L04AX03_Methotrexate.Methotrexate;
  annotation (Documentation(info = "<html><body><p>methotrexate under ATC L01BA01: the same models as <a href=\"modelica://Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L04A_Immunosuppressants.L04AX03_Methotrexate\">L04AX03_Methotrexate</a> (ATC L04AX03); this model is its default.</p></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from default: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: default</li></ul></body></html>"));
end Methotrexate;
