within Pharmacolibrary.Drugs;
package Substances "Identity and physicochemical data of each drug, one package per substance"
  extends Modelica.Icons.Package;
  annotation (Documentation(info = "<html><body><p>One package per drug: its identity (name, ATC codes, DrugBank, PubChem, ChEBI and Wikidata ids), molar mass, logP and metabolites, and a short summary of what the drug is used for. A drug appears in the ATC tree once per ATC code; its data lives here once. Models read the constants directly, e.g. <code>MW = Substances.Clopidogrel.M</code>, <code>MW_m1 = Substances.Clopidogrel.ClopidogrelH4.M</code>.</p><p>Generated by pharmacolibrary-dev (export.pharmacolibrary_substances): molar masses from PubChem, metabolites from the models extracted from papers, summaries written from Wikidata (linked) or flagged unverified. Replaces Drugs.Common.DrugData (removed in 26.09).</p></body></html>"));
end Substances;
