within Pharmacolibrary.Drugs.C_CardiovascularSystem.C08D_SelectiveCalciumChannelBlockersWithDirectCardiac.C08DB01_Diltiazem;
model Diltiazem_Klle1983_reference
  parameter Real Cl_ref = 1.3416666666666668e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 0.063 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Diltiazem.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>diltiazem</td></tr><tr><td>ATC code:</td><td>C08DB01</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Kölle EU et al. 1983</td></tr><tr><td>population:</td><td>healthy subjects</td></tr><tr><td>measured compound:</td><td>diltiazem</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>t1/2 alpha</td><td>0.1</td><td>h</td><td><small>t1/2α</small></td></tr><tr><td>t1/2 beta</td><td>2.1</td><td>h</td><td><small>t1/2β</small></td></tr><tr><td>t1/2 gamma</td><td>9.8</td><td>h</td><td><small>t1/2γ</small></td></tr><tr><td>Vc</td><td>0.9</td><td>l/kg</td><td><small>V</small></td></tr><tr><td>Vss</td><td>5.2</td><td>l/kg</td><td><small>Vss</small></td></tr><tr><td>Cltot</td><td>11.5</td><td>ml/min/kg</td><td><small>CL</small></td></tr><tr><td>mean hepatic extraction ratio</td><td>0.54</td><td>mean</td><td><small>EH</small></td></tr></table><h4>About diltiazem</h4><p>Diltiazem is a calcium channel blocker used to treat high blood pressure, angina, and certain heart rhythm problems such as atrial fibrillation and supraventricular tachycardia. It is an approved medicine and is widely used for these cardiovascular conditions.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q422229\">Wikidata Q422229</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Diltiazem\">Diltiazem</a>.</p><h4>References</h4><ol><li><p>Kölle EU et al. (1983). Pharmacokinetic model of diltiazem. <i>Arzneimittel-Forschung 33(7):972–977</i>. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/6684932\">6684932</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Kölle_1983: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Diltiazem_Klle1983_reference;
