within Pharmacolibrary.Drugs.C_CardiovascularSystem.C08D_SelectiveCalciumChannelBlockersWithDirectCardiac.C08DB01_Diltiazem;
model Diltiazem_Guan2018_reference
  parameter Real Cl_ref = 2.566666666666667e-05 "Cl [m3/s]";
  parameter Real Vd_ref = 3.5500000000000003 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Diltiazem.M,
    adminMass = 0.00024,
    ka = 0.0005444444444444444,
    Tlag = 0.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>diltiazem</td></tr><tr><td>ATC code:</td><td>C08DB01</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Guan XF et al. 2018</td></tr><tr><td>population:</td><td>Chinese renal transplant recipients</td></tr><tr><td>measured compound:</td><td>diltiazem</td></tr><tr><td>review:</td><td>curated candidate</td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>The absorption rate constant (K a)</td><td>1.96</td><td>/h</td><td><small>kabs</small></td></tr><tr><td>V/F</td><td>3550</td><td>L</td><td><small>V/F</small></td></tr><tr><td>apparent oral clearance (CL/F)</td><td>92.4</td><td>L/h</td><td><small>CL/F</small></td></tr></table><h4>About diltiazem</h4><p>Diltiazem is a calcium channel blocker used to treat high blood pressure, angina, and certain heart rhythm problems such as atrial fibrillation and supraventricular tachycardia. It is an approved medicine and is widely used for these cardiovascular conditions.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q422229\">Wikidata Q422229</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Diltiazem\">Diltiazem</a>.</p><h4>References</h4><ol><li><p>Guan XF et al. (2018). Population Pharmacokinetic Modeling of Diltiazem in Chinese Renal Transplant Recipients. <i>European journal of drug metabolism and pharmacokinetics 43(1):55–62</i>. DOI:<a href=\"https://doi.org/10.1007/s13318-017-0425-y\">10.1007/s13318-017-0425-y</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28646274\">28646274</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Guan_2018: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 518400, Tolerance = 1e-9, Interval = 1));
end Diltiazem_Guan2018_reference;
