within Pharmacolibrary.Drugs.N_NervousSystem.N02C_AntimigrainePreparations.N02CD02_Galcanezumab;
model Galcanezumab_FiedlerKelly2021_reference
  parameter Real Cl_ref = 2.9444444444444445e-09 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0112 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 0.0001,
    ka = 5.333333333333333e-06,
    Tlag = 727.2
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>galcanezumab</td></tr><tr><td>ATC code:</td><td>N02CD02</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Fiedler-Kelly J et al. 2021</td></tr><tr><td>population:</td><td>healthy subjects</td></tr><tr><td>measured compound:</td><td>galcanezumab</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_galcanezumab/Galcanezumab_FiedlerKelly2021_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>clearance</td><td>0.0106</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>11.2</td><td>L</td><td><small>V</small></td></tr><tr><td>absorption rate constant</td><td>0.0192</td><td>h-1</td><td><small>kabs</small></td></tr><tr><td>lag time</td><td>0.202</td><td>hours</td><td><small>tlag</small></td></tr><tr><td>elimination half-life</td><td>30</td><td>days</td><td><small>t1/2z</small></td></tr></table><h4>About galcanezumab</h4><p>Galcanezumab is a humanized monoclonal antibody used to prevent migraine attacks. It is an approved medicine, authorised in the European Union for migraine, and is also under investigation for other uses.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q25326707\">Wikidata Q25326707</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Galcanezumab\">Galcanezumab</a>.</p><h4>References</h4><ol><li><p>Fiedler-Kelly J et al. (2021). Relationship of the Calcitonin Gene-Related Peptide Monoclonal Antibody Galcanezumab Pharmacokinetics and Capsaicin-Induced Dermal Blood Flow in Healthy Subjects. <i>Clinical pharmacology in drug development 10(5):440–452</i>. DOI:<a href=\"https://doi.org/10.1002/cpdd.929\">10.1002/cpdd.929</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33740315\">33740315</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Fiedler-Kelly_2021: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Galcanezumab_FiedlerKelly2021_reference;
