within Pharmacolibrary.Drugs.N_NervousSystem.N05A_Antipsychotics.N05AX16_Brexpiprazole;
model Brexpiprazole_Wang2023_reference
  parameter Real Cl_ref = 3.722222222222222e-07 "Cl [m3/s]";
  parameter Real Vd_ref = 0.078 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_2C_enteral(
    weight = 70.0,
    F = 0.9,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Brexpiprazole.M,
    adminMass = 1e-06,
    ka = 0.0004138888888888889,
    Tlag = 0.0,
    k12 = 3.005698005698006e-06,
    k21 = 8.525252525252525e-06
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>brexpiprazole</td></tr><tr><td>ATC code:</td><td>N05AX16</td></tr><tr><td>model:</td><td>two compartments, oral dosing <small>(PK_2C_enteral)</small></td></tr><tr><td>source:</td><td>Wang Y et al. 2023</td></tr><tr><td>population:</td><td>adults, adolescents, and children with CNS disorders</td></tr><tr><td>measured compound:</td><td>brexpiprazole</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_brexpiprazole/Brexpiprazole_Wang2023_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>D 1 (hour)</td><td>0.931</td><td>hour</td><td><small>D1</small></td></tr><tr><td>k a (1/h)</td><td>1.49</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>CL (L/h)</td><td>1.34</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>V c (L)</td><td>78.0</td><td>L</td><td><small>V1</small></td></tr><tr><td>Q (L/h)</td><td>0.844</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>V p (L)</td><td>27.5</td><td>L</td><td><small>V2</small></td></tr></table><h4>About brexpiprazole</h4><p>Brexpiprazole is an antipsychotic used to treat schizophrenia, and has also been studied for conditions such as anxiety, psychosis and schizoaffective disorder. It is an approved medicine, authorised in the European Union for schizophrenia.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q2924764\">Wikidata Q2924764</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Brexpiprazole\">Brexpiprazole</a>.</p><h4>References</h4><ol><li><p>Wang Y et al. (2023). Population Pharmacokinetic Analysis of Brexpiprazole to Support its Indication and Dose Selection in Adolescents With Schizophrenia. <i>Journal of clinical pharmacology 63(11):1290–1299</i>. DOI:<a href=\"https://doi.org/10.1002/jcph.2307\">10.1002/jcph.2307</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37461192\">37461192</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Wang_2023: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 777600, Tolerance = 1e-9, Interval = 1));
end Brexpiprazole_Wang2023_reference;
