within Pharmacolibrary.Drugs.N_NervousSystem.N05A_Antipsychotics.N05AX16_Brexpiprazole;
model Brexpiprazole_Frederiksen2023v3_reference
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_3M_9C(
    Vd1 = 0.08120000000000001,
    Vd2 = 0.040100000000000004,
    q12 = 1.9833333333333332e-07,
    q21 = 1.9833333333333332e-07,
    q1_m11 = 3.111111111111111e-07,
    q1_m21 = 6.222222222222222e-09,
    CL1 = 0.0,
    Vd1m1 = 0.00244,
    CLm1 = 9.25e-07,
    Vd1m2 = 0.000447,
    CLm2 = 1.1666666666666667e-07,
    Vd2m2 = 0.020399999999999998,
    qm21_m22 = 6e-07,
    qm22_m21 = 6e-07,
    MW = Pharmacolibrary.Drugs.Substances.Brexpiprazole.M,
    MW_m1 = Pharmacolibrary.Drugs.Substances.Brexpiprazole.DM3411.M,
    MW_m2 = Pharmacolibrary.Drugs.Substances.Brexpiprazole.DM3412.M,
    F = 0.9,
    ka = 0.00028333333333333335,
    Tlag = 1479.6,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 1.5e-07
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>brexpiprazole</td></tr><tr><td>ATC code:</td><td>N05AX16</td></tr><tr><td>model:</td><td>parent and metabolites, formed from the central compartment <small>(PK_3M_9C)</small></td></tr><tr><td>source:</td><td>Frederiksen T et al. 2023</td></tr><tr><td>population:</td><td>healthy subjects and patients</td></tr><tr><td>measured compound:</td><td>brexpiprazole</td></tr><tr><td>review:</td><td>accepted with caveats</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_brexpiprazole/Brexpiprazole_Frederiksen2023v3_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Absorption rate constant fasted</td><td>1.02</td><td>1/h</td><td><small>kabs</small></td></tr><tr><td>Lag‐time</td><td>0.411</td><td>h</td><td><small>tlag</small></td></tr><tr><td>Volume of distribution, brexpiprazole central compartment (V2)</td><td>81.2</td><td>L</td><td><small>V1</small></td></tr><tr><td>Volume of distribution, brexpiprazole peripheral compartment (V3)</td><td>40.1</td><td>L</td><td><small>V2</small></td></tr><tr><td>Inter‐compartmental clearance, brexpiprazole (Q)</td><td>0.714</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>Clearance from brexpiprazole to DM‐3412 (CLM1) <small>(DM-3412)</small></td><td>0.0224</td><td>L/h</td><td><small>CLfm</small></td></tr><tr><td>Clearance from brexpiprazole to DM‐3411 (CLM2) <small>(DM-3411)</small></td><td>1.12</td><td>L/h</td><td><small>CLfm</small></td></tr><tr><td>Volume of distribution, DM‐3412 central compartment (V4) <small>(DM-3412)</small></td><td>0.447</td><td>L</td><td><small>V1</small></td></tr><tr><td>Volume of distribution, DM‐3412 peripheral compartment (V5) <small>(DM-3412)</small></td><td>20.4</td><td>L</td><td><small>V2</small></td></tr><tr><td>Inter‐compartmental clearance, DM‐3412 (QMET) <small>(DM-3412)</small></td><td>2.16</td><td>L/h</td><td><small>Q</small></td></tr><tr><td>Clearance from DM‐3412 central compartment (CLMET1) <small>(DM-3412)</small></td><td>0.420</td><td>L/h</td><td><small>CL</small></td></tr><tr><td>Volume of distribution, DM‐3411 central compartment (V6) <small>(DM-3411)</small></td><td>2.44</td><td>L</td><td><small>V</small></td></tr><tr><td>Clearance from DM‐3411 central compartment (CLMET2) <small>(DM-3411)</small></td><td>3.33</td><td>L/h</td><td><small>CL</small></td></tr></table><h4>About brexpiprazole</h4><p>Brexpiprazole is an antipsychotic used to treat schizophrenia, and has also been studied for conditions such as anxiety, psychosis and schizoaffective disorder. It is an approved medicine, authorised in the European Union for schizophrenia.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q2924764\">Wikidata Q2924764</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Brexpiprazole\">Brexpiprazole</a>.</p><h4>References</h4><ol><li><p>Frederiksen T et al. (2023). Estimating the In Vivo Function of CYP2D6 Alleles through Population Pharmacokinetic Modeling of Brexpiprazole. <i>Clinical pharmacology and therapeutics 113(2):360–369</i>. DOI:<a href=\"https://doi.org/10.1002/cpt.2791\">10.1002/cpt.2791</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36350097\">36350097</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Frederiksen_2023_3: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: accepted with caveats</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Brexpiprazole_Frederiksen2023v3_reference;
