within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics.N02BG10_Cannabinoids;
model Cannabinoids_chov2025_s_hhc_population_pk_model
  parameter Real Cl_ref = 1.0366944444444445e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0019259 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C_enteral(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    adminMass = 0.0007,
    ka = 0.00011388888888888888,
    Tlag = 1764.0
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>cannabinoids</td></tr><tr><td>ATC code:</td><td>N02BG10</td></tr><tr><td>model:</td><td>one compartment, oral dosing <small>(PK_1C_enteral)</small></td></tr><tr><td>source:</td><td>Šíchová K et al. 2025</td></tr><tr><td>population:</td><td>male Wistar rats</td></tr><tr><td>measured compound:</td><td>hexahydrocannabinol</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_cannabinoids/Cannabinoids_chov2025_s_hhc_population_pk_model\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>Tlag (h)</td><td>0.49</td><td>h</td><td><small>tlag</small></td></tr><tr><td>Ka (h−1)</td><td>0.41</td><td>h−1</td><td><small>kabs</small></td></tr><tr><td>Vd/F (mL)</td><td>1925.9</td><td>mL</td><td><small>V/F</small></td></tr><tr><td>CL/F (mL/h)</td><td>3732.1</td><td>mL/h</td><td><small>CL/F</small></td></tr></table><h4>About cannabinoids</h4><p>JWH-018 is a synthetic cannabinoid that was used recreationally as an ingredient in herbal smoking mixtures sold as legal alternatives to cannabis. It is no longer used because it was found to be harmful and was made a controlled substance in many countries.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q419020\">Wikidata Q419020</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Cannabinoids\">Cannabinoids</a>.</p><h4>References</h4><ol><li><p>Šíchová K et al. (2025). Hexahydrocannabinol: pharmacokinetics, systemic toxicity, and acute behavioral effects in Wistar rats. <i>The international journal of neuropsychopharmacology 28(8):pyaf041</i>. DOI:<a href=\"https://doi.org/10.1093/ijnp/pyaf041\">10.1093/ijnp/pyaf041</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/40643195\">40643195</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Šíchová_2025: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Cannabinoids_chov2025_s_hhc_population_pk_model;
