within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L04A_Immunosuppressants.L04AX01_Azathioprine;
model Azathioprine_elYazigi1993_reference
  parameter Real Cl_ref = 1.840277777777778e-09 "Cl [m3/s]";
  parameter Real Vd_ref = 0.05831 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Azathioprine.M,
    adminMass = 2.5e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>azathioprine</td></tr><tr><td>ATC code:</td><td>L04AX01</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>el-Yazigi A et al. 1993</td></tr><tr><td>population:</td><td>renal transplant patients</td></tr><tr><td>measured compound:</td><td>azathioprine</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_azathioprine/Azathioprine_elYazigi1993_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>1</td><td>0.833</td><td>L/kg</td><td><small>V</small></td></tr><tr><td>IFX CL</td><td>0.27</td><td>L/d</td><td><small>CL</small></td></tr></table><h4>About azathioprine</h4><p>Azathioprine is an immunosuppressive drug used for autoimmune conditions such as Crohn's disease, ulcerative colitis, rheumatoid arthritis, lupus, and to prevent graft rejection. It is widely used, appears on the WHO essential medicines list, and is authorised in the European Union.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q18939\">Wikidata Q18939</a> and the WHO ATC classification and the EMA medicines list; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Azathioprine\">Azathioprine</a>.</p><h4>References</h4><ol><li><p>el-Yazigi A et al. (1993). Pharmacokinetics of azathioprine after repeated oral and single intravenous administration. <i>Journal of clinical pharmacology 33(6):522–526</i>. DOI:<a href=\"https://doi.org/10.1002/j.1552-4604.1993.tb04698.x\">10.1002/j.1552-4604.1993.tb04698.x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/8366177\">8366177</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from el-Yazigi_1993: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 15552000, Tolerance = 1e-9, Interval = 1));
end Azathioprine_elYazigi1993_reference;
