within Pharmacolibrary.Pharmacodynamic;
model SigmoidEmaxEffect "instant Sigmoid Emax effect"
  extends Pharmacolibrary.Interfaces.PartialEffect;
  parameter Real E0(unit = "1")=0 "baseline effect";
  parameter Real Emax(unit = "1") "maximal effect";
  parameter Real h(unit = "1") "Hill exponent";
  parameter Pharmacolibrary.Types.MassConcentration c50 "concentration producing 50% of Emax";
equation
  E = E0+Emax*Ce^h/(c50^h + Ce^h);
  annotation(
    Icon(graphics = {Text(origin = {-4, -72}, extent = {{-108, 54}, {108, -54}}, textString = "%name"), Line(origin = {1.9, 33.9}, points = {{-95.9004, -49.9004}, {-15.9004, -47.9004}, {14.0996, 50.0996}, {90.0996, 50.0996}, {96.0996, 50.0996}}, color = {53, 132, 228}, thickness = 3, smooth = Smooth.Bezier), Line(origin = {-44, 34}, points = {{10, 50}, {102, 50}}, arrow = {Arrow.None, Arrow.Half}), Text(origin = {-133, 85}, extent = {{-89, 17}, {89, -17}}, textString = "Emax=%Emax", horizontalAlignment = TextAlignment.Left), Text(origin = {-133, -11}, extent = {{-89, 17}, {89, -17}}, textString = "E0=%E0", horizontalAlignment = TextAlignment.Left), Text(origin = {-133, -39}, extent = {{-89, 17}, {89, -17}}, textString = "EC50=%c50", horizontalAlignment = TextAlignment.Left), Line(origin = {54, -62}, rotation = 90, points = {{22, 50}, {102, 50}}, arrow = {Arrow.None, Arrow.Half}), Line(origin = {-34, -40}, points = {{-38, 0}, {38, 0}}), Text(origin = {-133, 31}, extent = {{-89, 17}, {89, -17}}, textString = "Hill=%h", horizontalAlignment = TextAlignment.Left), Text(origin = {-133, -39}, extent = {{-89, 17}, {89, -17}}, textString = "EC50=%c50", horizontalAlignment = TextAlignment.Left)}, coordinateSystem(initialScale = 0.1)),
    Documentation(info = "<html><head></head><body><h1 style=\"font-family: 'DejaVu Sans Mono';\">SigmoidEmaxEffect</h1><div style=\"font-family: 'DejaVu Sans Mono'; font-size: 12px;\">instant Sigmoid Emax effect model. Effect E is calculated using an equation</div><div style=\"font-family: 'DejaVu Sans Mono'; font-size: 12px;\"><br></div><div style=\"font-family: 'DejaVu Sans Mono'; font-size: 12px;\">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Emax * c<sup>h</sup></div><div style=\"font-family: 'DejaVu Sans Mono'; font-size: 12px;\">E = E0 + -----------</div><div style=\"font-family: 'DejaVu Sans Mono'; font-size: 12px;\">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; c50<sup>h&nbsp;</sup>+ c<sup>h</sup></div><div style=\"font-family: 'DejaVu Sans Mono'; font-size: 12px;\"><br></div><div style=\"font-family: 'DejaVu Sans Mono'; font-size: 12px;\">where c is the free concentration (either tissue or blood/plasma, depending on the switch) at the BloodTissueConcentrationPort connector.</div><h2 style=\"font-family: 'DejaVu Sans Mono';\">Parameters</h2><div style=\"font-family: 'DejaVu Sans Mono'; font-size: 12px;\">E0 - baseline effect without drug influence</div><div style=\"font-family: 'DejaVu Sans Mono'; font-size: 12px;\">Emax - maximal effect caused by drug</div><div style=\"font-family: 'DejaVu Sans Mono'; font-size: 12px;\">c50 - concentration producing half maximum effect</div><div style=\"font-family: 'DejaVu Sans Mono'; font-size: 12px;\">h - hill coefficient</div><div style=\"font-family: 'DejaVu Sans Mono'; font-size: 12px;\"><br></div></body></html>"),
  Diagram(graphics));
end SigmoidEmaxEffect;