within Pharmacolibrary.Drugs.N_NervousSystem.N06A_Antidepressants.N06AG03_Toloxatone;
model Toloxatone_Vistelle1992_reference
  parameter Real Cl_ref = 1.3166666666666666e-06 "Cl [m3/s]";
  parameter Real Vd_ref = 0.0058 "Vd [m3]";
  extends Pharmacolibrary.Pharmacokinetic.Models.PK_1C(
    weight = 70.0,
    F = 1,
    Cl = Cl_ref,
    Vd = Vd_ref,
    adminDuration = 600,
    adminCount = 1,
    MM = Pharmacolibrary.Drugs.Substances.Toloxatone.M,
    adminMass = 1e-05
  );

  annotation (Documentation(info = "<html><body><table><tr><td>name:</td><td>toloxatone</td></tr><tr><td>ATC code:</td><td>N06AG03</td></tr><tr><td>model:</td><td>one compartment, IV dosing <small>(PK_1C)</small></td></tr><tr><td>source:</td><td>Vistelle R et al. 1992</td></tr><tr><td>population:</td><td>anaesthetized rabbits</td></tr><tr><td>measured compound:</td><td>toloxatone</td></tr><tr><td>review:</td><td>curated candidate</td></tr><tr><td>record page:</td><td><a href=\"https://digital-biosystems.github.io/pharmacolibrary-docs/#/drugs/drug_toloxatone/Toloxatone_Vistelle1992_reference\">pharmacolibrary-docs</a></td></tr></table><h4>Parameters as reported in the paper</h4><table border=1 cellspacing=0 cellpadding=2><tr><th>parameter</th><th>value</th><th>unit</th><th>meaning</th></tr><tr><td>terminal half-life</td><td>47.4</td><td>min</td><td><small>t1/2z</small></td></tr><tr><td>total clearance</td><td>79</td><td>mL min-1</td><td><small>CL</small></td></tr><tr><td>volume of distribution</td><td>5.8</td><td>L</td><td><small>V</small></td></tr></table><h4>About toloxatone</h4><p>Toloxatone is a monoamine oxidase A inhibitor that has been used as an antidepressant. It is currently listed only as an experimental drug, suggesting it is not an established marketed medicine today.</p><p><small>Summary written by glm-5.3-flash from <a href=\"https://www.wikidata.org/wiki/Q3530618\">Wikidata Q3530618</a> and the WHO ATC classification; not checked by a person.</small></p><p>Identity, molar mass and metabolites: <a href=\"modelica://Pharmacolibrary.Drugs.Substances.Toloxatone\">Toloxatone</a>.</p><h4>References</h4><ol><li><p>Vistelle R et al. (1992). Toloxatone pharmacokinetics in the plasma and cerebrospinal fluid of the rabbit. <i>The Journal of pharmacy and pharmacology 44(2):124–126</i>. DOI:<a href=\"https://doi.org/10.1111/j.2042-7158.1992.tb03576.x\">10.1111/j.2042-7158.1992.tb03576.x</a> PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/1352813\">1352813</a></p></li></ol></body></html>", revisions = "<html><body><ul><li>10/2026 generated by pharmacolibrary-dev export.pharmacolibrary_models from Vistelle_1992: parameters extracted from the paper by the pharmacolibrary-dev pipeline, model built by its engineer, reviewed: curated candidate</li></ul></body></html>"),
    experiment(StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1));
end Toloxatone_Vistelle1992_reference;
